### ISSUE TITLE
unknown directive "MainRule"

### ISSUE THREAD

**Issue by blotus** [nbs-system/naxsi#13]
_From [leehe...@gmail.com](https://code.google.com/u/102081594063769071803/) on November 24, 2011 03:38:54_

What steps will reproduce the problem? 1.when I reload the nginx , there are some error informations 2. 3. What is the expected output? What do you see instead? 1、nginx: [emerg] unknown directive "MainRule" in /etc/nginx/naxsi_core.rules:13
2、nginx: [emerg] unknown directive " LearningMode " in /etc/nginx/web.rules:1 What version of the product are you using? On what operating system? centos 5.5 Please provide any additional information below.

_Original issue: http://code.google.com/p/naxsi/issues/detail?id=13_

**Comment by hzrandd** [comment]
Firstly.........
$ ./configure --add-module=/usr/local/Cellar/nginx_tcp_proxy_module \
  --add module=/Users/jake/jobs/naxsi-core-0.51-1/naxsi_src
List a port  info.
####################################################
configuring additional modules
adding module in /usr/local/Cellar/nginx_tcp_proxy_module
checking for nginx_tcp_module ... found
 + ngx_tcp_module was configured
adding module in /Users/jake/jobs/naxsi-core-0.51-1/naxsi_src
 + ngx_http_naxsi_module was configured
checking for PCRE library ... found
checking for PCRE JIT support ... not found
checking for OpenSSL library ... found
checking for zlib library ... found
creating objs/Makefile

Configuration summary
  + using system PCRE library
  + using system OpenSSL library
  + md5: using OpenSSL library
  + sha1: using OpenSSL library
  + using system zlib library

  nginx path prefix: "/usr/local/nginx"
  nginx binary file: "/usr/local/nginx/sbin/nginx"
  nginx configuration prefix: "/usr/local/nginx/conf"
  nginx configuration file: "/usr/local/nginx/conf/nginx.conf"
  nginx pid file: "/usr/local/nginx/logs/nginx.pid"
  nginx error log file: "/usr/local/nginx/logs/error.log"
  nginx http access log file: "/usr/local/nginx/logs/access.log"
  nginx http client request body temporary files: "client_body_temp"
  nginx http proxy temporary files: "proxy_temp"
  nginx http fastcgi temporary files: "fastcgi_temp"
  nginx http uwsgi temporary files: "uwsgi_temp"
  nginx http scgi temporary files: "scgi_temp"
####################################################

Second....
$ make 
####################################################
/usr/include/openssl/ssl.h:1547:6: note: 'SSL_CTX_set_client_CA_list' has been explicitly marked deprecated here
void SSL_CTX_set_client_CA_list(SSL_CTX *ctx, STACK_OF(X509_NAME) *name_list) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
     ^
10 warnings generated.
cc -c   -I src/core -I src/event -I src/event/modules -I src/os/unix -I /usr/local/Cellar/nginx_tcp_proxy_module/modules -I /usr/local/Cellar/nginx_tcp_proxy_module/parsers -I /usr/local/Cellar/nginx_tcp_proxy_module -I objs -I src/http -I src/http/modules -I src/mail \
		-o objs/addon/naxsi_src/naxsi_runtime.o \
		/Users/jake/jobs/naxsi-core-0.51-1/naxsi_src/naxsi_runtime.c
cc -c   -I src/core -I src/event -I src/event/modules -I src/os/unix -I /usr/local/Cellar/nginx_tcp_proxy_module/modules -I /usr/local/Cellar/nginx_tcp_proxy_module/parsers -I /usr/local/Cellar/nginx_tcp_proxy_module -I objs -I src/http -I src/http/modules -I src/mail \
		-o objs/addon/naxsi_src/naxsi_config.o \
		/Users/jake/jobs/naxsi-core-0.51-1/naxsi_src/naxsi_config.c
cc -c   -I src/core -I src/event -I src/event/modules -I src/os/unix -I /usr/local/Cellar/nginx_tcp_proxy_module/modules -I /usr/local/Cellar/nginx_tcp_proxy_module/parsers -I /usr/local/Cellar/nginx_tcp_proxy_module -I objs -I src/http -I src/http/modules -I src/mail \
		-o objs/addon/naxsi_src/naxsi_utils.o \
		/Users/jake/jobs/naxsi-core-0.51-1/naxsi_src/naxsi_utils.c
cc -c   -I src/core -I src/event -I src/event/modules -I src/os/unix -I /usr/local/Cellar/nginx_tcp_proxy_module/modules -I /usr/local/Cellar/nginx_tcp_proxy_module/parsers -I /usr/local/Cellar/nginx_tcp_proxy_module -I objs -I src/http -I src/http/modules -I src/mail \
		-o objs/addon/naxsi_src/naxsi_skeleton.o \
		/Users/jake/jobs/naxsi-core-0.51-1/naxsi_src/naxsi_skeleton.c
cc -c   -I src/core -I src/event -I src/event/modules -I src/os/unix -I /usr/local/Cellar/nginx_tcp_proxy_module/modules -I /usr/local/Cellar/nginx_tcp_proxy_module/parsers -I /usr/local/Cellar/nginx_tcp_proxy_module -I objs -I src/http -I src/http/modules -I src/mail \
		-o objs/addon/naxsi_src/naxsi_json.o \
		/Users/jake/jobs/naxsi-core-0.51-1/naxsi_src/naxsi_json.c
cc -c  -I src/core -I src/event -I src/event/modules -I src/os/unix -I /usr/local/Cellar/nginx_tcp_proxy_module/modules -I /usr/local/Cellar/nginx_tcp_proxy_module/parsers -I /usr/local/Cellar/nginx_tcp_proxy_module -I objs \
		-o objs/ngx_modules.o \
		objs/ngx_modules.c
####################################################
let's to see, naxsi info was output.
then.........
$ sudo make install
##### it seems no error. but when i check the configure info:
#########################################################
$ sudo /usr/local/nginx/bin/nginx -V
nginx version: nginx/1.4.4
TLS SNI support enabled
configure arguments: --add-module=/usr/local/Cellar/nginx_tcp_proxy_module
#########################################################
To see,there is no naxsi module.why not ?

**Comment by hzrandd** [comment]
use ModSecurity for Nginx  but not Naxis?
