### ISSUE TITLE
Naxsi blocks when in learning mode

### ISSUE THREAD

**Issue by Napsty** [nbs-system/naxsi#133]
Hi, I'm relatively new to NAXSI so it is possible that a configuration error is the cause for this problem.

I have activated NAXSI on a Debian Wheezy running Nginx 1.2.1. Both Nginx and NAXSI were installed through the official Debian repositories (nginx-naxsi package). 

I have activated NAXSI in nginx.conf and created a first ruleset with the following definition:

```
LearningMode; #Enables learning mode
SecRulesEnabled;
#SecRulesDisabled;
DeniedUrl "/RequestDenied";
## check rules
CheckRule "$SQL >= 8" BLOCK;
CheckRule "$RFI >= 8" BLOCK;
CheckRule "$TRAVERSAL >= 4" BLOCK;
CheckRule "$EVADE >= 4" BLOCK;
CheckRule "$XSS >= 8" BLOCK;
```

Well yeah, that's obviously the same rule file as documented in the Wiki. So LearningMode is enabled. But as soon as I include the rule file in the vhost, site loading problems happen. Sometimes the logo isn't loaded and after a reload of the page the css is not loaded. Then again after another reload the page works fine.

Additional information: The tested page is running on a Tomcat and Nginx serves as Reverse Proxy. The relevant config is here:

```
server {
[...]
  location / {
    include /etc/nginx/naxsi.rules;
    try_files /maintenance.html $uri @tomcat;
  }

  location @tomcat {
    include /etc/nginx/proxy.conf;
    include /etc/nginx/naxsi.rules;
    proxy_pass http://127.0.0.1:8081;
  }
[...]
}
```

Is there a known issue with NAXSI in LearningMode and ReverseProxy settings? Or could it be an issue of an outdated Nginx version (Debian is stable I love it, but I admit somewhat old)? Or is the issue simpler and I'm using a config which is plain wrong?

cheers and thanks for the NAXSI :-)

**Comment by jmce** [comment]
At least in this context 
https://github.com/gplessis/dotdeb-nginx/issues/79
I still get blocking for internal rules 17 and 18, both involving libinjection.
Is there a way to get the expected behavior for those two rules, in  learning mode?

**Comment by jmce** [comment]
Huh, I suppose I can simply set the corresponding CheckRule settings ($LIBINJECTION_SQL, $LIBINJECTION_XSS) to LOG instead of DROP  :) --- by the way, I noticed only now that those are the only cases for which I had DROP instead of BLOCK (using default suggested settings), thus now wondering if that might explain the difference in behavior (learning mode suppressing BLOCK but not DROP?).
