### ISSUE TITLE
naxsi could not log the utf-8 uri into nginx's error log file

### ISSUE THREAD

**Issue by JackieKhuu** [nbs-system/naxsi#143]
We have implement a friendly URL in our website. Therefore, that URL have the utf-8 encode for Vietnamese.
The problem is I could not define a white list for our URLs. Because of naxsi will replace the utf-8 characters with the question mark:
2014/10/31 16:56:13 [error] 28013#0: *47618 NAXSI_EXLOG: ip=117.78.13.17&server=www.mysite.com&uri=/k&id=1010&zone=ARGS&var_name=&content=%3f%3f-s%3f%3f-truy%3f%3f%3fn-d%3f%3f%3fn-(to%3f%3fn-qu%3f%3f%3fc-v%3f%3f-th%3f%3f%3f-tr%3f%3f%3f%3f%3fng-n%3f%3f%3f%3f%3fc-ngo%3f%3fi)-kw, client: 117.78.13.17, server: www.mysite.com, request: "GET /k???-s??-truy???n-d???n-(to??n-qu???c-v??-th???-tr?????ng-n?????c-ngo??i)-kw HTTP/1.0", host: "www.mysite.com"
2014/10/31 16:56:13 [error] 28013#0: *47618 NAXSI_EXLOG: ip=117.78.13.17&server=www.mysite.com&uri=/k&id=1011&zone=ARGS&var_name=&content=%3f%3f-s%3f%3f-truy%3f%3f%3fn-d%3f%3f%3fn-(to%3f%3fn-qu%3f%3f%3fc-v%3f%3f-th%3f%3f%3f-tr%3f%3f%3f%3f%3fng-n%3f%3f%3f%3f%3fc-ngo%3f%3fi)-kw, client: 117.78.13.17, server: www.mysite.com, request: "GET /k???-s??-truy???n-d???n-(to??n-qu???c-v??-th???-tr?????ng-n?????c-ngo??i)-kw HTTP/1.0", host: "www.mysite.com"
2014/10/31 16:56:13 [error] 28013#0: *47618 NAXSI_FMT: ip=117.78.13.17&server=www.mysite.com&uri=/k&learning=1&vers=0.53-1&total_processed=177&total_blocked=1&block=1&cscore0=$SQL&score0=8&cscore1=$XSS&score1=16&zone0=ARGS&id0=1010&var_name0=&zone1=ARGS&id1=1011&var_name1=, client: 117.78.13.17, server: www.mysite.com, request: "GET /k???-s??-truy???n-d???n-(to??n-qu???c-v??-th???-tr?????ng-n?????c-ngo??i)-kw HTTP/1.0", host: "www.mysite.com"

Then when I generate a whitelist with nxapi, the rule will be liked this: 
#msg: A generic, precise wl tpl (url+var+id)
#Rule (1011) parenthesis, probable sql/xss
#total hits 2
#content : ??-s??-truy???n-d???n-(to??n-qu???c-v??-th???-tr?????ng-n?????c-ngo??i)-kw
#peers : 117.78.13.17
#uri : /k
# warnings : rule_ip is 1
# warnings : global_rule_ip_ratio is 2.44
BasicRule  wl:1011 "mz:$URL:/k|ARGS";

Do we have any solution for this issue?
Thank you very much!

**Comment by buixor** [comment]
Hi,

Unfortunately, naxsi does not know how to handle utf8 :(
