### ISSUE TITLE
Install with nginx 1.6.2

### ISSUE THREAD

**Issue by inDream** [nbs-system/naxsi#145]
I'm using Ubuntu 14.04 and cannot install via `apt-get install nginx-naxsi`.
Error message:
```
apt-get install nginx-naxsi
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nginx-naxsi : Depends: nginx-common (= 1.6.2-1+trusty0) but 1.6.2-4+trusty0 is to be installed
               Conflicts: nginx-light but 1.6.2-4+trusty0 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by shellshocker** [comment]
Vote for Debian Jessie public repo. :-)
Just wanted to install it and then BAM! - not supported anymore. I don't want to use nginx without my beloved naxsi!

**Comment by buixor** [comment]
Hi,
Closing the issue as there is not much anything we can do on that :(

**Comment by efkan** [comment]
If you want to install the latest naxsi version of nginx;

first, clear old installations..
then `sudo apt-get install nginx-common=1.6.2-1+trusty0`
then `sudo apt-get install nginx-naxsi=1.6.2-1+trusty0`
