### ISSUE TITLE
Naxsi not forwarding to blockedURL

### ISSUE THREAD

**Issue by perfect-privacy** [nbs-system/naxsi#148]
Hi, 

I tested naxsi some months ago and everything worked fine. However, now that I want to put naxsi into production, I used the same configuration with newer nginx/naxsi versions but forwarding blocked requests to DeniedUrl does not work correctly.

While not in learning mode, requests are forwarded to my defined DeniedUrl location (a backend apache server), but no data about the block request is posted to that url. 
While in learning mode, requests are forwarded if I set naxsi_flag_post_action to 1, but there is also no information posted about the blocked request. 

Shouldn't naxsi post this information? I'm trying to build a captcha site that sends an email if a request was blocked by accident, similar to https://code.google.com/p/naxsi/wiki/DeniedUrl

It this a bug in nginx/naxsi or am I missing something? 

Thanks in advance,
Lars Mueller 

naxsi.rules:
 SecRulesEnabled;
 DeniedUrl "/RequestDenied";
 ..snip.. the default check rules..

location /RequestDenied {
        proxy_pass https://some.other.server.com/blocked.php;
}

blocked.php, dump everything:
<?php 
 var_dump($_SERVER);
 var_dump(apache_request_headers());
 var_dump($_POST);
 var_dump($_GET);
?>

**Comment by buixor** [comment]
Hi,

Yes, post_action changed, and needs to be dynamically enabled with "naxsi_flag_post_action".
We don't use this much (as it might lead to strong performance impact, posting all requests twice), however, you should still be able to use it. In the HTTP headers sent to the /RequestDenied, can you please look for : x-orig-url x-orig-args and x-naxsi-sig ?

Please let me know,
