### ISSUE TITLE
Is there a way to whitelist naxsi internal rule?

### ISSUE THREAD

**Issue by ihacku** [nbs-system/naxsi#152]
#@MainRule "msg:request too big, stored on disk and not parsed" id:2; 

This internal rule caused too many false positive, I tried to delete this line, but seems didn't work.
And sadly I don't have enough time to use learning model.

Sorry for post questions here.

**Comment by ihacku** [comment]
Ok, whitelist internal rules need be done in site's nginx conf, not in naxsi_core.rules.
Like this
            DeniedUrl "/RequestDenied";

            BasicRule wl:0 "mz:$URL:/iis.aspx|ARGS|BODY|URL";
            BasicRule wl:10;
            BasicRule wl:11;  
            CheckRule "$XSS >= 4" BLOCK;

Please close this issue.

**Comment by buixor** [comment]
Hi,
