### ISSUE TITLE
no values for cscore/score when more than 3 signatures are matching

### ISSUE THREAD

**Issue by rogerthat** [nbs-system/naxsi#153]
entry:

2015/01/10 14:46:27 [error] 28308#0: *212228 NAXSI_FMT: ip=193.87.72.194&server=example.com&uri=/sic/sites/viewticket.php&learning=0&vers=0.53-1&total_processed=9644&total_blocked=53&block=1&cscore0=$UWA&score0=4&cscore1=$SQL&score1=4&cscore2=$XSS&score2=8&zone0=HEADERS&id0=42000077&var_name0=user-agent&zone1=BODY&id1=1000&var_name1=tid[sqltype]&zone2=BODY|NAME&id2=1310&var_name2=tid[sqltype]&zone3=BODY|NAME&id3=1311&var_name3=tid[sqltype], client: 193.87.72.194, server: www.example.com, request: "POST /sic/sites/viewticket.php HTTP/1.1", host: "example.com"

this translates into:

    cscore0=$UWA
      score0=4
      zone0=HEADERS
      id0=42000077
      var_name0=user-agent
      
    cscore1=$SQL
      score1=4
      zone1=BODY
      id1=1000
      var_name1=tid[sqltype]
      
    cscore2=$XSS
      score2=8
      zone2=BODY|NAME
      id2=1310
      var_name2=tid[sqltype]
      
    [here are the missing fileds]
      zone3=BODY|NAME
      id3=1311
      var_name3=tid[sqltype],

**Comment by buixor** [comment]
Hi,

Not sure to understand your issue. However, seems naxsi is not in learning mode, so it will stop processing your request as soon as a checkrule provoking a block is triggered.

**Comment by rogerthat** [comment]
nevermind, it's not an issue but a problem with multiple attacks within one request
