### ISSUE TITLE
naxsi block all connection

### ISSUE THREAD

**Issue by ezako2** [nbs-system/naxsi#154]
its block all connection , I have put the include in 
http 
{...
include mime.types;
include naxsi_core.rules;
...}
and when I open my website CLEAN url , (just the home page)
I see this error

> 2015/01/20 12:38:05 [error] 17619#0: *257 NAXSI_FMT: ip=XXX.XXX.XX&server=sub.domain.com&uri=/&learning=1&vers=0.53-1&total_processed=1&total_blocked=1&block=1&cscore0=$SQL&score0=42&cscore1=$XSS&score1=224&zone0=HEADERS&id0=1002&var_name0=cookie&zone1=HEADERS&id1=1005&var_name1=cookie&zone2=HEADERS&id2=1010&var_name2=cookie&zone3=HEADERS&id3=1011&var_name3=cookie&zone4=HEADERS&id4=1315&var_name4=cookie, client: 105.200.112.171, server: www.sub.domain.com, request: "GET / HTTP/1.1", host: "sub.domain.com"

when test injected link, its also give me the error
> 2015/01/20 12:39:36 [error] 17624#0: *1218 NAXSI_FMT: ip=XXX.XXX.XXX&server=sub.domain.com&uri=/&learning=1&vers=0.53-1&total_processed=3&total_blocked=2&block=1&cscore0=$SQL&score0=42&cscore1=$XSS&score1=232&zone0=HEADERS&id0=1002&var_name0=cookie&zone1=HEADERS&id1=1005&var_name1=cookie&zone2=HEADERS&id2=1010&var_name2=cookie&zone3=HEADERS&id3=1011&var_name3=cookie&zone4=HEADERS&id4=1315&var_name4=cookie&zone5=ARGS&id5=1302&var_name5=a, client: 105.200.112.171, server: www.sub.domain.com, request: "GET /?a=%3C HTTP/1.1", host: "sub.domain.com"

I install lastest version of naxsi and nginx 1.6.2

**Comment by buixor** [comment]
Yep, that's expected, because of your cookies containing characters or things that match naxsi rules.
You should either put naxsi in learning mode and/or perform learning on your website.
