### ISSUE TITLE
Infinite loop in nxtool.py --fifo

### ISSUE THREAD

**Issue by scollazo** [nbs-system/naxsi#156]
Steps to reproduce:
 - Start nxtool.py with ``nxtool.py --fifo=/tmp/fifo``
 - Start nginx.  ``error_log`` must be configured to use the fifo (/tmp/fifo in this case)
 - Stop nginx

While nginx is up, nxtool works as expected, feeding logs to elasticsearch, but if nginx stops, there is an infinite loop that puts the cpu to 100% usage.

**Comment by gradew** [comment]
Hi,

Just adding some feedback to this ticket: I had the exact same problem yesterday when trying to feed nxtool.py with --stdin: it goes into an infinite loop and keeps displaying "start - stop\n".
Same command with --file worked just fine, though.

**Comment by buixor** [comment]
closed by chazz :)
