### ISSUE TITLE
Segmentation fault with long GET

### ISSUE THREAD

**Issue by harston** [nbs-system/naxsi#161]
When i'll get GET request where ARGS have about 35000 characters there is a problem with ngx_http_nx_log() (coredump)

Program terminated with signal 11, Segmentation fault.
#0  0x0000000000481215 in ngx_http_nx_log ()

I've found that problem can be with:

naxsi_src/naxsi_runtime.c:797:#define MAX_LINE_SIZE (NGX_MAX_ERROR_STR - 100)

Default NGX_MAX_ERROR_STR in Nginx is 2048, but increase it to 8192 solves the problem.

**Comment by buixor** [comment]
Hi, 

Please see issue 162, we are going to pull @nzin patch.
Closing this one, please follow up on issue 162.

**Comment by nzin** [comment]
ok.

will not have time soon, but I will check that
