### ISSUE TITLE
Segmentation fault with /`echo skip`

### ISSUE THREAD

**Issue by apleks** [nbs-system/naxsi#162]
I was able to produce a segmentation fault if accessing a GET such as:

http://mysite.domain.tld/`echo skip`

This popped out while testing Naxsi with a vanilla skipfish scan as you can see in the gdb backtrace below:

(gdb) backtrace full
#0  ngx_vslprintf (
    buf=0x7fff2b043be3 ".53-1&total_processed=419&total_blocked=17&block=1&cscore0=$XSS&score0=32&zone0=URL&id0=1314&var_name0=, client: 10.128.58.13, server: mysite.domain.tld, request: \"GET /`echo%24{IFS}skip12``echo%24{IFS}34fi"...,
    buf@entry=0x7fff2b043bab "NAXSI_FMT: ip=10.128.58.13&server=mysite.domain.tld&uri=/`echo.53-1&total_processed=419&total_blocked=17&block=1&cscore0=$XSS&score0=32&zone0=URL&id0=1314&var_name0=, client: 10.128.58.13, server: mysite.domain.tld"..., last=last@entry=0x7fff2b044380 "9#0: *10(",
    fmt=0x7fff2b04457b "skip12``echo%2034fish`&learning=0&vers=0.53-1&total_processed=420&total_blocked=18&block=1&cscore0=$XSS&score0=32&zone0=URL&id0=1314&var_name0=",
    fmt@entry=0x7fff2b044540 "NAXSI_FMT: ip=10.128.58.13&server=mysite.domain.tld&uri=/`echo%20skip12``echo%2034fish`&learning=0&vers=0.53-1&total_processed=420&total_blocked=18&block=1&cscore0=$XSS&score0=32&zone0=URL&id0=1314&var_name"..., args=args@entry=0x7fff2b044388) at src/core/ngx_string.c:256
        p = 0x0
        zero = <optimized out>
        d = <optimized out>
        f = <optimized out>
        len = <optimized out>
        slen = 18446744073709551615
        i64 = 0
        ui64 = 0
        frac = <optimized out>
        ms = <optimized out>
        width = <optimized out>
        sign = 1
        hex = 0
        max_width = 0
        frac_width = 0
        scale = <optimized out>
---Type <return> to continue, or q <return> to quit---
        n = <optimized out>
        v = <optimized out>
        vv = <optimized out>
#1  0x0000000000408673 in ngx_log_error_core (level=level@entry=4, log=0x1077df0, err=err@entry=0,
    fmt=fmt@entry=0x7fff2b044540 "NAXSI_FMT: ip=10.128.58.13&server=mysite.domain.tld&uri=/`echo%20skip12``echo%2034fish`&learning=0&vers=0.53-1&total_processed=420&total_blocked=18&block=1&cscore0=$XSS&score0=32&zone0=URL&id0=1314&var_name"...) at src/core/ngx_log.c:119
        args = {{gp_offset = 40, fp_offset = 48, overflow_arg_area = 0x7fff2b044490, reg_save_area = 0x7fff2b0443a0}}
        p = 0x7fff2b043bab "NAXSI_FMT: ip=10.128.58.13&server=mysite.domain.tld&uri=/`echo.53-1&total_processed=419&total_blocked=17&block=1&cscore0=$XSS&score0=32&zone0=URL&id0=1314&var_name0=, client: 10.128.58.13, server: mysite.domain.tld"...
        last = 0x7fff2b044380 "9#0: *10("
        msg = 0x7fff2b043bab "NAXSI_FMT: ip=10.128.58.13&server=mysite.domain.tld&uri=/`echo.53-1&total_processed=419&total_blocked=17&block=1&cscore0=$XSS&score0=32&zone0=URL&id0=1314&var_name0=, client: 10.128.58.13, server: mysite.domain.tld"...
        errstr = "2015/02/11 20:35:07 [error] 20719#0: *1041 NAXSI_FMT: ip=10.128.58.13&server=mysite.domain.tld&uri=/`echo.53-1&total_processed=419&total_blocked=17&block=1&cscore0=$XSS&score0=32&zone0=URL&id0=1314&var_name"...
        wrote_stderr = <optimized out>
        debug_connection = <optimized out>
#2  0x0000000000484fb1 in ngx_log_naxsi (level=level@entry=4, r=r@entry=0x107b4f0, err=err@entry=0, fmt=fmt@entry=0x496ca7 "NAXSI_FMT: %s")
    at ../naxsi/naxsi_src//naxsi_log.c:260
        args = {{gp_offset = 40, fp_offset = 48, overflow_arg_area = 0x7fff2b044e50, reg_save_area = 0x7fff2b044d60}}
        loc = 0x109aec8
        main_cf = 0x1072490
        p = <optimized out>
        last = 0x7fff2b044d3f ""
        errstr = "NAXSI_FMT: ip=10.128.58.13&server=mysite.domain.tld&uri=/`echo%20skip12``echo%2034fish`&learning=0&vers=0.53-1&total_processed=420&total_blocked=18&block=1&cscore0=$XSS&score0=32&zone0=URL&id0=1314&var_name"...
---Type <return> to continue, or q <return> to quit---
        logarray = <optimized out>
        l = <optimized out>
#3  0x000000000047da6c in ngx_http_output_forbidden_page (ctx=ctx@entry=0x107c3a8, r=r@entry=0x107b4f0) at ../naxsi/naxsi_src//naxsi_runtime.c:963
        i = 0
        tmp_uri = 0x1073590
        denied_args = <optimized out>
        empty = {len = 0, data = 0x4912cf ""}
        cf = 0x109aec8
        ostr = 0x1073558
        h = <optimized out>
#4  0x00000000004843e4 in ngx_http_dummy_access_handler (r=0x107b4f0) at ../naxsi/naxsi_src//naxsi_skeleton.c:1170
        ctx = 0x107c3a8
        rc = <optimized out>
        cf = 0x109aec8
        tmsstart = {tms_utime = 4, tms_stime = 19, tms_cutime = 0, tms_cstime = 0}
        tmsend = {tms_utime = 4, tms_stime = 19, tms_cutime = 0, tms_cstime = 0}
        start = 472412092
        end = 472412092
        lookup = <optimized out>
        learning_flag = {len = 19, data = 0x4974d2 "naxsi_flag_learning"}
        enable_flag = {len = 17, data = 0x4974c0 "naxsi_flag_enable"}
        post_action_flag = {len = 22, data = 0x4974e6 "naxsi_flag_post_action"}
        extensive_log_flag = {len = 19, data = 0x4974fd "naxsi_extensive_log"}
#5  0x0000000000436159 in ngx_http_core_rewrite_phase (r=0x107b4f0, ph=0x10a24c0) at src/http/ngx_http_core_module.c:942
        rc = <optimized out>
---Type <return> to continue, or q <return> to quit---
#6  0x0000000000432273 in ngx_http_core_run_phases (r=r@entry=0x107b4f0) at src/http/ngx_http_core_module.c:888
        rc = <optimized out>
        ph = 0x10a2490
        cmcf = <optimized out>
#7  0x0000000000432382 in ngx_http_handler (r=r@entry=0x107b4f0) at src/http/ngx_http_core_module.c:871
        cmcf = <optimized out>
#8  0x000000000043d3bf in ngx_http_process_request (r=r@entry=0x107b4f0) at src/http/ngx_http_request.c:1901
        c = 0x10a6518
#9  0x000000000043d79a in ngx_http_process_request_headers (rev=rev@entry=0x10dc058) at src/http/ngx_http_request.c:1332
        p = <optimized out>
        len = <optimized out>
        n = <optimized out>
        rc = <optimized out>
        rv = <optimized out>
        h = <optimized out>
        c = 0x10a6518
        hh = <optimized out>
        r = 0x107b4f0
        cscf = 0x1098a10
        cmcf = 0x1070cf0
#10 0x000000000043dac3 in ngx_http_process_request_line (rev=rev@entry=0x10dc058) at src/http/ngx_http_request.c:1012
        n = <optimized out>
        rc = <optimized out>
        rv = <optimized out>
        host = {len = 17458456, data = 0x10a6518 "\360\264\a\001"}
---Type <return> to continue, or q <return> to quit---
        c = 0x10a6518
        r = 0x107b4f0
#11 0x000000000043e606 in ngx_http_keepalive_handler (rev=0x10dc058) at src/http/ngx_http_request.c:3182
        size = 1024
        n = <optimized out>
        b = 0x1077ed8
        c = 0x10a6518
#12 0x000000000041f649 in ngx_event_process_posted (cycle=cycle@entry=0x106f4e0, posted=0x6bd890 <ngx_posted_events>) at src/event/ngx_event_posted.c:33
        q = 0x10dc0a8
        ev = 0x10dc058
#13 0x000000000041f131 in ngx_process_events_and_timers (cycle=cycle@entry=0x106f4e0) at src/event/ngx_event.c:265
        flags = 1
        timer = <optimized out>
        delta = 1
#14 0x00000000004267b9 in ngx_worker_process_cycle (cycle=0x106f4e0, data=<optimized out>) at src/os/unix/ngx_process_cycle.c:824
        worker = <optimized out>
        i = <optimized out>
        c = <optimized out>
#15 0x0000000000424e0f in ngx_spawn_process (cycle=cycle@entry=0x106f4e0, proc=proc@entry=0x4266c5 <ngx_worker_process_cycle>, data=data@entry=0x1,
    name=name@entry=0x48a026 "worker process", respawn=respawn@entry=-3) at src/os/unix/ngx_process.c:198
        on = 1
        pid = 0
        s = 1
#16 0x00000000004259de in ngx_start_worker_processes (cycle=cycle@entry=0x106f4e0, n=4, type=type@entry=-3) at src/os/unix/ngx_process_cycle.c:368
        i = 1
---Type <return> to continue, or q <return> to quit---
        ch = {command = 1, pid = 20718, slot = 0, fd = 3}
#17 0x00000000004270f4 in ngx_master_process_cycle (cycle=cycle@entry=0x106f4e0) at src/os/unix/ngx_process_cycle.c:140
        title = 0x10a290c "master process /usr/local/nginx/sbin/nginx"
        p = <optimized out>
        size = <optimized out>
        i = <optimized out>
        n = <optimized out>
        sigio = <optimized out>
        set = {__val = {0 <repeats 16 times>}}
        itv = {it_interval = {tv_sec = 17238025, tv_usec = 0}, it_value = {tv_sec = 0, tv_usec = 0}}
        live = <optimized out>
        delay = <optimized out>
        ls = <optimized out>
        ccf = 0x1070510
#18 0x0000000000407dd3 in main (argc=<optimized out>, argv=<optimized out>) at src/core/nginx.c:407
        i = <optimized out>
        log = 0x6bab00 <ngx_log>
        cycle = 0x106f4e0
        init_cycle = {conf_ctx = 0x0, pool = 0x106e960, log = 0x6bab00 <ngx_log>, new_log = {log_level = 0, file = 0x0, connection = 0, handler = 0x0, data = 0x0,
            writer = 0x0, wdata = 0x0, action = 0x0, next = 0x0}, log_use_stderr = 0, files = 0x0, free_connections = 0x0, free_connection_n = 0,
          reusable_connections_queue = {prev = 0x0, next = 0x0}, listening = {elts = 0x0, nelts = 0, size = 0, nalloc = 0, pool = 0x0}, paths = {elts = 0x0,
            nelts = 0, size = 0, nalloc = 0, pool = 0x0}, open_files = {last = 0x0, part = {elts = 0x0, nelts = 0, next = 0x0}, size = 0, nalloc = 0, pool = 0x0},
          shared_memory = {last = 0x0, part = {elts = 0x0, nelts = 0, next = 0x0}, size = 0, nalloc = 0, pool = 0x0}, connection_n = 0, files_n = 0,
          connections = 0x0, read_events = 0x0, write_events = 0x0, old_cycle = 0x0, conf_file = {len = 21, data = 0x48550e "/etc/nginx/nginx.conf"}, conf_param = {
            len = 0, data = 0x0}, conf_prefix = {len = 11, data = 0x48550e "/etc/nginx/nginx.conf"}, prefix = {len = 17, data = 0x4854fc "/usr/local/nginx/"},
---Type <return> to continue, or q <return> to quit---
          lock_file = {len = 0, data = 0x0}, hostname = {len = 0, data = 0x0}}
        ccf = <optimized out>
(gdb)

CONFIGS:

user                nobody;
worker_processes    4;
worker_rlimit_core  800M;
working_directory   /tmp/;
 error_log           /var/log/nginx/error.log;
pid                 /var/run/nginx.pid;
 events {
     worker_connections 1024;
     use epoll;
     # multi_accept on;
}
http {
     include                        /etc/nginx/mime.types;
     server_names_hash_bucket_size  128;
     access_log                     /var/log/nginx/access.log;
     sendfile                       on;
     keepalive_timeout              65;
     tcp_nodelay                    on;
     gzip                           on;
     gzip_disable                   "MSIE [1-6]\.(?!.*SV1)";
     include                        /etc/nginx/sites-enabled/*;
}
 
Virtualhost config:
server {
     proxy_set_header  Proxy-Connection "";
     listen            *:80;
     server_name    mysite.domain.tld
     access_log        /var/log/nginx/access.log;
     error_log         /var/log/nginx/error.log debug;  
     location / {
          proxy_pass        http://backend.domain.tld/;
          proxy_set_header  Host backend.domain.tld;
     }
     location /RequestDenied {
         return 418;
     }
}

Hope this helps, let me know if you need more.

**Comment by buixor** [comment]
Hi,

This seems to be related to @nzin patch for logging.
We already faced a previous crash with this patch, we are going to pull it before next release.
We are going to reverse on master and ping you back then.

**Comment by buixor** [comment]
Hi,

Patch reverted, works "as expected".
@nzin's patch might be merged later once fixed etc.

Closing the issue, don't hesitate to re-open if you find anything weird :)
And thanks !
