### ISSUE TITLE
Tutorial Mistake...  # size :1000

### ISSUE THREAD

**Issue by Keithsc** [nbs-system/naxsi#163]
Hi, there appears to be an error on the following wiki page. If I run the nxtool.py accoring to the documentation then the output is just "size :1000' 

But If I put a = inbetween --filter and 'url /myurl' then nxtool works and outputs loads of text.
https://github.com/nbs-system/naxsi/tree/master/nxapi

nxtool.py -c nxapi.json -s www.x1.fr -f --filter 'uri /foo/bar/test' --slack
size :1000

nxtool.py -c nxapi.json -s www.x1.fr -f --filter='uri /foo/bar/test' --slack
size :1000
template :tpl/.......

I hope this mioght help someone.

**Comment by buixor** [comment]
Hi,

I can't reproduce the issue, with or without '=' between --filter and actual fiter seems to work.
