### ISSUE TITLE
naxsi wordpress rule

### ISSUE THREAD

**Issue by proteansec** [nbs-system/naxsi#164]
Hi,

The following rule is getting hit when saving a draft post in WP:
1 NAXSI_FMT: ip=1.2.3.4&server=www.domain.com&uri=/wp-admin/post.php&learning=0&total_processed=1&total_blocked=1&zone0=BODY|NAME&id0=1310&var_name0=post_category[]&zone1=BODY|NAME&id1=1311&var_name1=post_category[], client: 1.2.3.4, server: www.domain.com, request: "POST /wp-admin/post.php HTTP/1.1", host: "www.domain.com", referrer: "https://www.domain.com/wp-admin/post.php?post=24338&action=edit&message=10"

I'm adding the following rules to the config, but the rule is still being hit.

BasicRule wl:1310,1311 "mz:$URL:/wp-admin/post.php|BODY|NAME";
BasicRule wl:1310,1311 "mz:$URL:/wp-admin/post.php|$BODY_VAR:post_category[]|NAME";

Can you tell me whether this is a bug?

**Comment by buixor** [comment]
Hi,

The first rule should be enough to cover the exception :

BasicRule wl:1310,1311 "mz:$URL:/wp-admin/post.php|BODY|NAME";

Can you conform this is not a human mistake ? I fail to reproduce your bug.
