### ISSUE TITLE
$URL_X with POST Requests

### ISSUE THREAD

**Issue by khaefeli** [nbs-system/naxsi#165]
Hi!

I tried to whitelist the complete (wl:0) magento backend with an URL_X regex for the matchzone URL:

    BasicRule wl:0 "mz:$URL_X:^/admin/|URL";

or with BODY for the POST request:

    BasicRule wl:0 "mz:$URL_X:^(.*)/admin/(.*)|BODY";

or even more "open" stuff like:

    BasicRule wl:0 "mz:$URL_X:admin";

etc etc. but it doesn't work. the regex testing tool matches.

If I use the whitelist rules form nx_util, everything works:

    BasicRule wl:1310,1311 "mz:$URL:/admin|$BODY_VAR:login[password]|NAME";
    BasicRule wl:1310,1311 "mz:$URL:/admin|$BODY_VAR:login[username]|NAME";

but not if I modify that to:

    BasicRule wl:1310,1311 "mz:$URL:/admin|BODY";
    BasicRule wl:1310,1311 "mz:$URL:/admin|BODY";

Login URL is: http://www.domain.ch/admin
in the end, it should also work for http://www.domain.ch/index.php/admin
or when the backend is stored under a sub-subdir http://www.domain.ch/shop/admin

(for sure, the best and most secure way  is to use the generated whitelists. )

Cheers

**Comment by buixor** [comment]
Hi,

1°) Regarding regexes with several matching groups  : BasicRule wl:0 "mz:$URL_X:^(.*)/admin/(.*)|BODY";
We actually identified a bug a few weeks ago that is related to PCRE output vectors (which impact the number of matching groups you can use). We faced the same issue here, and on master/ the output vector size has been increased, to allow up to ~10 matching vs ~2 now.

2°) Regarding the whitelist that do not seem to work : BasicRule wl:0 "mz:$URL_X:^/admin/|URL";
This is really weird, as it should work (pretty sure it does :p). However - we do host a lot of magento as well - and we tend to create another location for /admin and filter it by ip, and deactivate naxsi on it. Please note that wl:0 does not disable internal rules !

BasicRule wl:0 "mz:$URL_X:admin"; #this whitelist is not valid, as you do not specify match zone ($URL..:/x is not a match zone)

Let me know :)

**Comment by khaefeli** [comment]
Hi Buixor,

Thank you for your answer!

I've compiled the newest version of your great  naxsi now, to avoid the PRCE output vector bug.
But the issue is still there. I tried to "breakdown" the problem, but It's really wired:

    BasicRule wl:1310,1311 "mz:$URL:/admin|$BODY_VAR:login[password]|NAME";
    BasicRule wl:1310,1311 "mz:$URL:/admin|$BODY_VAR:login[username]|NAME";
    BasicRule wl:1310,1311 "mz:$URL:/admin/|$BODY_VAR:login[password]|NAME";
    BasicRule wl:1310,1311 "mz:$URL:/admin/|$BODY_VAR:login[username]|NAME";

When I use this  four rules, I can login into the magento backend and everything is fine.
But when I comment them out and insert:

    BasicRule wl:1310,1311 "mz:$URL:/admin|BODY";

to whitelist  the post request, the login POST is blocked with the following log entry:

    2015/03/03 09:49:27 [error] 9810#0: *47 NAXSI_FMT: ip=91.199.98.29&server=www.domain.ch&uri=/admin&learning=0&vers=0.53-1&total_processed=2&total_blocked=1&block=1&cscore0=$XSS&score0=8&zone0=BODY|NAME&id0=1310&var_name0=login[username]&zone1=BODY|NAME&id1=1311&var_name1=login[username], client: 91.199.98.29, server: www.domain.ch, request: "POST /admin HTTP/1.1", host: "www.domain.ch", referrer: "http://www.domain.ch/admin"

also the regex whitelists above aren't working. But maybe it's the same issue, that |BODY or |ARGS aren't working correct?

We're using Debien Jessie with Nginx 1.6.2 and libpcre3:amd64 2:8.35-3.3

Regards,
Kevin

**Comment by buixor** [comment]
Hi,

I think there is a slight mistake here :
 - |BODY and |BODY|NAME are not the same. If you want to whitelist something in the variable 'name' instead of its 'content', you should use BasicRule wl:1310,1311 "mz:$URL:/admin|BODY|NAME";


Please don't hesitate to reopen if you still face issues

**Comment by khaefeli** [comment]
(facepalm) thank you. works

**Comment by nix0x00** [comment]
I am also having same issue with magento. I used following rules thinking it will allow everything on "/admin" directory. but blocks every request.

```
BasicRule wl:0 "mz:$URL_X:^/admin/|URL";
BasicRule wl:1 "mz:$URL:/admin|BODY";
BasicRule wl:1310,1311 "mz:$URL:/admin|BODY|NAME";
```

One thing I did not understand from above comments, is `wl:[NUMBER]`, is 0 or 1310 etc some specific codes? or we can use any number with wl:?

**Comment by wargio** [comment]
you can check the ids here: https://github.com/nbs-system/naxsi/blob/master/naxsi_config/naxsi_core.rules

**Comment by nix0x00** [comment]
I think for me, 1310,1311 should work, but I still see everything is being blocked in admin directory. I have following rules now.

Is there any rules file for Magento?

```
BasicRule wl:1310,1311 "mz:$URL_X:^/admin/|URL";
BasicRule wl:1310,1311 "mz:$URL:/admin|BODY";
BasicRule wl:1310,1311 "mz:$URL:/admin|BODY|NAME";
```

**Comment by wargio** [comment]
are you sure that those are the rules that triggers the block?
I would suggest to not enable naxsi on the admin panel, and instead add a rule to enable it only on non-admin pages on nginx; instead on the admin pages i would add ip filtering rules or basic auth.

**Comment by nix0x00** [comment]
Sample error:

`05#14405: *1 "/var/www/user/admin/mpreports/dashboard/index.php" is not found (2: No such file or directory), client: x.x.x.x, server: www.domain.com, request: "GET /admin/mpreports/dashboard/ HTTP/1.1", host: "www.domain.com", referrer: "https://www.domain.com/admin/mpreports/dashboard/index/key/ea35b65fe302866d1c691fc286d3321ca0bc81eeb22/"`

Firstly, I just want naxsi to ignore "admin" directory. What rule should I apply to ignore this very directory? Secondly, can you please tell me about any documentation (if available) for the whitelist rules.

**Comment by wargio** [comment]
just place all the naxsi stuff (see below) in a config file that you can include via nginx config:

- file: `/my/path/enable_naxsi.conf`

```
  #Enable naxsi
   SecRulesEnabled;
   #Define where blocked requests go
   DeniedUrl "/50x.html"; 
   #CheckRules, determining when naxsi needs to take action
   CheckRule "$SQL >= 8" BLOCK;
   CheckRule "$RFI >= 8" BLOCK;
   CheckRule "$TRAVERSAL >= 4" BLOCK;
   CheckRule "$EVADE >= 4" BLOCK;
   #naxsi logs goes there
   error_log /.../foo.log;
   # my whitelist
   BasicRule wl:1310,1311 "mz:$URL_X:^/admin/|URL";
   BasicRule wl:1310,1311 "mz:$URL:/admin|BODY";
   BasicRule wl:1310,1311 "mz:$URL:/admin|BODY|NAME";
``

then just include the file via the `include` directive in the nginx config.

`sites-enabled/www.domain.com.conf`

```
 server {
  listen ...;
  server_name  ...;
  location /admin {
   ... do some stuff ...
  }
  location / {
   include /my/path/enable_naxsi.conf
   ... do some stuff but public ...
  }
  error_page   500 502 503 504  /50x.html;
  #This is where the blocked requests are going
  location = /50x.html {
  return 418; #I'm a teapot \o/
  }
 }
```

**Comment by wargio** [comment]
btw is blocked on the cookie value by the rule id 1315

**Comment by nix0x00** [comment]
Its not working, I have tried following rules but its still blocking.

```
BasicRule wl:1310,1311 "mz:$URL:/admin|URL";
BasicRule wl:1310,1311 "mz:$URL:/admin|BODY";
BasicRule wl:1310,1311 "mz:$URL:/admin|BODY|NAME";
BasicRule wl:1310,1311 "mz:$URL:/admin/mpreports/|BODY";
```

**Comment by wargio** [comment]
as i said before the issue you are having is linked to rule `1315`. what you need to do is to add
`BasicRule wl:1315 "mz:$HEADERS_VAR:cookie";`

**Comment by nix0x00** [comment]
I have added it, and now the rules i have are:

```
BasicRule wl:1310,1311 "mz:$URL:/lavestirNoCPl|URL";
BasicRule wl:1310,1311 "mz:$URL:/lavestirNoCPl|BODY";
BasicRule wl:1310,1311 "mz:$URL:/lavestirNoCPl|BODY|NAME";
BasicRule wl:1310,1311 "mz:$URL:/lavestirNoCPl/mpreports/|BODY";
BasicRule wl:1315 "mz:$HEADERS_VAR:cookie";
```

**However, I have same errors related to XSS.** 

`2020/08/03 09:09:00 [error] 3384#3384: *10 NAXSI_FMT: ip=x.x.x.x&server=www.example.com&uri=/exampleMkHg/admin/index/index/key/4bc6a37802a4fefac130caf314cf018e5162f5e79cb6362cc472a99875d5b881/&learning=0&vers=0.56&total_processed=5&total_blocked=1&block=1&cscore0=$XSS&score0=8&zone0=BODY|NAME&id0=1310&var_name0=login%5Busername%5D&zone1=BODY|NAME&id1=1311&var_name1=login%5Busername%5D, client: x.x.x.x, server: www.example.com, request: "POST /exampleMkHg/admin/index/index/key/4bc6a37802a4fefac130caf31c472a99875d5b881/ HTTP/1.1", host: "www.example.com", referrer: "https://www.example.com/exampleMkHg/admin/index/index/key/4bc6a37802a4feface5162f5e79cb6362cc472a99875d5b881/"`

`2020/08/03 09:09:22 [error] 3384#3384: *16 NAXSI_FMT: ip=x.x.x.x&server=www.example.com&uri=/exampleMkHg/mpreports/cards/loadcard/key/48bcf2964c7155066d3b769dca5852771332c59e5cdf47cba317b9585e54a424/&learning=0&vers=0.56&total_processed=8&total_blocked=2&block=1&cscore0=$XSS&score0=8&zone0=BODY|NAME&id0=1310&var_name0=daterange%5B0%5D&zone1=BODY|NAME&id1=1311&var_name1=daterange%5B0%5D, client: x.x.x.x, server: www.example.com, request: "POST /exampleMkHg/mpreports/cards/loadcard/key/48bcf2964c7155066d3b769dca5852771332c594a424/?isAjax=true HTTP/1.1", host: "www.example.com", referrer: "https://www.example.com/exampleMkHg/mpreports/dashboard/index/key/8abf6c4f9ad1d351323a4310fcb4f1c7a44644b066f24d4dc/" `

**Comment by wargio** [comment]
i'm sorry, but i told you to not use naxsi on admin pages. just enable it on non admin pages.
