### ISSUE TITLE
new libinjection, plenty of compiler issues

### ISSUE THREAD

**Issue by itpp16** [nbs-system/naxsi#167]
naxsi_skeleton.c(410) : error C2275: 'ngx_http_special_score_t' : illegal use of this type as an expression
naxsi_skeleton.c(410) : error C2065: 'libjct_sql' : undeclared identifier
naxsi_skeleton.c(411) : error C2275: 'ngx_http_special_score_t' : illegal use of this type as an expression
naxsi_skeleton.c(411) : error C2065: 'libjct_xss' : undeclared identifier
naxsi_skeleton.c(412) : error C2065: 'libjct_sql' : undeclared identifier
naxsi_skeleton.c(412) : error C2065: 'libjct_xss' : undeclared identifier
naxsi_skeleton.c(413) : error C2065: 'libjct_sql' : undeclared identifier
naxsi_skeleton.c(413) : error C2223: left of '->sc_tag' must point to struct/union
naxsi_skeleton.c(414) : error C2065: 'libjct_xss' : undeclared identifier
naxsi_skeleton.c(414) : error C2223: left of '->sc_tag' must point to struct/union
naxsi_skeleton.c(415) : error C2065: 'libjct_sql' : undeclared identifier
naxsi_skeleton.c(415) : error C2223: left of '->sc_tag' must point to struct/union
naxsi_skeleton.c(415) : error C2065: 'libjct_xss' : undeclared identifier
naxsi_skeleton.c(415) : error C2223: left of '->sc_tag' must point to struct/union
naxsi_skeleton.c(416) : error C2065: 'libjct_sql' : undeclared identifier
naxsi_skeleton.c(416) : error C2223: left of '->sc_tag' must point to struct/union
naxsi_skeleton.c(417) : error C2065: 'libjct_xss' : undeclared identifier
naxsi_skeleton.c(417) : error C2223: left of '->sc_tag' must point to struct/union
naxsi_skeleton.c(418) : error C2065: 'libjct_sql' : undeclared identifier
naxsi_skeleton.c(418) : error C2223: left of '->sc_tag' must point to struct/union
naxsi_skeleton.c(418) : error C2065: 'libjct_xss' : undeclared identifier
naxsi_skeleton.c(418) : error C2223: left of '->sc_tag' must point to struct/union
naxsi_skeleton.c(419) : error C2065: 'libjct_sql' : undeclared identifier
naxsi_skeleton.c(419) : error C2223: left of '->sc_tag' must point to struct/union
naxsi_skeleton.c(419) : warning C4047: 'function' : 'const char *' differs in levels of indirection from 'int'
naxsi_skeleton.c(419) : warning C4024: 'strncpy' : different types for formal and actual parameter 2
naxsi_skeleton.c(419) : error C2198: 'strncpy' : too few arguments for call
naxsi_skeleton.c(420) : error C2065: 'libjct_xss' : undeclared identifier
naxsi_skeleton.c(420) : error C2223: left of '->sc_tag' must point to struct/union
naxsi_skeleton.c(420) : warning C4047: 'function' : 'const char *' differs in levels of indirection from 'int'
naxsi_skeleton.c(420) : warning C4024: 'strncpy' : different types for formal and actual parameter 2
naxsi_skeleton.c(420) : error C2198: 'strncpy' : too few arguments for call
naxsi_skeleton.c(421) : error C2065: 'libjct_xss' : undeclared identifier
naxsi_skeleton.c(421) : error C2223: left of '->sc_tag' must point to struct/union
naxsi_skeleton.c(422) : error C2065: 'libjct_sql' : undeclared identifier
naxsi_skeleton.c(422) : error C2223: left of '->sc_tag' must point to struct/union
naxsi_skeleton.c(423) : error C2065: 'libjct_sql' : undeclared identifier
naxsi_skeleton.c(423) : error C2223: left of '->sc_score' must point to struct/union
naxsi_skeleton.c(424) : error C2065: 'libjct_xss' : undeclared identifier
naxsi_skeleton.c(424) : error C2223: left of '->sc_score' must point to struct/union

**Comment by buixor** [comment]
Hello dear friend from the mystical windows realm :)

Can you provide a bit more details on the errors ?
Seem it didn't like our declarations in the style "naxsi_skeleton.c:  ngx_http_special_score_t *libjct_xss = ngx_array_push(nx_int__libinject_xss->sscores);"

**Comment by itpp16** [comment]
Alice in wonderland here :) what else would you like to know? undeclared identifiers can be easily solved but;
typedef struct
{
  ngx_array_t	*special_scores;
............
  ngx_http_special_score_t *libjct_sql = ngx_array_push(nx_int__libinject_sql->sscores);
  ngx_http_special_score_t *libjct_xss = ngx_array_push(nx_int__libinject_xss->sscores);

Not that easily.

**Comment by buixor** [comment]
Hello Alice,

mmh either I missed something, or you forgot some data in your paste ?
I still don't get the error :p

**Comment by itpp16** [comment]
Initially those lines should not occur in the middle of code, moved them to the top of function.
Fixed the rest but it crashes hard, could be the while (TRUE / 1) items (which is really bad coding)...
