### ISSUE TITLE
Remove rule 1315 will cause all rule bypass

### ISSUE THREAD

**Issue by ihacku** [nbs-system/naxsi#168]
rule 1315 is "rx:%[2|3]."  "msg:double encoding !”, it cause false positive sometimes. 

like this one 

targetUrl=http%3A%2F%2Fwww%2Etieyou%2Ecom%2Fbuy_now%2Ephp%3Ffrom%3D%25E5%25B1%25B1%25E6%25B5%25B7%25E5%2585%25B3%26to%3D%25E6%2599%258F%25E5%259F%258E%26checi%3DK958%252FK955

I know it's sounds silly to remove a main rule, but I’m a lazy person, so I just removed this rule rather than use whitelist. 

Yesterday we got a vul report about sqli and WAF bypass, and it’s using double url-encode like the chardoubleencode.py sqlmap tamper script  https://github.com/sqlmapproject/sqlmap/blob/master/tamper/chardoubleencode.py

Actually I removed rule 1401 as it’s cause massive false positive too.

I think the ability to detect those evading tricks should be a core function of WAF rather than rely on rule set, what do you think?

**Comment by buixor** [comment]
Hi,

This has been an internal topic of discussion.
Double decoding everything might be an option, but I'm afraid it's only the begining of the slidding slope of "let's decode everything"... So far, we didn't notice *real* cases of legitimate double encoding usage, so I'm not yet convinced.

If you have some points in the favor of double-decoding everything, I'm open ;)

**Comment by buixor** [comment]
Please re-open if you have suggestions :)
