### ISSUE TITLE
Cookie values

### ISSUE THREAD

**Issue by jbm42** [nbs-system/naxsi#169]
Tried out Naxsi (survives under load - yay!),   but then fills the logs with lots of false positives (as expected).  

I can see how I'd put in whitelist rules for most of them.. except for the cookie related ones.  I can make them narrow by URL, but what about by the cookie variable itself?  For example, I may be happy with weird characters in GA tags, but not in another cookie value?

I sorta expected to see the cookie key/values decomposed into their own zone, like the url params.

I've probably misunderstood something!

**Comment by buixor** [comment]
Hi,

No, you didn't misunderstood, naxsi doesn't parse/decompose cookies yet :)
Might arrive in a future version !

**Comment by jonm-advfn** [comment]
OK cool.  Maybe I'll take a look at the code :)
