### ISSUE TITLE
The code style is unconsitent.

### ISSUE THREAD

**Issue by jvoisin** [nbs-system/naxsi#172]
What about using something like [uncrustify](http://uncrustify.sourceforge.net/) in a git-hook to impose a consistent coding-style?

**Comment by buixor** [comment]
what about : https://twitter.com/UdellGames/status/788690145822306304/photo/1

@jvoisin

**Comment by jvoisin** [comment]
Well, what about no?

**Comment by jvoisin** [comment]
[It seems]( https://www.cryptobells.com/exploring-naxsi-a-bit/ ) that we also have some naming issues:

> Beyond this, I find (admittedly pedantic) issues with small chunks of source (and I’m not the only one). Naxsi uses a mix of prefixes among strucs and functions; the use of ngx_http_ is particularly confusing, especially to new developers. This namespace pollution is wholly unnecessary. There are also a number of compile-time definitions that feel like they should be configurable (at least as an advanced option), including recursive JSON parsing depth and PCRE ovec sizes, and overall the codebase is littered with inconsistent style. It feels very much like an odd, organic blend of data-driven architecture and hard-coded logic branches based on rule definitions, making extension and development very difficult.

This should be addressed too :)
