### ISSUE TITLE
Blacklisting '@@'

### ISSUE THREAD

**Issue by jvoisin** [nbs-system/naxsi#176]
What about adding `@@` to the blacklist, since it can be used as an infoleak for [MsSQL]( https://msdn.microsoft.com/en-us/library/ms173823.aspx ) and MySQL.

**Comment by Cartogenic** [comment]
MainRule "str:@@" "msg:double @@" "mz:BODY|URL|ARGS|$HEADERS_VAR:Cookie" "s:$SQL:4" id:1017;

@@ --> +4 points

if you are using default ruleset then:
CheckRule "$SQL >= 8" BLOCK;

meaning @@ alone won't block but will make request more suspicious. If any other suspicious string like select|union|update|delete|insert|table|from|ascii|hex|unhex|drop (| = or),, (each of these strings adds up 4 points) is used in conjuction with @@, request is blocked. 

Very smart system! +1 developer, you rock!
In the end, it blocks malicious queries using @@.

**Comment by jvoisin** [comment]
This is why it [has been merged]( https://github.com/nbs-system/naxsi/commit/cb5271a29f155316d1b352d6666d6b67d2bcca4e ) :)
