### ISSUE TITLE
Double Encoding on $HEADERS_VAR:Cookie

### ISSUE THREAD

**Issue by ajrpayne** [nbs-system/naxsi#181]
From what I have been able to gather, NAXSI does not parse/decompose cookies yet. If that is the case, isn't Rule 1315 only checking for single encoding in the cookies?

MainRule "rx:%[2|3]."  "msg:double encoding !" "mz:ARGS|URL|BODY|$HEADERS_VAR:Cookie" "s:$XSS:8" id:1315;

**Comment by buixor** [comment]
Hi,

Yes, naxsi does not know how to properly parse cookies.
But the encoding rule might match anywhere, not only on cookies, it's meant to detect chained encoding that naxsi won't know how to handle.

**Comment by ajrpayne** [comment]
Hi,

Thanks for the quick response. I am still not clear on what is happening based on your reply though.
 
For example, lets say %38 is somewhere within a cookie value. Since cookies are not decoded before being checked won't %38 trip rule 1315 in the cookie even though it is only single encoded and not double encoded?

**Comment by buixor** [comment]
Hi,

I don't remember if the cookie is decoded by naxsi :p
But admitting it behaves as you suggest, then yes, rule 1315 will trigger over url-encoded stuff in cookies. Proper parsing of cookies would be cool indeed ;)

**Comment by buixor** [comment]
Hi,

sorry for delay, not much time to work on the project lately :)
After checking, cookies are not decoded, so 1315 will trigger on cookies, even if not double encoded (but at least simple encoded). However, after thinking about this, I believe it's not a serious issue, as most of the time, only ; and = are url-encoded.

If you feel this is still an issue, I'm open to discussion :)

**Comment by lizter** [comment]
I am currently experiencing an issue that I think is related to this. I use Naxsi in Nginx with a proxy pass to an Node Express app that store a session id in a cookie. The header starts like this: `set-cookie: connect.sid=s%3AiKf4eH...`

I am new to Naxsi, and I am not sure whether it would be safe to try to whitelist this cookie.

**Comment by buixor** [comment]
hello @lizter
In your case, I guess it is not big deal to white-list double encoding in cookies as it seems to be already present. This case is more here to back the eventuality of weird applications :)

**Comment by lizter** [comment]
Thank you for the reply. Do you have any tips on how I can do this? I tried to add `BasicRule wl:1315 "mz:HEADERS:cookie";`, but that gave me `nginx: [emerg] Naxsi-Config : Incorrect line BasicRule wl:1315 (../naxsi-0.54/naxsi_src//naxsi_skeleton.c/477)... in /etc/nginx/naxsi.rules:13`

**Comment by buixor** [comment]
please see wiki, esp https://github.com/nbs-system/naxsi/wiki/whitelists
