### ISSUE TITLE
Internal Rules => Documentation 

### ISSUE THREAD

**Issue by khaefeli** [nbs-system/naxsi#182]
Hi,

We've many false positives with the internal rule ID 2:
#@MainRule "msg:request too big, stored on disk and not parsed" id:2;

Always with fileuploads / larger POST requests (TYPO3)

Do you have any information about this and other internal rules?

Regards,
Kevin

**Comment by buixor** [comment]
Hi,

Yes : if the request's size exceed "client_body_buffer_size", it will be buffered to disk, and naxsi won't parse it (he doesn't know how to do it, and it might have a huge performance impact).
So, either you disable rule 2 for that specific URL (but naxsi won't see anything in BODY vars for that URL), or you increase the client_body_buffer_size to avoid that :)

See as well : https://github.com/nbs-system/naxsi/wiki/naxsilogs

**Comment by khaefeli** [comment]
cool, thanks!
