### ISSUE TITLE
"var name is mandatory" False Positive

### ISSUE THREAD

**Issue by harston** [nbs-system/naxsi#185]
jQuery #mulitplefileuploader uploadFile() when upload one file can send multiple Content-Disposition with blank 'name' and 'undefined' data:
POST /upload.php HTTP/1.1
Host: my.host
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:37.0) Gecko/20100101 Firefox/37.0
Accept: */*
Accept-Language: en-US,en;q=0.7,pl;q=0.3
Accept-Encoding: gzip, deflate
X-Requested-With: XMLHttpRequest
Referer: http://my.host/test.php
Content-Length: 1319
Content-Type: multipart/form-data; boundary=---------------------------14728869977677596101654014094
Cookie: smuuid=1478139b887-32937c104684-33032d5b-1a6795a5-66de5703-dd8bed4f0cbe; _ga=GA1.2.237723093.1415273622; __utma=34417080.237723093.1415273622.1417609407.1417609407.1; __utmz=34417080.1417609407.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache

-----------------------------14728869977677596101654014094
Content-Disposition: form-data; name="myfile"; filename="image.png"
Content-Type: image/png

.PNG
.
....IHDR......
/* image body */
-----------------------------14728869977677596101654014094
Content-Disposition: form-data; name=""

undefined
-----------------------------14728869977677596101654014094
Content-Disposition: form-data; name=""

undefined
-----------------------------14728869977677596101654014094--

I've noticed same situation in Joomla (POST /administrator/index.php?option=com_joomgallery&controller=jupload&task=upload) but haven't time to test it.

It looks that in naxsi_src/naxsi_runtime.c
   /* var name is mandatory */
     if (!varn_start || !varn_end || varn_end <= varn_start) {
       ngx_http_apply_rulematch_v_n(&nx_int__uncommon_post_format, ctx, r, NULL, NULL, BODY, 1, 0);
       dummy_error_fatal(ctx, r, "POST data : no 'name' in POST var");
       return ;
     }

**Comment by buixor** [comment]
Hi,

Thanks for the feedback :)
The internal rule itself is not a feedback, however - as you say - it might happen in a legit way, I will look at a way to fix this, so that it can be disabled for legitimate purposes, but still match if no whitelists were applied !

**Comment by buixor** [comment]
I guess we should simply remove the dummy_error_fatal() call, it will allow to whitelist this.

**Comment by buixor** [comment]
Hi,

It should be fixed with last commit.
Can you test on master branch, and re-open if it doesn't fit your needs ?
You should now be able to Whitelist the specific internal ID.
