### ISSUE TITLE
IE11 => invalid POST format

### ISSUE THREAD

**Issue by khaefeli** [nbs-system/naxsi#187]
Hi,

We're running into 403 blocks with the internal rule ID 13 and Internet Explorer 11.
The request is submitted from a normal contact form. (TYPO3 Powermail)
Same content with FF & Chrome works - only IE11 requests are blocked.

I've enabled the naxsi_extensive_log to get more information about it:

    2015/04/15 10:39:10 [error] 28499#0: *100519 NAXSI_EXLOG: ip=2a04:502:1001:110:f9ed:5291:1ad:a0d8&server=www.example.ch&uri=/buecher-und-fachartikel/pm-fachbuch/bestellformular/&id=13&zone=BODY&var_name=&content=, client: 2a04:502:1001:110:f9ed:5291:1ad:a0d8, server: www.example.ch, request: "POST /buecher-und-fachartikel/pm-fachbuch/bestellformular/?tx_powermail_pi1%5Baction%5D=create&tx_powermail_pi1%5Bcontroller%5D=Form&cHash=2f55d5b40450bc464cd0a2c1766afd48 HTTP/1.1", host: "www.example.ch", referrer: "https://www.example.ch/buecher-und-fachartikel/pm-fachbuch/bestellformular/"

    2015/04/15 10:39:10 [error] 28499#0: *100519 NAXSI_FMT: ip=2a04:502:1001:110:f9ed:5291:1ad:a0d8&server=www.example.ch&uri=/buecher-und-fachartikel/pm-fachbuch/bestellformular/&learning=0&vers=0.53-1&total_processed=57&total_blocked=18&block=1&zone0=BODY&id0=13&var_name0=, client: 2a04:502:1001:110:f9ed:5291:1ad:a0d8, server: www.example.ch, request: "POST /buecher-und-fachartikel/pm-fachbuch/bestellformular/?tx_powermail_pi1%5Baction%5D=create&tx_powermail_pi1%5Bcontroller%5D=Form&cHash=2f55d5b40450bc464cd0a2c1766afd48 HTTP/1.1", host: "www.example.ch", referrer: "https://www.example.ch/buecher-und-fachartikel/pm-fachbuch/bestellformular/"

I've also activated the nginx log for POST request and compared the logs:
http://pastebin.com/Zh2RMejX

so here are my questions:
 * did somebody also notice this errors with IE11?
 * how do you recommend to debug it? 
 * how does RuleID 13 validates the POST requests?

Cheers

**Comment by buixor** [comment]
Hi,

I never encountered specific errors with IE11 + naxsi, but I'm not a windows user, so I can't really try :(
id:13 is an internal rule for "uncommon post format", which is a bit vague, so possible cases are :
 - bad content disposition
 - missing boundary line
 - impossible to parse content-disposition field
 - lack of var_name in the post
 
However, naxsi should log something when this happens (as long as you setup the log to debug in nginx) saying a bit more about this. Can you post those logs ?


cheers,

**Comment by khaefeli** [comment]
Hi buixor,

first: thank you again for the fast answer.
I also don't use windows, so I've to ask some colleagues :-) Anyway:

I don't see any boundery line in my IE11 post (see pastbin). 
but I'll recheck the error.log with log level debug. 

cheers

**Comment by buixor** [comment]
Hi,

Sorry for the delay in my answer, picking back on issues !

So regarding your issue, I guess it's a browser problem, as you mentioned it does not happen with other browsers. When naxsi is not blocking the request, does the application behave as expected ? Because either naxsi miserably fails at parsing your request, or the browser is doing wrong (in the latest case, I don't know how application would behave without a name in the POST variable, but my guess is "not").

You should be able to whitelist ID:11 to fix the issue, but it might (will probably) create a partial bypass in the WAF.

If you are able to transmit me a full body (including \r\n) it will allow me to get a better understand, and know if we will just blame IE11 for being a crappy browser, or actually sort some real issue in naxsi :)


Cheers,

**Comment by khaefeli** [comment]
Hi!

The application works well when we put naxsi in the learning mode. 

At the moment I dont see any logs anymore regarding this issue. Also my IE11 test ist OK.
Maybe it was an IE bug, which is fixed now.

You can close this issue - I'll keep an eye on it and come back to you if we see this strange behaviour again. (with some full body logs..)

Thanks!

**Comment by buixor** [comment]
cool,

cheers,

**Comment by khaefeli** [comment]
Hi,

OK, now we got it. 

The issue is related to IE11 and the fact that IE11 submit the form with the submit button part. (even if the name is empty)
 See:

     Content-Disposition: form-data; name=\x22\x22\x0D\x0A\x0D\x0Asenden\x0D\x0A-----------------------------7df379324004a\x0D\x0A

request body for that was:

    -----------------------------7df2a3322007a
    Content-Disposition: form-data; name=""
    
    senden
    -----------------------------7df2a3322007a

The installed TYPO3 extension (powermail) added a submit button with an empty name=""

chrome, firefox and other browser simply submit the post without the "submit" part. 
so the post is valid. IE11 doesn't.

so we fixed it with adding something like:

    <input type="submit" name="thankyouIE11" value="Senden">

cheers
