### ISSUE TITLE
Allow NAXSI to examine file upload contents

### ISSUE THREAD

**Issue by hugochinchilla** [nbs-system/naxsi#188]
It would be usefull to protect against php shells for example, or file uploaders. Just checking for `<?php`, `eval(`, `mail(`, `move_uploaded_file(` would be enought to protect most of php sites from 99% of the automated attacks.

**Comment by buixor** [comment]
Hi,

So far, you can only check file extensions / file names of uploaded files.
We did not plan to integrate file content parsing, as it is a huge field, and we feel like it's more of an AV job, plus obfuscation might make it too easy to bypass :(
