### ISSUE TITLE
"malformed content-disposition line" False Positive

### ISSUE THREAD

**Issue by harston** [nbs-system/naxsi#189]
In https://github.com/nbs-system/naxsi/issues/185 i was writing about FP i Joomla. Currently i have reproduced it in JoomGallery module in "Java Upload" where is problem with "malformed content-disposition line" filter and dummy_error_fatal() in it.

    /* 
    ** now idx point to the end of the 
    ** content-disposition: form-data; filename="" name=""
    */
    idx += (u_char *)line_end - (src+idx) + 1;
    if (src[idx] != '\r' || src[idx+1] != '\n') {
      ngx_http_apply_rulematch_v_n(&nx_int__uncommon_post_format, ctx, r, NULL, NULL, BODY, 1, 0);
      dummy_error_fatal(ctx, r, "POST data : malformed content-disposition line");
      return ;
    }

It should be possible to disable/whitelist this filter.

2015/04/16 13:48:39 [debug] 7972#0: *9 XX-******** NGINX NAXSI INTERNAL ERROR ********
2015/04/16 13:48:39 [debug] 7972#0: *9 POST data : malformed content-disposition line
2015/04/16 13:48:39 [debug] 7972#0: *9 XX-func:ngx_http_dummy_multipart_parse file://../nginx/src/naxsi-1803ef69853f0af9b91387b1298f722b2e477850/naxsi_src/naxsi_runtime.c line:1733
2015/04/16 13:48:39 [debug] 7972#0: *9 XX-uri:/administrator/index.php?option=com_joomgallery&controller=jupload&task=upload HTTP/1.1
Host
2015/04/16 13:48:39 [error] 7972#0: *9 NAXSI_FMT: ip=0.0.0.0&server=joomla.mielecin24.info&uri=/administrator/index.php&learning=0&vers=0.53-1&total_processed=5&total_blocked=1&block=1, client: 0.0.0.0, server: , request: "POST /administrator/index.php?option=com_joomgallery&controller=jupload&task=upload HTTP/1.1", host: "my.host"

**Comment by buixor** [comment]
Hi,

I pushed a fix upstream for this.
Now most of the calls to the "killer macro" (dummy_error_fatal) are in if(ngx_http_apply_rulematch_v_n()) { } blocks.
This should allow you to effectively whitelist those internal rules.

**Comment by buixor** [comment]
Just re-open if the fix didn't work :)
