### ISSUE TITLE
Whitelisting using nxtools.py

### ISSUE THREAD

**Issue by Cartogenic** [nbs-system/naxsi#191]
Can't understand how to use the new nxtool for whitelisting... hard to understand wiki, not much info there about whitelisting (only using nx_util.py, which is deprecated.)
what is elasticsearch database and how to setup naxsi with it?

**Comment by gradew** [comment]
Hi Cartogenic,

I did have trouble as well ;-)
Here's what I do to generate whitelists; bear in mind that nx_util is deprecated. You will need to use nxapi.py now:

- set up ES (Elasticsearch) and create an index called nxapi.
- alter nxapi.json to make it point to your ES instance (IP or FQDN)
- once you've generated enough error logs with nginx, run:  nxtool.py -c nxapi.json --file=/var/log/nginx/error.log (or whatever your error log file(s) is/are); this will feed all the NAXSI_FMT data into ES
- BasicRule statements can then be generated using the following: nxtool.py -c nxapi.json -f --slack

Elasticsearch is basically a search engine that you can query/build using JSON.
Setting it up is rather easy and fairly well explained on the offical website. You may want to also install "head", which is an Elasticsearch plugin that will give you some sort of GUI that you can use for basic operations (such as creating indexes).

ES is beyond the scope of this thread, but if you're having trouble setting it up, I'd be glad to help :)

**Comment by m0l1n** [comment]
You really have to install an ES cluster just to use the nxtool.py ? 

Can't we just use the tool on the naxsi log the way nx_util did it ?

**Comment by buixor** [comment]
Hi,

Yes, nxtool requires ES.
It might sound annoying, but sqlite/mysql DB backend was too troublesome
for us to be able to procude decent learning.
We do not have plans for other DBs back-ends so far.

**Comment by m0l1n** [comment]
Yes, it just sound quite heavy to me  :
-"Hey can I whitelist with naxsi?"
-"Yeah you just need an ES cluster"

But well it's a solution, but in that mind it would be great if you could
make some documentation about it, or at least a redirecting link to
ElasticSearch page ;)

I mean whitelist is what make naxsi nice to use !

2015-06-11 14:32 GMT+02:00 buixor <notifications@github.com>:

> Hi,
>
> Yes, nxtool requires ES.
> It might sound annoying, but sqlite/mysql DB backend was too troublesome
> for us to be able to procude decent learning.
> We do not have plans for other DBs back-ends so far.
>
>
> On Thu, Jun 11, 2015 at 12:11 PM, m0l1n <notifications@github.com> wrote:
>
> > You really have to install an ES cluster just to use the nxtool.py ?
> >
> > Can't we just use the tool on the naxsi log the way nx_util did it ?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/nbs-system/naxsi/issues/191#issuecomment-111076640>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nbs-system/naxsi/issues/191#issuecomment-111116362>.
>



-- 
Cordialement,
MOLLARD Quentin,
Etudiant en Master Informatique,
à l'IM2AG , Université Joseph Fourier .

**Comment by buixor** [comment]
"Cluster" is a big word for a software you can launch standalone !
But yeah, I do understand the strugle, however - it takes what it takes :)

Noted for the ElasticSearch suggestion in the documentation.
If you already have feedback or suggestions, they are welcome

ps: the wiki is open for editing by anyone !

**Comment by m0l1n** [comment]
I don't have much time for now, but in 2-3 weeks I will work on ES and
naxpi to make thing work, will comment everything I do and try to put some
documentation to guide user through it :)

2015-06-11 15:06 GMT+02:00 buixor <notifications@github.com>:

> "Cluster" is a big word for a software you can launch standalone !
> But yeah, I do understand the strugle, however - it takes what it takes :)
>
> Noted for the ElasticSearch suggestion in the documentation.
> If you already have feedback or suggestions, they are welcome
>
> ps: the wiki is open for editing by anyone !
>
>
> On Thu, Jun 11, 2015 at 2:36 PM, m0l1n <notifications@github.com> wrote:
>
> > Yes, it just sound quite heavy to me :
> > -"Hey can I whitelist with naxsi?"
> > -"Yeah you just need an ES cluster"
> >
> > But well it's a solution, but in that mind it would be great if you could
> > make some documentation about it, or at least a redirecting link to
> > ElasticSearch page ;)
> >
> > I mean whitelist is what make naxsi nice to use !
> >
> >
> > 2015-06-11 14:32 GMT+02:00 buixor <notifications@github.com>:
> >
> > > Hi,
> > >
> > > Yes, nxtool requires ES.
> > > It might sound annoying, but sqlite/mysql DB backend was too
> troublesome
> > > for us to be able to procude decent learning.
> > > We do not have plans for other DBs back-ends so far.
> > >
> > >
> > > On Thu, Jun 11, 2015 at 12:11 PM, m0l1n <notifications@github.com>
> > wrote:
> > >
> > > > You really have to install an ES cluster just to use the nxtool.py ?
> > > >
> > > > Can't we just use the tool on the naxsi log the way nx_util did it ?
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> https://github.com/nbs-system/naxsi/issues/191#issuecomment-111076640
> > >.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/nbs-system/naxsi/issues/191#issuecomment-111116362
> >.
> > >
> >
> >
> >
> > --
> > Cordialement,
> > MOLLARD Quentin,
> > Etudiant en Master Informatique,
> > à l'IM2AG , Université Joseph Fourier .
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/nbs-system/naxsi/issues/191#issuecomment-111117409>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nbs-system/naxsi/issues/191#issuecomment-111125799>.
>



-- 
Cordialement,
MOLLARD Quentin,
Etudiant en Master Informatique,
à l'IM2AG , Université Joseph Fourier .

**Comment by buixor** [comment]
Awesome, thank you :)
Don't hesitate to drop by on irc if you need any help!

**Comment by Cartogenic** [comment]
Thank you for all your help =)
Sorry for the very late response, I rarely check my mail, and got around the problem using the old white list tool.

**Comment by buixor** [comment]
You're welcome.
Don't use nx_util, it's evil and will do bad things to you :)

**Comment by Cartogenic** [comment]
Noted =) Thanks once again for all your help!
