### ISSUE TITLE
support in debian jessie

### ISSUE THREAD

**Issue by myworking82** [nbs-system/naxsi#192]
Hi. Can you tell me, will naxsi be present in debian jessie as deb packege or like exten for nginx????

**Comment by buixor** [comment]
Hi,

unfortunately, it seems debian developpers didn't chose to continue to package naxsi in jessie ...
some people in the community are thinking about building and publishing packages, so stay tuned :)

**Comment by dschallert** [comment]
Hi there, 

a year passed by.. Any updates on debian jessie + naxsi?

Thanks

**Comment by jvoisin** [comment]
I works here, but you have to compile it yourself. Feel free to ask the Debian people to package it for you, or even better, package it, and try to push it upstream.

**Comment by dschallert** [comment]
Yep, compiled it myself aswell a dozen times. Just wondering why the debian guys kicked the package with jessie.
