### ISSUE TITLE
nxtool does not handle inline comments in tagging process

### ISSUE THREAD

**Issue by alefauch** [nbs-system/naxsi#194]
My whitelist file is like 

# HEADERS_VAR
BasicRule  wl:1005 "mz:$HEADERS_VAR:cookie";	#Rule (1005) mysql keyword (|)
BasicRule  wl:1011 "mz:$HEADERS_VAR:cookie";	#Rule (1011) parenthesis, probable sql/xss
BasicRule  wl:1010 "mz:$HEADERS_VAR:cookie";	#Rule (1010) parenthesis, probable sql/xss
BasicRule wl:1315 "mz:$HEADERS_VAR:cookie";		#Rule (1315) % double encoding

When you run nxtool with this whitelist for tagging the process fails.
The same process works fine if the lines are like:

# HEADERS_VAR
BasicRule  wl:1005 "mz:$HEADERS_VAR:cookie";
BasicRule  wl:1011 "mz:$HEADERS_VAR:cookie";
BasicRule  wl:1010 "mz:$HEADERS_VAR:cookie";
BasicRule wl:1315 "mz:$HEADERS_VAR:cookie";

nxtool should be able to handle inline comments because this is a valid syntax for nginx.

**Comment by buixor** [comment]
Thanks for the report, we are going to fix that and ping you :)

**Comment by buixor** [comment]
Hi antonin,

this should be fixed now : https://github.com/nbs-system/naxsi/commit/2ba5f82ad470fb2ca0ddb09b4b06668ed8ed9fe5
