### ISSUE TITLE
naxsi rule can't filter character “char” ?

### ISSUE THREAD

**Issue by ihacku** [nbs-system/naxsi#198]
I want to add a rule like this
MainRule "str:char" "msg:sql keywords" "mz:BODY|URL|ARGS" "s:$SQL:3" id:1024

I want filter payload like this %20(1=CHAR(106)%2bCHAR(106)%2bCHAR(106))%20--

reload nginx and this will lead to an error
nginx: [emerg] Naxsi-Config : Incorrect line MainRule str:char (/path/naxsi/naxsi_src/naxsi_skeleton.c/860)... in /usr/local/nginx/naxsi/naxsi_config/naxsi_core.rules:44

why is this?

**Comment by buixor** [comment]
Did you add the ; at the end of the line ?

**Comment by ihacku** [comment]
Ahh, I'm so noob, sorry.
