### ISSUE TITLE
Signed Commits/Releases

### ISSUE THREAD

**Issue by quantumpacket** [nbs-system/naxsi#201]
After checking out https://github.com/nbs-system/naxsi/wiki/installation I see nowhere that the downloaded source is being verified for neither Nginx or NAXSI.

With Nginx source you can do the following:

``` shell
wget http://nginx.org/download/nginx-N.N.N.tar.gz
wget http://nginx.org/download/nginx-N.N.N.tar.gz.asc
gpg -v --openpgp --verify ./nginx-N.N.N.tar.gz.asc ./nginx-N.N.N.tar.gz
```

This should probably be what is used in the documentation instead.

Now when it comes to using git a similar check can be done like so on tagged releases:

``` shell
git init
git clone https://github.com/nbs-system/naxsi.git
git tag -v TAG_NAME
```

There is another git option for verifying commits as well.

Do you currently sign commits/releases? If so, what is the public key? If not, do you plan on doing so? I think as a security based software it would make sense to do so. Also, Nginx already signs their source, so it would be pointless to verify it and then add an unverified source.

References:
- http://mikegerwitz.com/papers/git-horror-story
- https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work
- https://ariejan.net/2014/06/04/gpg-sign-your-git-commits/
- http://nginx.org/en/download.html

Thoughts?

**Comment by buixor** [comment]
Hi,

That's actually a very good point, and there is no reason not to do so :)
In the past, most people tend to use packages from official repositories, but it seems a good thing to do.

Thanks for the suggestion,

**Comment by quantumpacket** [comment]
True, most people do get it from a repo, but for those who want to compile Nginx+NAXSI we definitely could use a way to verify it.

Since NAXSI source is currently not being signed, how are the package maintainers for the repos verifying the source integrity before compiling?

I'm currently not allowed to use NAXSI source per policy, because it's not signed. But if I get the package from the repo which is signed by the package maintainer (in this case Ubuntu) I am allowed to use it. Which doesn't seem secure if it's not being signed upstream.

Regardless of IT sec policies, the paranoid side of me :eyes:  says it would be a great way for the NSA :shipit: to compromise source code and backdoor a production server.

**Comment by buixor** [comment]
It's easy, I sign my code with "signed by bui" so that people know it's me :)
More seriously, I'm going to try give it a try today, so stay tuned !

**Comment by buixor** [comment]
https://github.com/nbs-system/naxsi/releases/tag/0.54rc3
Does it looks good ? :)

**Comment by quantumpacket** [comment]
```
$ git tag -v 0.54rc3
object e3e1ac843c049c116d600be3f79a560cd553efb3
type commit
tag 0.54rc3
tagger bui <bui@nbs-system.com> 1433504103 +0200

0.54rc3, signed
gpg: Signature made Fri 05 Jun 2015 07:35:03 AM EDT using RSA key ID 2685AED4
gpg: Good signature from "Naxsi Project (Key Used To Sign Code) <tko@nbs-system.com>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 5FA3 5473 CA73 872A A973  1F5C 251A 28DE 2685 AED4
```
:+1:  Thanks!

**Comment by quantumpacket** [comment]
I updated https://github.com/nbs-system/naxsi/wiki/installation but it could use a 2nd pair of eyes to make sure I typed it all up correctly. Thanks for this awesome module!

**Comment by quantumpacket** [comment]
I just tried to compile the latest release and my compile script failed due to the signature files no longer being archived as they were before. So either the docs need to be updated as they expect the file to be `tar.gz.asc`, or the previous file format used.

But the more important thing is I am getting a wrong signature for the current release:

> gpg: armor header: Version: GnuPG v1
gpg: Signature made Tue 29 Sep 2015 08:41:13 AM EDT using RSA key ID 2685AED4
gpg: using PGP trust model
gpg: BAD signature from "Naxsi Project (Key Used To Sign Code) <tko@nbs-system.com>"
gpg: binary signature, digest algorithm SHA1

Can you verify on your end this is the case using the current release archive and signature?

Also, you should be using SHA2 and not SHA1 as Nginx is doing so, as it's no longer considered secure. You can check out [this](https://nixaid.com/gpg-migration-sha1-to-sha2/) for instructions for migrating your keys to SHA2.

**Comment by quantumpacket** [comment]
@buixor It's been a week was wondering if anybody had the chance to verify the signature mismatch. If this requires a new issue to be opened let me know. I figured it best fit in this already on-topic one. Thanks.

Something like this should be addressed as soon as possible as it could indicate either a tampered with source archive, or a corrupted one. Neither of which should be available for people to download and use.

**Comment by buixor** [comment]
Hi,

Sorry for delay, missed this one :)
I'm going to update the current release for consistent filename, and I'll
change digest in close future :)

**Comment by quantumpacket** [comment]
Thanks! Any news on the bad signature for the current release?

**Comment by buixor** [comment]
Ah, I didn't see that signature was bad!

Going to (try to) fix it today :)

>

**Comment by quantumpacket** [comment]
@buixor 

Is there a reason why the [source verification](https://github.com/nbs-system/naxsi/wiki/olds-installation#installation-from-source) section was removed from the [new wiki page](https://github.com/nbs-system/naxsi/wiki/naxsi-compil#compilation)? I was going to go update the key retrieval to use full keys to prevent key collisions and saw it was removed. Also, any update on when you'll change to SHA-2 as mentioned [here](https://github.com/nbs-system/naxsi/issues/201#issuecomment-146473218)?

**Comment by buixor** [comment]
Hello !

This is indeed a mistake, a "someone" from the community was supposed to make this page from the wiki, but it didn't happen :(

(Hope you see the effort on the wiki still)

I'm going to do it as soon as I have some time, this was unintentional !

**Comment by quantumpacket** [comment]
Closing as Wiki has been updated https://github.com/nbs-system/naxsi/wiki/naxsi-compile :+1:
