### ISSUE TITLE
nxtool whitelist attempt causes TypeError encode takes no keyword arguments error

### ISSUE THREAD

**Issue by cFINNY** [nbs-system/naxsi#206]
Hey guys,
While attempting to use nxtool for the first time after setting it up/etc and importing all the logs, we tried to generate a whitelist for a specific uri exactly as shown in the wiki however am getting an exception/error, can't seem to find any way around it? Any ideas? Thanks

nxtool.py -s www.ourdomain.com -f --filter 'uri /overrides/ajax/updateBanner/' --slack                                                                                                                                 
```
# size :1000
#  template :/usr/local/nxapi/tpl/APPS/google_analytics-ARGS.tpl 
Nb of hits :0
#  template :/usr/local/nxapi/tpl/URI/site-wide-id.tpl 
Nb of hits :87595
#  template matched, generating all rules.
1 whitelists ...
#Rule (1000) sql keywords
#total hits 87595
Traceback (most recent call last):
  File "/usr/bin/nxtool.py", line 141, in <module>
    translate.full_auto()
  File "/usr/lib/python2.6/site-packages/nxapi/nxtransform.py", line 227, in full_auto
    self.fancy_display(genrule, results, template)
  File "/usr/lib/python2.6/site-packages/nxapi/nxtransform.py", line 246, in fancy_display
    print "#"+x+" : "+unicode(y).encode("utf-8", errors='replace')
TypeError: encode() takes no keyword arguments
```

**Comment by buixor** [comment]
Hi,

Seems you step a foot in the fantastic word of encoding handling and python.
It is probably because you have some weird stuff in either the content of the whitelist, it might be the content itself (displayed if you have extensive_log). If you can transmit me a sample, I can fix the encoding issue :) If you don't want to post it on the bugtracker, mail it to me : bui@memze.ro

cheers,

**Comment by blotus** [comment]
Hi,

Can you  try again with the latest commit ? I removed the keyword argument as it seems that you use python 2.6 which does not support keyword arguments for encode().

**Comment by cFINNY** [comment]
Hi guys, thank you for the quick replies and work! I'll give it a shot pretty soon here with the latest commit and let you guys know if that resolved it otherwise will send some samples for further investigation, gotta love python encoding haha.

**Comment by cFINNY** [comment]
Hey guys,
Looks like that resolved the issue!:) Thanks to you both for all your great work on naxsi, and thanks for getting this figured so quickly!
