### ISSUE TITLE
Whitelisting Regex

### ISSUE THREAD

**Issue by khaefeli** [nbs-system/naxsi#208]
Hi,

I tried to whitelist some POST variables with the following regex:

    BasicRule wl:1310,1311 "mz:$URL_X:(.*)/checkout/(.*)|$BODY_VAR_X:^(billing|giftmessage|payment|shipping|street|options)$|NAME";

the error log says:

    Naxsi-Config : Incorrect line BasicRule wl:1310,1311

If I change it to: 

     BasicRule wl:1310,1311 "mz:$URL_X:(.*)/checkout/(.*)|$BODY_VAR_X:^billing|NAME";

is it working well. I'm not sure if my regex is wrong or are there some limitations?

Cheers,
Kevin

**Comment by buixor** [comment]
Hi,

Sorry to say so, but there is a bug, which disallows you to use | in regular expressions, as it's used as a separator between elements of the matchzone.
We don't know how to fix it yet without doing terrible things that will give us nightmares :(

**Comment by khaefeli** [comment]
no worries! we can repeat the rules - that should be a real problem (but it would be nicer with such a regex) maybe the WL regex wiki section should be updated to "warn" other people

**Comment by quantumpacket** [comment]
Is there no way to allow escaping of the separator?

```conf
BasicRule wl:1310,1311 "mz:$URL_X:(.*)/checkout/(.*)|$BODY_VAR_X:^(billing\|giftmessage\|payment\|shipping\|street\|options)$|NAME";
```
Not sure how Nginx handles backslashes in config files, but it might require double escaping so Nginx sees it as a literal backslash.

**Comment by buixor** [comment]
Unfortunately, I don't think it is possible, one of the reasons being that regex allow you to escape |, so you would end up in an endless escaping sequence (is it a real pipe, an escaped one, or is it an escaped pipe prefixed by escaped backslash ? etc.)

If someone has an idea, I'm open, but so far I don't see any viable one :)

**Comment by khaefeli** [comment]
tricky one :-)

but escaping for example [ is working?

    BasicRule wl:1310,1311 "mz:$BODY_VAR_X:^tx_(.*)\[(.*)|NAME";

**Comment by buixor** [comment]
yes it is, because [ is not used by naxsi itself as a special character. Don't misunderstand me, it's not nginx's nor pcre's fault, but really a poor design decision on my side :) (at a time where I didn't even plan to support regex in match zones).

**Comment by quantumpacket** [comment]
One last suggestion, I'm probably wrong anyways.

Can we not use a comma as the matchzone separator instead of a pipe? The score section already uses commas as its separator. I see a conflict with a comma being much less likely as it has no special meaning in PCRE, and it's not going to be as useful as allowing the use of a pipe in a regex.

**Comment by buixor** [comment]
Hi,

> Can we not use a comma as the matchzone separator instead of a pipe?
Sorry but no :D for the sake of backward comptability (can you see
forthcoming drama, breaking all ever written whitelists or signatures ?),
and not replacing an unsolvable problem by an equally unsolvable problem, I
must refute this idea with vigor :)


> comma being much less likely as it has no special meaning in PCRE,
Actually, it's used for repetitions etc. so it will create other problems,
ie. a{3,}


Sorry, but for now seems we'll have to live with this !
