### ISSUE TITLE
block by request method

### ISSUE THREAD

**Issue by myworking82** [nbs-system/naxsi#211]
Hi. I try create MainRule for block by request method and do this:
MainRule "str:HEAD" "msg:DDOS block (HEAD request)" "mz:$HEADERS_VAR_X:^Request\sMethod$" "s:$DDOS:1" id:5001;
but HEAD request do not blocked, can you help me???

**Comment by buixor** [comment]
Hi,

naxsi does not support creating rules on the request method so far, sorry.
