### ISSUE TITLE
there is something wrong with install document:  Import Source Signing Keys

### ISSUE THREAD

**Issue by benborba** [nbs-system/naxsi#213]
page: https://github.com/nbs-system/naxsi/wiki/installation
section: Import Source Signing Keys

release package from nginx.org signed by A1C052F8 but not 7BD9BF62
I test version 1.9.3 and 1.8.0, both of them signed by A1C052F8

**Comment by buixor** [comment]
Hi, seems that there is a confusion on nginx's site, as the key available at http://nginx.org/keys/nginx_signing.key is still 7BD9BF62. I'm going to add both !
