### ISSUE TITLE
Whitlisting ratio explanation

### ISSUE THREAD

**Issue by denmaddog** [nbs-system/naxsi#214]
Hello,

I am having naxsi in learning mode populating nginx error log fo quite some time, and then I've populated elasticsearch db with those entries, but when I want to generate whitelists, I get just this as output:
nxtool.py -c /root/naxsi_latest/nxapi/nxapi.json -f --slack
# size :1000
Also when I do nxtool.py -c /root/naxsi_latest/nxapi/nxapi.json -x --colors I get:
# size :1000
# Whitelist(ing) ratio :
# false 100.0 % (total:30562380/30562380)
.
.
.

What does it mean false 100.0%? Does it mean that no request was detected as positive by naxsi?

Thanks,

Zeljko

**Comment by buixor** [comment]
Hi,

It means that none of the events stored into the ES database have been tagged yet.
tagging is manually performed with nxtool, when you use the --tag options and provide whitelists.

See: 
https://github.com/nbs-system/naxsi/tree/master/nxapi#3-tagging-events
