### ISSUE TITLE
Seperate logfile confusion ?

### ISSUE THREAD

**Issue by Keithsc** [nbs-system/naxsi#215]
Hi, Is it possible to get naxsi to log to it's own log file instead of the nginx error_log ?

I've used the latest source for nginx (1.8.0) along with the master.zip file of naxsi but can't figure out what the config line option should be or where it should go.. in nginx.conf or my naxsi_settings.conf.

I've been trying things like the lines below but keep getting unknown directive.

nasxi_log /var/log/nginx/naxsi_log;
naxsi_logformat /var/log/nginx/naxsi_log;

**Comment by blotus** [comment]
Hi,

This option is no longer present. It was briefly available only in the repo (no release), but we discovered a few bugs in it, allowing to crash the nginx child. We chose to remove the feature for the time being, as it is not really important (and you can emulate this using syslog for example, by making nginx log to syslog, and configuring syslog to send the logs to differents files based on the log line).

**Comment by Keithsc** [comment]
Hi,

Thanks for the quick reply. I was trying to get syslog to work earlier today but was having issues so decided to just use log files instead. I will raise a separate issue about the syslog problems I was having. Thanks Keith.
________________________________________
