### ISSUE TITLE
nxtool.py --syslog not working as expected

### ISSUE THREAD

**Issue by Keithsc** [nbs-system/naxsi#216]
Hi, If I run nxtool.py --syslog then I get the following but nothing get logged....

[root@syslog conf.d]# nxtool.py --syslog
# size :1000
WARNING:root:Reading from syslog socket
Listening for syslog incoming 192.168.yy.yy port 10514

If i run tcpdump I can see there is traffic...
14:26:44.029485 IP 192.168.xx.xx.49460 > 192.168.yy.yy.10514: UDP, length 654

Is there a facility or severity that I need to set on nginx for this to work ?  or is there a simple mod / print line I could add to nxtool.py to let me see what it's receiving ?

Thanks
Keith

**Comment by buixor** [comment]
I'm attempting to summon @guiguiabloc for intel here :)

**Comment by guiguiabloc** [comment]
:)
Works fine in tcp mode :

syslog.conf:
filter f_naxsi { match("NAXSI_FMT" value("MESSAGE")); };
source mywebsite {
file("/var/log/nginx/logs/mywebsite-error.log" flags(no-parse));
};
destination nxtool {
        tcp("10.1.2.3" port(51401) template("$MSG\n"));
};
log { source(mywebsite); filter(f_naxsi); destination(nxtool); };
nxapi.json
},
"syslogd": {
 "host" : "0.0.0.0",
 "port" : "51401"
},

python nxtool.py -c nxapi.json --syslog 


Could you try it ?

**Comment by buixor** [comment]
Hi @Keithsc,

is @guiguiabloc explenation fine for you ?
if it's not a bug, please close issue :)

**Comment by Keithsc** [comment]
Thanks for the reply. I have a working solution in place just now using logstash to collect the logs on a central server, that then writes them to disk from where I run nxtool.  When I get the change I will have another shot at getting nxtool to work with syslog.
Thanks
keith
