### ISSUE TITLE
Segfault with incorrect rules

### ISSUE THREAD

**Issue by blotus** [nbs-system/naxsi#217]
Naxsi segfaults in some cases with incorrect rules that are not detected while parsing the configuration, for example : 
 - BasicRule wl:1101 "mz:$URL_X:^/\d+$|$ARGS_VAR_X:^a$|$ARGS_VAR_X:^b$

(gdb) c
Continuing.

Program received signal SIGSEGV, Segmentation fault.
ngx_http_dummy_pcre_wrapper (rx=0x0, str=0x7f8df74d94b8 "a=https://asd&b=https://foo", len=1)
    at /home/sblot/git/naxsi/naxsi_src//naxsi_runtime.c:390
390	  match = pcre_exec(rx->regex->code, 0, (const char *) str, len, 0, 0, captures, 1);
(gdb) p str
$1 = (unsigned char *) 0x7f8df74d94b8 "a=https://asd&b=https://foo"
(gdb) p *rx
Cannot access memory at address 0x0

**Comment by buixor** [comment]
https://github.com/nbs-system/naxsi/commit/f406d7f5cc7531383b00490c6219d9e7f74eed16

should be fixed. naxsi will scream if it sees some inconsistent WL.
