### ISSUE TITLE
txtool.py does not generate any whitelist rule

### ISSUE THREAD

**Issue by 123BLiN** [nbs-system/naxsi#219]
Hello, thank you very much for this awesome project!
I used old nx_util.py script for a while but now trying to setup new nxapi utility.
I have pretty full ES database, and can see stats with nxtool.py -x
however when I try to generate whitelists with nxtool.py -f --slack I just get blank list.
```bash
root@t-nlb-d:~# nxtool.py -f --slack
# size :1000
root@t-nlb-d:~#
```
I have the last version of nxapi on ubuntu 14.04. Can someone help to troubleshoot this issue?

**Comment by buixor** [comment]
Hi,

Can you show the stats you have with "-x" option ?
As well, you should add "-s fqdn.com" to generate the rules.

**Comment by 123BLiN** [comment]
Hi! I have next stats (real data removed):
```bash
root@t-nlb-d:~# nxtool.py -x
# size :1000
# Whitelist(ing) ratio :
# false 100.0 % (total:3347/3347)
# Top servers :
# xxxxx 36.6 % (total:1225/3347)
# yyyyy 22.26 % (total:745/3347)
# zzzzz 8.07 % (total:270/3347)
...
# Top URI(s) :
# /ffdgdfgd.dll 53.78 % (total:1800/3347)
# /gdfgd.aspx 32.42 % (total:1085/3347)
# /Admin/Contents/List 5.68 % (total:190/3347)
# /Service1/Service.asmx 2.54 % (total:85/3347)
# /> 1.05 % (total:35/3347)
# /service1/fffservice.asmx 0.75 % (total:25/3347)
# /CreditScoreWebService.asmx 0.75 % (total:25/3347)
# /signalr/poll 0.6 % (total:20/3347)
# /signalr/connect 0.6 % (total:20/3347)
# /Admin/Contents/Remove/1527 0.45 % (total:15/3347)
# />>> 0.36 % (total:12/3347)
# Top Zone(s) :
# BODY 60.35 % (total:2020/3347)
# ARGS 32.42 % (total:1085/3347)
# BODY|NAME 5.83 % (total:195/3347)
# URL 1.4 % (total:47/3347)
# Top Peer(s) :
# xx.xxx.xxx.xx 38.9 % (total:1302/3347)
# yy.yyy.yyy.yy 36.6 % (total:1225/3347)
```
same with -s :(
```bash
root@t-nlb-d:~# nxtool.py -f --slack -s xxx.test-yyy.org #the real host name from the stats
# size :1000
root@t-nlb-d:~#
```

**Comment by buixor** [comment]
mh, that is quite weird :)
It seems that nxtool does not see / find your templates.
Can you please check that the path pointed by nxapi.json (installed by default in /usr/local/etc/) contains actual templates ?

"naxsi" : {
 "rules_path" : "/etc/nginx/naxsi_core.rules",
 "template_path" : [ "tpl/"], 
 "geoipdb_path" : "nx_datas/country2coords.txt"
},

**Comment by 123BLiN** [comment]
You are the best from the best!

looks like some setup.py problem, but I'm not familiar with python.
I'v changed relative path to /usr/local/nxapi/tpl/ and /usr/local/nxapi/nx_datas/country2coords.txt in /usr/local/etc/nxapi.json:
```bash
"naxsi" : {
 "rules_path" : "/etc/nginx/naxsi_core.rules",
 "template_path" : [ "/usr/local/nxapi/tpl/"],
 "geoipdb_path" : "/usr/local/nxapi/nx_datas/country2coords.txt"
},
```
and all works.

Thank you very much again.

**Comment by buixor** [comment]
yes, definitely looks like me :p
