### ISSUE TITLE
Mixing hash tables and linked list with whitelists

### ISSUE THREAD

**Issue by craiglawson** [nbs-system/naxsi#220]
I'm told this should not work... 

I have many wl's setup which mix $URL_X and $BODY_VAR for example, nothing seems to scream and shout at me and it certainly appears to work as far as I can see...

Example from a Magento site:

BasicRule wl:1005 "mz:$URL_X:^/index.php/hostcontrolU23/catalog_product/validate/id/[0-9]{4,6}/back/edit/attributes/[^/]+\/key/[0-9a-z]{64}/active_tab/configurable/$|$BODY_VAR:product[meta_title]";

nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

**Comment by buixor** [comment]
Hey Craig,

Can you give a try to this branch : 

https://github.com/nbs-system/naxsi/tree/mixed_matchzone_detection


I added some code to detect matchzones mixing the regex and static string matches.

cheers,

**Comment by buixor** [comment]
Closing, @craiglawson will open if issue is spotted
