### ISSUE TITLE
Whitelist doesn't work with URL having capital letters

### ISSUE THREAD

**Issue by exebit** [nbs-system/naxsi#224]
Try whitelist this request:
https://some.domain.forth.level/Test?data="ddfg

Add this rule:
`BasicRule wl:1001 "mz:$URL:/Test|ARGS";`

And I see in logs 1001 rule (double quote) detection. As I change capital letters to lower case rule is working

**Comment by buixor** [comment]
Hi,

Both the patterns and the match zones arguments (here, /Test) must be lowercase, naxsi being case insensitive.
I edited the wiki to make it clearer,


thanks
