### ISSUE TITLE
How do I set up the nxapi?

### ISSUE THREAD

**Issue by MonkyHub** [nbs-system/naxsi#225]
Hi

I am a bit confused. Under "Simple usage approach", you describe what needs to be done, but you also presume things that are not explained. I have managed to make ElasticSearch run, but how does the entire setup look like?

All tutorials I've seen so far to generate the whitelists, are a couple of years old. It’s nice to offer tools, but it’s very frustrating when there is no explanation how to use and set them up correctly. There are explanations for the older versions, but none for the current version. That’s why I am asking for your support by providing a step by step guide.

**Comment by studersi** [comment]
Hi,
I had similar problems. I added some additional information to the nxapi readme file.

The pull request is pending, but have a look here, maybe this helps:
https://github.com/nbs-system/naxsi/pull/229/files

**Comment by buixor** [comment]
thanks !
