### ISSUE TITLE
Use nxapi generate whitelist, did not generate data！

### ISSUE THREAD

**Issue by orright** [nbs-system/naxsi#231]
error.log
[root@localhost bin]# grep NAXSI_FMT /usr/local/nginx/logs/error.log
2015/10/20 13:40:28 [error] 28677#0: *1 NAXSI_FMT: ip=192.168.100.212&server=192.168.100.222&uri=/&learning=0&vers=0.54&total_processed=1&total_blocked=1&block=1&cscore0=$XSS&score0=8&zone0=ARGS&id0=1302&var_name0=a, client: 192.168.100.212, server: localhost, request: "GET /?a=%3C HTTP/1.1", host: "192.168.100.222"
2015/10/20 13:41:43 [error] 28677#0: *12 NAXSI_FMT: ip=192.168.100.212&server=192.168.100.222&uri=/&learning=0&vers=0.54&total_processed=4&total_blocked=2&block=1&cscore0=$XSS&score0=8&zone0=ARGS&id0=1302&var_name0=a, client: 192.168.100.212, server: localhost, request: "GET /?a=%3C HTTP/1.1", host: "192.168.100.222"

[root@localhost nxapi]#  ./nxtool.py -x --colors -c nxapi.json --files=/usr/local/nginx/logs/error.log
# size :1000
# Whitelist(ing) ratio :
# Top servers :
# Top URI(s) :
# Top Zone(s) :
# Top Peer(s) :
[root@localhost nxapi]# 

I do not know what the reasons are, help me！ ths！

**Comment by lewismarshall** [comment]
:+1:  I get the same with the following data:

My Elasticsearch setup:
```
docker run -d --name es_thing  -p 9200:9200 quay.io/ukhomeofficedigital/elasticsearch:v0.1.1
curl -XPUT 'http://192.168.99.100:9200/nxapi/'
{"acknowledged":true}
```
Run tool:
```
./nxtool.py -x --colors -c nxapi.json --files=../../proxy.logs
# size :1000
# Whitelist(ing) ratio :
# Top servers :
# Top URI(s) :
# Top Zone(s) :
# Top Peer(s) :
```

Log Data:
```
grep NAXSI_FMT ../../proxy.logs
2015/10/20 15:34:23 [error] 19#0: *90 NAXSI_FMT: ip=10.10.67.1&server=fdcs-acceptance.notprod.homeoffice.gov.uk&uri=/documents/uploads&learning=0&vers=0.54&total_processed=39&total_blocked=1&block=1&zone0=BODY&id0=2&var_name0=, client: 10.10.67.1, server: proxy, request: "POST /documents/uploads?_csrf=04868dbb-de6d-4bcf-afb3-8162dbea8a5a HTTP/1.1", host: "fdcs-acceptance.notprod.homeoffice.gov.uk", referrer: "https://fdcs-acceptance.notprod.homeoffice.gov.uk/documents"
2015/10/20 15:34:27 [error] 19#0: *91 NAXSI_FMT: ip=10.10.67.1&server=fdcs-acceptance.notprod.homeoffice.gov.uk&uri=/documents/uploads&learning=0&vers=0.54&total_processed=50&total_blocked=2&block=1&zone0=BODY&id0=2&var_name0=, client: 10.10.67.1, server: proxy, request: "POST /documents/uploads?_csrf=04868dbb-de6d-4bcf-afb3-8162dbea8a5a HTTP/1.1", host: "fdcs-acceptance.notprod.homeoffice.gov.uk", referrer: "https://fdcs-acceptance.notprod.homeoffice.gov.uk/documents"
2015/10/20 15:39:23 [error] 19#0: *534 NAXSI_FMT: ip=10.10.67.1&server=fdcs-acceptance.notprod.homeoffice.gov.uk&uri=/documents/uploads&learning=0&vers=0.54&total_processed=444&total_blocked=3&block=1&zone0=BODY&id0=2&var_name0=, client: 10.10.67.1, server: proxy, request: "POST /documents/uploads?_csrf=e7ce6f9c-425e-40e5-b92b-b80f4b5915ab HTTP/1.1", host: "fdcs-acceptance.notprod.homeoffice.gov.uk", referrer: "https://fdcs-acceptance.notprod.homeoffice.gov.uk/documents"
2015/10/20 15:39:27 [error] 19#0: *534 NAXSI_FMT: ip=10.10.67.1&server=fdcs-acceptance.notprod.homeoffice.gov.uk&uri=/documents/uploads&learning=0&vers=0.54&total_processed=455&total_blocked=4&block=1&zone0=BODY&id0=2&var_name0=, client: 10.10.67.1, server: proxy, request: "POST /documents/uploads?_csrf=e7ce6f9c-425e-40e5-b92b-b80f4b5915ab HTTP/1.1", host: "fdcs-acceptance.notprod.homeoffice.gov.uk", referrer: "https://fdcs-acceptance.notprod.homeoffice.gov.uk/documents"
```
The version of NGINX etc. is built here:
https://github.com/UKHomeOffice/docker-ngx-openresty/blob/master/build.sh
But the NAXSI version is from here:
https://github.com/nbs-system/naxsi/archive/master.zip

Be good to find out more...

**Comment by blindpet** [comment]
@orright yours looks like it's not in learning mode since it says learningmode=0

Mine looks like this but it still isn't working

`2015/10/24 14:43:55 [error] 25837#25837: *2 NAXSI_FMT: ip=192.168.60.1&server=192.168.60.135&uri=/xss.php<script>alert('attacked')</script>&learning=1&vers=0.54&total_processed=16&total_blocked=14&block=1&cscore0=$SQL&score0=16&cscore1=$XSS&score1=64&zone0=URL&id0=1010&var_name0=&zone1=URL&id1=1011&var_name1=&zone2=URL&id2=1013&var_name2=&zone3=URL&id3=1302&var_name3=&zone4=URL&id4=1303&var_name4=, client: 192.168.60.1, server: default, request: "GET /xss.php%3Cscript%3Ealert('attacked')%3C/script%3E HTTP/1.1", host: "192.168.60.135"`



Checking returns blankness

    python nxtool.py -c ./nxapi.json  -x --colors

    # size :1000
    # Whitelist(ing) ratio :
    # Top servers :
    # Top URI(s) :
    # Top Zone(s) :
    # Top Peer(s) :

**Comment by orright** [comment]
In both cases, I tried, or not

**Comment by AnoopAlias** [comment]
I can confirm this tool is not working

 nxapi]# cat /var/log/nginx/error.log|grep NAXSI_FMT|wc -l
18

nxapi]# nxtool.py -x --colors -c nxapi.json --files=/var/log/nginx/error.log 
# size :1000
# Whitelist(ing) ratio :
# Top servers :
# Top URI(s) :
# Top Zone(s) :
# Top Peer(s) :

#################

 nxapi]# curl -XPOST "http://localhost:9200/nxapi/events/_search?pretty" -d '{}'
{
  "took" : 7,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  }
}
#######################

Should the learning be done on both access log and error log ?

**Comment by AnoopAlias** [comment]
Looks like the data is being populated if we omit the "-x" switch

nxtool.py -c nxapi.json --files=/var/log/nginx/error.log

works fine from my end . And as far as I can see..the learning need to be done only on error_log and not access log

**Comment by orright** [comment]
@AnoopAlias 
Finally solved?

**Comment by AnoopAlias** [comment]
Yes it works if we omit the -x switch . I think it's a mistake in the documentation

**Comment by orright** [comment]
@AnoopAlias 
thanks a lot ！！！

**Comment by buixor** [comment]
hi guys,

I pushed a fix that should avoid this, aborting if mutually exclusive options are present.

please re-open if it doesn't fix the issue

**Comment by AnoopAlias** [comment]
@buixor  - I think you have to edit the documentation at  https://github.com/nbs-system/naxsi/blob/master/nxapi/README.md

Particularly the line

#########
Load the data from the log file into ElasticSearch with the folloing command:
./nxtool.py -x --colors -c nxapi.json --files=/PATH/TO/LOGFILE.LOG
#########

**Comment by buixor** [comment]
changed, thanks ;)
