### ISSUE TITLE
wlr_url_hash and wlr_url_hash_bucket_size

### ISSUE THREAD

**Issue by AnoopAlias** [nbs-system/naxsi#232]
I could find the following error in a nxapi whitelist file loaded with a lot of entries. wlr_url_hash_bucket_size xxxx; does not seem to a valid nginx directive too.

Any idea how to increase these values?

nginx: [emerg] could not build the wlr_url_hash, you should increase wlr_url_hash_bucket_size: 512
nginx: [emerg] $URL hashtable init failed in /etc/nginx/nginx.conf:87
nginx: [emerg] WhiteList Hash building failed in /etc/nginx/nginx.conf:87
nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by buixor** [comment]
Hello,

Can you provide me more detals on how you triggered this error ? I think it should only happen if :
  * you have a lot of whitelists
  * you have incorrect whitelists that make hashtable build fail

If you could provide your configuration, it would probably help a lot :)

cheers,

**Comment by AnoopAlias** [comment]
Hi,

yes the particular config had a lot of whitelist . I am using NAXSI in a plugin integrated with the popular cPanel plugin and this  automatically populates the whitelist rules with a script 

##
https://raw.githubusercontent.com/AnoopAlias/nDeploy/master/rpm_buildtree/nginx-pkg-64-common/usr/nginx/scripts/nxapi-learn.sh.disabled
##

Since cPanel is mostly used in mass hosting setup and there will be lot of domains the whitelist file may get large for some domains .

I asked the same question in nginx userlist and was pointed to modifying the hardcoded values 

https://github.com/nbs-system/naxsi/blob/master/naxsi_src/naxsi_utils.c#L569-#L573

I am presently using  2048 for bucket size and 256000 for max_size .

Hopefully that will solve the issue?

**Comment by buixor** [comment]
yes, this will solve the issue, but I'm afraid that your way of generating whitelists is a bit optimistic, and you might end up allowing dangerous things :)

**Comment by AnoopAlias** [comment]
@buixor - Thanks . Can you point to a better way of whitelist generation . Note that there will be mostly 500+ vhosts on a typical server in mass hosting  and each will be managed by different users .

Also can you point me to the regex check you do (or any another better way) to ensure the mz regex doesnt contain "|" . Right now my what I do is do a final nginx config test and if it fails notify the server admin that whitelist generation has failed . 

Probably its better if you incorporate the check in nxtool whitelist generation itself ;so any rule that may generate a nginx config test failure is not generated,
