### ISSUE TITLE
nxtool.py doesn't work with elasticsearch 2.0

### ISSUE THREAD

**Issue by thomasjpatterson** [nbs-system/naxsi#233]
With the update to 2.0 for elasticsearch the nxtool no longer works for searching as it uses facets to search which were dropped in 2.0. Inputting works fine but when searching it displays this error: 
$ ./nxtool.py -x --colors -c nxapi.json
size :1000
Whitelist(ing) ratio :
No handlers could be found for logger "elasticsearch"
Traceback (most recent call last):
  File "./nxtool.py", line 253, in <module>
    translate.fetch_top(cfg.cfg["global_filters"], "whitelisted", limit=2)
  File "/home/Downloads/naxsi-master/nxapi/nxapi/nxtransform.py", line 529, in fetch_top
    res = self.search(esq)
  File "/home/Downloads/naxsi-master/nxapi/nxapi/nxtransform.py", line 560, in search
    x = self.es.search(index=self.cfg["elastic"]["index"], doc_type=self.cfg["elastic"]["doctype"], body=esq)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 70, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 429, in search
    params=params, body=body)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 274, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 55, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 83, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, {u'failed_shards': [{u'node': u'7OlvkMr2Q4CfinVEnmkgyA', u'index': u'nxapi', u'reason': {u'reason': u'failed to parse search source. unknown search element [facets]', u'type': u'search_parse_exception', u'line': 1, u'col': 2}, u'shard': 0}], u'root_cause': [{u'reason': u'failed to parse search source. unknown search element [facets]', u'type': u'search_parse_exception', u'line': 1, u'col': 2}], u'grouped': True, u'reason': u'all shards failed', u'phase': u'query', u'type': u'search_phase_execution_exception'})

**Comment by buixor** [comment]
Hi,

thanks for the notice, didn't try yet.
I'll try to get my hands on ES 2.X to fix the issue.
But this lack of backward compat is pretty annoying from them, they did the same between 0.9 and 1.X iirc.

**Comment by thomasjpatterson** [comment]
No problem and yeah it's bad when they just straight drop compatibility. It was going so smoothly then when I went to start whitelisting it went bad. For the time being I just dropped down to es1.x to continue working.

**Comment by calumah** [comment]
Hi, almost same error with elasticsearch 2.1 :

```
./nxtool.py -c nxapi.json -x
# size :1000
# Whitelist(ing) ratio :
Traceback (most recent call last):
  File "./nxtool.py", line 253, in <module>
    translate.fetch_top(cfg.cfg["global_filters"], "whitelisted", limit=2)
  File "/root/naxsi/nxapi/nxapi/nxtransform.py", line 529, in fetch_top
    res = self.search(esq)
  File "/root/naxsi/nxapi/nxapi/nxtransform.py", line 560, in search
    x = self.es.search(index=self.cfg["elastic"]["index"], doc_type=self.cfg["elastic"]["doctype"], body=esq)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 530, in search
    doc_type, '_search'), params=params, body=body)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 93, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, u'search_phase_execution_exception')
```

**Comment by buixor** [comment]
Hi,

Yes thank you for the report, I'm aware of that.
I'll try to get my hands on an ES 2.X instance any time soon and fix it .. really wish I can close this in the coming days, it's going to become a problem soon :)

**Comment by jean-loic** [comment]
Hi,
With ES 2.X facets have been deprecated and replaced by aggregations. Not sure it's the best way to do that but here's a patch for nxtransform.py (v0.54) to support aggregations :
```patch
528c528
<         esq['facets'] =  { "facet_results" : {"terms": { "field": field, "size" : self.es_max_size} }}
---
>         esq['aggregations'] =  { "agg1" : {"terms": { "field": field, "size" : self.es_max_size} }}
530c530,531
<         total = res['facets']['facet_results']['total']
---
>         #total = res['aggregations']['agg1']['buckets'][0]['doc_count']
>         total = res['hits']['total']
532,533c533,534
<         for x in res['facets']['facet_results']['terms']:
<             print "# "+self.grn.format(x['term'])+" "+str(round( (float(x['count']) / total) * 100.0, 2))+" % (total:"+str(x['count'])+"/"+str(total)+")"
---
>         for x in res['aggregations']['agg1']['buckets']:
>             print "# "+self.grn.format(x['key'])+" "+str(round( (float(x['doc_count']) / total) * 100.0, 2))+" % (total:"+str(x['doc_count'])+"/"+str(total)+")"
542c543
<         esq['facets'] =  { "facet_results" : {"terms": { "field": key, "size" : 50000} }}
---
>         esq['aggregations'] =  { "agg1" : {"terms": { "field": key, "size" : 50000} }}
544,546c545,547
<         for x in res['facets']['facet_results']['terms']:
<             if x['term'] not in uniques:
<                 uniques.append(x['term'])
---
>         for x in res['aggregations']['agg1']['buckets']:
>             if x['key'] not in uniques:
>                 uniques.append(x['key'])
```
Hope this can help

**Comment by buixor** [comment]
Dude, I don't know you, but I love you :)

Going to give it a try this week-end, and branch it.

**Comment by jean-loic** [comment]
Hi buixor,
I'm just a french FreeBSD naxsi fan. Used mod_security for a long time, even in positive mode with mod_profiler help and was searching for... naxsi. Thanks and keep on the good work.

**Comment by buixor** [comment]
thanks again, seems to work :+1: 

Closing issue until someone complains patch isn't working ;)

**Comment by aarvee11** [comment]
Works perfectly with the patch provided! You can go ahead and merge this!
