### ISSUE TITLE
BAD signature from "Naxsi Project (Key Used To Sign Code) <tko@nbs-system.com>"

### ISSUE THREAD

**Issue by Hard-Shade** [nbs-system/naxsi#234]
0.54 release does not verify. Prior release 0.54rc3.tar.gz verifies with no problem.

**Comment by quantumpacket** [comment]
@Hard-Shade see latest posts for https://github.com/nbs-system/naxsi/issues/201

**Comment by buixor** [comment]
do you believe I actually updated the signature ? :D

Sorry for the delay, I totally forgot about this.

Closing issue so that I see it if it happens again
