### ISSUE TITLE
nginx 1.8.0 wl cannot work

### ISSUE THREAD

**Issue by mrbaiwei** [nbs-system/naxsi#239]
2015/12/28 14:09:06 [debug] 14757#0: *4924 is rule [1007] whitelisted in zone ARGS for item attack
2015/12/28 14:09:06 [debug] 14757#0: *4924 extra: exception happened in |NAME
2015/12/28 14:09:06 [debug] 14757#0: *4924 rule 1007 is disabled somewhere
2015/12/28 14:09:06 [debug] 14757#0: *4924 hashing varname [attack]
2015/12/28 14:09:06 [debug] 14757#0: *4924 hashing varname [attack] (rule:1007) - 'wl:X_VAR:attack'
2015/12/28 14:09:06 [debug] 14757#0: *4924 hashing varname [attack] (rule:1007) - 'wl:X_VAR:attack|NAME'
2015/12/28 14:09:06 [debug] 14757#0: *4924 hashing uri#1 [/] (rule:1007) ($URL:X|URI)
2015/12/28 14:09:06 [debug] 14757#0: *4924 hashing uri#3 [#/] (rule:1007) ($URL:X|ZONE|NAME)
2015/12/28 14:09:06 [debug] 14757#0: *4924 hashing MIX [#/#attack] ($URL:x|$X_VAR:y) or ($URL:x|$X_VAR:y|NAME)
2015/12/28 14:09:06 [error] 14757#0: *4924 NAXSI_FMT: ip=1.1.1.1&server=www.x.com&uri=/&learning=0&vers=0.54&total_processed=726&total_blocked=10&block=1&cscore0=$SQL&score0=8&zone0=ARGS|NAME&id0=1007&var_name0=attack, client: 1.1.1.1, server: localhost, request: "HEAD /?attack=1 HTTP/1.0", host: "www. x.com"

MainRule "str:attack" "msg:ddos" "mz:ARGS|BODY" "s:$SQL:8" id:1007;
BasicRule wl:1007;

**Comment by buixor** [comment]
Please provide details : At least make it so that I don't have to scratch my head understanding what you actually mean :)

**Comment by mrbaiwei** [comment]
I've set the whitelist for id:1007 ,but access to be blocked
MainRule： "str:attack" "msg:ddos" "mz:ARGS|BODY" "s:$SQL:8" id:1007;
BasicRule：wl:1007;

debug info：
2015/12/28 14:09:06 [debug] 14757#0: *4924 is rule [1007] whitelisted in zone ARGS for item attack
2015/12/28 14:09:06 [debug] 14757#0: *4924 extra: exception happened in |NAME
2015/12/28 14:09:06 [debug] 14757#0: *4924 rule 1007 is disabled somewhere
2015/12/28 14:09:06 [debug] 14757#0: *4924 hashing varname [attack]
2015/12/28 14:09:06 [debug] 14757#0: *4924 hashing varname attack - 'wl:X_VAR:attack'
2015/12/28 14:09:06 [debug] 14757#0: *4924 hashing varname attack - 'wl:X_VAR:attack|NAME'
2015/12/28 14:09:06 [debug] 14757#0: *4924 hashing uri#1 / ($URL:X|URI)
2015/12/28 14:09:06 [debug] 14757#0: *4924 hashing uri#3 #/ ($URL:X|ZONE|NAME)
2015/12/28 14:09:06 [debug] 14757#0: *4924 hashing MIX #/#attack or ($URL:x|$X_VAR:y|NAME)
2015/12/28 14:09:06 [error] 14757#0: *4924 NAXSI_FMT: ip=1.1.1.1&server=www.x.com&uri=/&learning=0&vers=0.54&total_processed=726&total_blocked=10&block=1&cscore0=$SQL&score0=8&zone0=ARGS|NAME&id0=1007&var_name0=attack, client: 1.1.1.1, server: localhost, request: "HEAD /?attack=1 HTTP/1.0", host: "www. x.com"

**Comment by buixor** [comment]
Can you provide a reproducible test case ? Because this kind of case should be covered by naxsi and is part of unit tests : t/01naxsi_whitelists.t


ie. provide config + request

**Comment by mrbaiwei** [comment]
cat site.rules
#LearningMode; #Enables learning mode
SecRulesEnabled;
#SecRulesDisabled;
DeniedUrl "/RequestDenied";
## check rules
CheckRule "$SQL >= 8" BLOCK;
BasicRule wl:1007;

cat naxsi_core.rules
MainRule "str:attack" "msg:ddos" "mz:ARGS|BODY" "s:$SQL:8" id:1007;

test url:
http://s-241185.gotocdn.com/?attack=1

**Comment by buixor** [comment]
Hi,

I guess you should use  BasicRule wl:4201 "mz:ARGS|NAME"; for the whitelist.
Simply BasicRule wl:XX does not seem to apply in |NAME zone, I'm self opening issue :)

**Comment by mrbaiwei** [comment]
ok，thank you！
