### ISSUE TITLE
rules 10，16

### ISSUE THREAD

**Issue by mrbaiwei** [nbs-system/naxsi#240]
&vers=0.54total_processed=766&total_blocked=54&block=1&zone0=BODY&id0=10&var_name0=body5
&vers=0.54&total_processed=2900&total_blocked=86&block=1&zone0=BODY&id0=16&var_name0=

how to disable this rules

**Comment by buixor** [comment]
Whitelist it as any other rule ? Or I misunderstood your question ?

**Comment by mrbaiwei** [comment]
i don't set whitelist and I did not set the id to 10 and 16 the main rule
but errorlog display id: 10,16 appear to be matching interception
