### ISSUE TITLE
whitelists problem

### ISSUE THREAD

**Issue by mrbaiwei** [nbs-system/naxsi#242]
hi：
my MainRule ：
MainRule "rx:select|union|update|delete|insert|table|from|ascii|hex|unhex|drop" "msg:sql keywords" "mz:ARGS" "s:$SQL:4" id:1000;
BasicRules:
BasicRule wl:1000 "mz:$URL:/admin.php|ARGS";
BasicRule wl:1000 "mz:$URL_X:/admin\.php|ARGS";
request:
/admin.php?action=members&operation=clean&confirmed=yes&submit=yes&includepost=yes&includeuc=yes&current=0&pertask=1000&lastprocess=&allnum=0&deletestart=0&deleteitem=blog
all did not match

**Comment by mrbaiwei** [comment]
test for a long time,must add NAME,like
BasicRule wl:1000 "mz:$URL:/admin.php|ARGS|NAME";

**Comment by buixor** [comment]
?

Please, keep the issue concise and factual, it's not a forum :p

If you want to discuss etc. go on irc #naxsi on freenode, thanks.
