### ISSUE TITLE
_X with square bracket regex + |NAME gets ignored

### ISSUE THREAD

**Issue by vladimir000** [nbs-system/naxsi#245]
Hi,

I have this whitelist:

BasicRule wl:1000,1007,1009,1100,1101,1310,1311 "mz:$URL_X:^/[a-z\\-]+\.php$|$ARGS_VAR_X:^[\\[\\]a-z\\_\-]+$|NAME";

1007 rule would match on /index.php?----=a&------=a
But it is correctly whitelisted

1310-1311 rule would match on /index.php?a[z_1]=abc&a[z_1]=abc&a[z_1]=abc&a[z_1]=abc&a[z_1]=abc&
And it still matches:

ip=X&server=Y&uri=/index.php&learning=1&vers=0.54&total_processed=20&total_blocked=1&block=1&cscore0=$XSS&score0=40&zone0=ARGS|NAME&id0=1310&var_name0=a[z_1]&zone1=ARGS|NAME&id1=1311&var_name1=a[z_1]&zone2=ARGS|NAME&id2=1310&var_name2=a[z_1]&zone3=ARGS|NAME&id3=1311&var_name3=a[z_1]&zone4=ARGS|NAME&id4=1310&var_name4=a[z_1]&zone5=ARGS|NAME&id5=1311&var_name5=a[z_1]&zone6=ARGS|NAME&id6=1310&var_name6=a[z_1]&zone7=ARGS|NAME&id7=1311&var_name7=a[z_1]&zone8=ARGS|NAME&id8=1310&var_name8=a[z_1]&zone9=ARGS|NAME&id9=1311&var_name9=a[z_1],

I tried until the latest commit at the time of writing (as i saw you fixed some matches for |NAME), but still get the same issue with the brackets in regex for |NAME matching, works fine for variable values (just |NAME gives problems).

**Comment by buixor** [comment]
Hi,

I think you regex's wrong :p

^[\[\]a-z_0-9-]+$ instead of ^[\[\]a-z\_-]+$ would do the trick no ?

**Comment by buixor** [comment]
Closing, because I think it's linked to that, please re-open if it's not :)
