### ISSUE TITLE
Truncated error.log line

### ISSUE THREAD

**Issue by sm0k** [nbs-system/naxsi#247]
Hi,

Today I tried to run sqlmap against Naxsi, it appears that long url are truncated in logs:

`2016/02/05 18:42:01 [error] 15040#15040: *280 NAXSI_FMT: ip=10.8.0.10&server=192.168.122.126&uri=/index.php&learning=1&vers=0.54&total_processed=182&total_blocked=86&block=1&cscore0=$SQL&score0=74&cscore1=$XSS&score1=48&zone0=ARGS&id0=1000&var_name0=id&zone1=ARGS&id1=1002&var_name1=id&zone2=ARGS&id2=1007&var_name2=id&zone3=ARGS&id3=1009&var_name3=id&zone4=ARGS&id4=1010&var_name4=id&zone5=ARGS&id5=1011&var_name5=id&zone6=ARGS&id6=1015&var_name6=id, client: 10.8.0.10, server: _, request: "GET /index.php?id=1%20UNION%20ALL%20SELECT%20NULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CCONCAT%280x716a766b71%2C%28CASE%20WHEN%20%288234%3D%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%`

Problem: no closing ", and no host: "192.168.122.126" value.

Is there a workaround? Cause it triggers grokparse errors when my logstash tries to handle these lines.

Thanks

**Comment by buixor** [comment]
Hi,

I need to double-check but afaik it's a limitation in nginx (naxsi relies on nginx's api for that)

**Comment by sm0k** [comment]
Ok, you're right, it an hardcoded limitation of nginx. The only way to extend the 2048 char limit is to recompile Nginx... Will follow another path.

Thank you!

**Comment by buixor** [comment]
Hi,

You can as well use $naxsi_extensive_log to get more info ;)
