### ISSUE TITLE
Dynamic loadable support

### ISSUE THREAD

**Issue by sbagmeijer** [nbs-system/naxsi#249]
Hello if you have some time would it be possible to add support for loading this great module as a dynamic module as is supported in the new nginx 1.9.11?

https://www.nginx.com/blog/dynamic-modules-nginx-1-9-11/
https://www.nginx.com/resources/wiki/extending/converting/

**Comment by buixor** [comment]
Hi,

Please see branch naxsi-loadable :
https://github.com/nbs-system/naxsi/tree/naxsi-loadable

Tell me if you see any issues.

**Comment by sbagmeijer** [comment]
Sorry for the late reply! thank you for adding the support :+1: !

**Comment by buixor** [comment]
has been merged in master ;)
