### ISSUE TITLE
Nginx 1.9.11 release now supports dynamic modules

### ISSUE THREAD

**Issue by danlsgiga** [nbs-system/naxsi#250]
This is more a feature request than anything else. Would be possible to build a loadable module for the latest and greatest Nginx 1.9.11 version?
The dynamic module loading was released and would be awesome to have naxsi as a dynamic module.

https://www.nginx.com/blog/dynamic-modules-nginx-1-9-11/

**Comment by ihacku** [comment]
https://github.com/nbs-system/naxsi/issues/249

**Comment by danlsgiga** [comment]
Oops, sorry about that. I did search for a similar before submitting this one... but I did only on the open issues... my bad.

Thanks a lot!! ;)
