### ISSUE TITLE
Disabling rule

### ISSUE THREAD

**Issue by xavier777** [nbs-system/naxsi#259]
Hi, 

Naxsi is blocking POST request when i'm uploading images on my site.

I put the BasicRule whitelist as suggered beside but NAXSI still blocking the image upload.

> ########### Optimized Rules Suggestion ##################
> \# total_count:7 (100.0%), peer_count:1 (100.0%) | request too big, stored on disk and not parsed
> BasicRule wl:2 "mz:$URL:/calendar/submit/|BODY";

What's wrong ?

Thanks by advance,
Xavier

**Comment by buixor** [comment]
Please provide more information for us to reproduce the bug.
request / expected response / NAXSI_FMT.

**Comment by xavier777** [comment]
Hi Buixor,

NoPhear wrote this issue on my recommandations : 

https://github.com/nbs-system/naxsi/issues/251

I want bypass BasicRule wl:2


when you say : Please provide a way to reproduce your error.

What do you need ?

Thanks by advance,
Xavier
