### ISSUE TITLE
reverse proxy 

### ISSUE THREAD

**Issue by yurilaaziz** [nbs-system/naxsi#260]
I want to ask if there is a possibility to redirect the traffic to another server instead the /RequestDenied Page ? 

 location / {
        proxy_pass       http://172.24.1.30:80;
        proxy_set_header  Host $http_host;
        include           /etc/nginx/naxsi.rules;
        }
        # Only for nginx-naxsi used with nginx-naxsi-ui : process denied requests
        location /RequestDenied {
                proxy_pass http://172.24.1.31:80;
                #return 500;
        }

but when I do 
` wget http://172.24.1.32/?a=%3C`

```
--2016-03-17 07:15:54--  http://172.24.1.32/?a=%3C
Connecting to 172.24.1.32:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://172.24.1.32/RequestDenied/ [following]
--2016-03-17 07:15:54--  http://172.24.1.32/RequestDenied/
Reusing existing connection to 172.24.1.32:80.
```

I want that may honeypot server ! get all the traffic

**Comment by buixor** [comment]
Yes, you should be able to, can you give more context about the issues you are facing ?

**Comment by yurilaaziz** [comment]
yes it's work fine with adding a trailing slash
`proxy_pass http://172.24.1.31:80/; `

can we log the GET and POST vars of the blocked request ?

**Comment by buixor** [comment]
Please take a look at the wiki ... 

https://github.com/nbs-system/naxsi/wiki/deniedurl
