### ISSUE TITLE
nxapi tag_events loop bug

### ISSUE THREAD

**Issue by aiwilliams** [nbs-system/naxsi#263]
I have a few million blocks logged over three days after enabling naxsi in `LearningMode`. After importing them into Elasticsearch, and creating some whitelist rules, then running the `--tag` feature of nxapi, I ran into a couple of issues.

1. When more than 10,000 results would come back in the loop, there would be an error from Elasticsearch telling me to take a different approach. I solved this by checking to see whether there were more than 20K results in the batch.
2. Sometimes all the records would be tagged, so that `count < total_events`, but `for item in res['hits']['hits']:` would run against 0 results, leading to an infinite loop.

Both are addressed in this diff. I do not know enough to suggest the best solution. I hope this is helpful.

```
diff --git a/nxapi/nxapi/nxtransform.py b/nxapi/nxapi/nxtransform.py
index d8a82c8..a307c1b 100644
--- a/nxapi/nxapi/nxtransform.py
+++ b/nxapi/nxapi/nxtransform.py
@@ -647,13 +647,17 @@ class NxTranslate():
         total_events = int(str(x["hits"]["total"]))
         print str(self.grn.format(total_events)) + " items to be tagged ..."
         size = int(x['hits']['total'])
-        if size > 100:
+        if size > 20000:
+            size = size / 100
+        elif size > 100:
             size = size / 10
         while count < total_events:
             esq["size"] = size
             esq["from"] = 0
             res = self.search(esq)
             # Iterate through matched evts to tag them.
+            if int(res['hits']['total']) == 0:
+                break
             for item in res['hits']['hits']:
                 eid = item['_id']
                 body = item['_source']
```

**Comment by buixor** [comment]
oh thank you very much for the report and the bugfix.
I can't check it myself this week, but I'll give you a feedback next week, and properly merge it :)

**Comment by buixor** [comment]
Your fix works perfectly.
Do you want me to patch it, or do you prefer to do a MR ?

**Comment by aiwilliams** [comment]
@buixor Please, feel free to patch it. I hope it makes your life easier and not harder :blush:
