### ISSUE TITLE
NAXSI_NXLOG has form variable name and value swapped

### ISSUE THREAD

**Issue by aiwilliams** [nbs-system/naxsi#264]
I'm seeing that sometimes NAXSI_EXLOG comes out weird like `var_name=https://somewhere.org&content=data[auth_domain]`. When I look around in the code, I see [this confusing bit](https://github.com/nbs-system/naxsi/blob/e757f4992a7b6b48b951a68b2fbddcdb8c554ddd/naxsi_src/naxsi_runtime.c#L1042) where name and value are swapped when extensive logging is enabled.

**Comment by aiwilliams** [comment]
To clarify, I am using nxapi and I have a lot of data where the name/value is swapped. Looking at the actual log data (before loading it into Elasticsearch), I see that the name/value are swapped. The data that is correct is in lines where naxsi would have blocked if I were not in LearningMode.

**Comment by buixor** [comment]
Hi, Can you provide a way to reproduce it ?
I'm not sure which case you refer to, but I think it might "seem" swapped, but it's because the exception happened in the name of the variable, rather than the content, thus the switch. (I don't know if it's clear, but it is entended)

**Comment by aiwilliams** [comment]
@buixor Seems you are correct! Thanks for your response.

```
<187>Mar 30 14:57:26 myserver.com nginx: 2016/03/30 14:57:26 [error] 7853#0: *53 NAXSI_EXLOG: ip=11.11.11.11&server=myserver.com&uri=/something.json&id=1000&zone=ARGS|NAME&var_name=somewhere&content=from, client: 11.11.11.11, server: myserver.com, request: "GET /something.json?from=somewhere HTTP/1.1", host: "myserver.com"
```

That is generated from this request:
```
curl https://myserver.com/something.json?from=somewhere
```

* `zone=ARGS|NAME`
* `var_name=somewhere`
* `content=from`

The `from` variable name violates rule `1000`.

**Comment by jmce** [comment]
A similar issue for BODY args was mentioned here https://github.com/nbs-system/naxsi/issues/110 but at least in what's included in dotdeb's nginx-naxsi & nginx-extras [1.8.1-1~dotdeb+8.1],
apparently [per naxsi.h] version 0.54, EXLOG output still has var_name and content swapped when zone=ARGS|NAME or BODY|NAME. 

E.g.,  a URL with a query including   "…&updated=true&…" results in 
var_name=true and content=updated info in EXLOG output lines.
