### ISSUE TITLE
config was not found

### ISSUE THREAD

**Issue by dcalixto** [nbs-system/naxsi#268]
on compiling show this error:
```
adding module in /home/ubuntu/nginxmodule/naxsi-0.54
./configure: error: no /home/ubuntu/nginxmodule/naxsi-0.54/config was found

```

someone with this issue?

**Comment by michaelstephenson** [comment]
what version of ubuntu are you using?

**Comment by dcalixto** [comment]
@michaelstephenson , i'm using 14.04 trusty.

**Comment by blotus** [comment]
Hi,

It seems you provided a wrong path to nginx, you have to provide the path of the naxsi_src directory (which would be /home/ubuntu/nginxmodule/naxsi-0.54/naxsi_src/ in your case).

**Comment by dcalixto** [comment]
thak you very much @blotus. that's it, just one doubt naxsi did work with openssl? may i really have to install zlib?

**Comment by blotus** [comment]
Yes, naxsi does work with SSL. Naxsi doesn't use zlib, but nginx does in the gzip module. If you don't want to install zlib, just remove the gzip module from nginx (--without-http_gzip_module in your ./configure args should work).

**Comment by dcalixto** [comment]
right, thank you!
