### ISSUE TITLE
id:10, "invalid hex encoding, null bytes" false flag in multipart/form-data POST

### ISSUE THREAD

**Issue by christopherjdickson** [nbs-system/naxsi#270]
Running version 0.54, I'm seeing a bunch of errors like this and trying to validate if it's intended behavior:

```
learning=1&vers=0.54&total_processed=10503&total_blocked=57&block=1&zone0=BODY&id0=10&var_name0=incomingsubject&zone1=BODY&id1=10&var_name1=incomingbody
```

Here are the relevant portions of the POST:

```
------WebKitFormBoundary5OdelRospReihJ33\x0D\x0AContent-Disposition: form-data; name=\x22incomingSubject\x22\x0D\x0A\x0D\x0AApplication Received for %JOB_ORDER_TITLE%\x0D\x0A
```

```
------WebKitFormBoundary5OdelRospReihJ33\x0D\x0AContent-Disposition: form-data; name=\x22incomingBody\x22\x0D\x0A\x0D\x0AAn applicant has applied to the <strong>%JOB_ORDER_TITLE%</strong> position posted at %MY_PORTAL%<br />\x0D\x0A<br />\x0D\x0A%APPLICATION_SUMMARY%\x0D\x0A
```

Are the `%TAG%` segments tripping up NAXSI?

**Comment by christopherjdickson** [comment]
After reviewing the code for the `naxsi_unescape_uri` function, I realize my question is silly. We're gonna have to either escape the `%`'s or whitelist id:10.

**Comment by christopherjdickson** [comment]
Actually I think this might be a bug in Naxsi. As far as I can determine, `%`'s do not need to be escaped between the boundaries of a multipart/form-data POST.

In Naxsi, `ngx_http_dummy_multipart_parse` relies on `naxsi_unescape_uri` to check for null bytes, but `naxsi_unescape_uri` has some strict rules about the presence of `%`'s which are causing requests like the one above to be blocked.

**Comment by buixor** [comment]
Hi,

sorry for slight delays, I was out :)
Let me come back to you on this topic quickly

**Comment by buixor** [comment]
actually for this specific issue, I prefer to stick with the current behavior (trying to decode even in mutlipart), and accept the false positive, it might create a

**Comment by buixor** [comment]
I'm closing the issue, if you think (besides the fault positive) it might have implications, feel free to re-open it :)

**Comment by christopherjdickson** [comment]
If this issue is deemed working as intended, I would endorse a solution for #142 (whitelisting based on the value of an argument). In the present state, my only option is to effectively disable id:10 by whitelisting it in mz:BODY across the board. This is undesirable but apparently necessary unless you have any suggestions. 

For instance, the `%TAG%` strings appear in emails being sent from our system. I would like to be able to whitelist id:10 on mz BODY whenever the value of argument `a` is `sendEmail`. Is there any way to accomplish this?
