### ISSUE TITLE
Please add `|` support in regexps

### ISSUE THREAD

**Issue by jvoisin** [nbs-system/naxsi#271]
Currently, naxsi doens't support `|` in regexps, even while they are quoted :/

**Comment by buixor** [comment]
yes, it would be a much needed change, but I didn't find a clean/cool way to do so without breaking backward compat, I'm open to suggestions :)

**Comment by markussackmann** [comment]
You could have an optional variable in naxsi_core.rules witch defines the delimiter.

**Comment by buixor** [comment]
@jvoisin YOU ARE NOT ALLOWED TO VOTE ON THIS ISSUE !!!

jk actually that a smart suggestion @markussackmann :)

**Comment by jvoisin** [comment]
<s>Fuck, I thought that the vote was anonym</s> OMG MY ACCOUNT WAS HACKED! I wish I could remove my vote, but alas, it's too late.

**Comment by danlsgiga** [comment]
This would be really appreaciated! :)

**Comment by buixor** [comment]
I will try to make it happen for 0.56 with configuration parsing rewrite :)
