### ISSUE TITLE
Event Log Control

### ISSUE THREAD

**Issue by dlucenario** [nbs-system/naxsi#272]
Is there a way to pass the logs to a LUA script? Im using an OpenResty function called access_by_lua_file to call a LUA script. Basically I want to get the contents being written in the error log during a request and pass it to a LUA script. 

![def-conf](https://cloud.githubusercontent.com/assets/7834465/14524200/dab1e36e-0269-11e6-879a-c59cf659a076.png)

![naxsi-log](https://cloud.githubusercontent.com/assets/7834465/14524337/6ee8496a-026a-11e6-95c8-4166cbcbf025.png)

**Comment by buixor** [comment]
Hi,

Those are passed via HTTP headers, please see : 
https://github.com/nbs-system/naxsi/wiki/deniedurl

let me know if it doesn't fit your needs :)
