### ISSUE TITLE
don't generating zone-variable where naxsi in learningmode=1 

### ISSUE THREAD

**Issue by mikhail-yarosh** [nbs-system/naxsi#278]
After enableing learningmode nginx-log contain this:
2016/05/04 14:12:36 [error] 21378#21378: *932 NAXSI_FMT: ip=91.205.147.166&server=test.int&uri=/&learning=1&vers=0.54&total_processed=48&total_blocked=48&block=1, client: xxx.xxx.xxx.xxx, server: test.int, request: "POST / HTTP/1.1", host: "test.int", referrer: "https://test.int/wmpaycheck.php"
2016/05/04 14:16:55 [error] 21378#21378: *1207 NAXSI_FMT: ip=176.114.39.191&server=test.int&uri=/&learning=1&vers=0.54&total_processed=63&total_blocked=63&block=1, client: xxx.xxx.xxx.xxx, server: test.int, request: "GET / HTTP/1.1", host: "test.int"
2016/05/04 14:17:00 [error] 8180#8180: *1197 NAXSI_FMT: ip=176.114.39.191&server=test.int&uri=/&learning=1&vers=0.54&total_processed=55&total_blocked=55&block=1, client: xxx.xxx.xxx.xxx, server: test.int, request: "GET / HTTP/1.1", host: "test.int"

and when i using nxtool to add this to elasticsearch i have much warnings:
./nxtool.py -c test.json --files=nginx.log
# size :1000
WARNING:root:Python's GeoIP module is not present.
            'World Map' reports won't work,
            and you can't use per-country filters.
Unable to get GeoIP
WARNING:root:List of files :['/nginx.log']
log open
WARNING:root:Malformed/incomplete event [no zone]
{'date': '2016-05-04T13:50:16+03', 'events': []}
WARNING:root:Malformed/incomplete event [no zone]
{'date': '2016-05-04T13:52:16+03', 'events': []}
WARNING:root:Malformed/incomplete event [no zone]
{'date': '2016-05-04T13:52:41+03', 'events': []}
WARNING:root:Malformed/incomplete event [no zone]
{'date': '2016-05-04T13:53:09+03', 'events': []}
WARNING:root:Malformed/incomplete event [no zone]

./nxtool.py -x --colors -c test.json
# size :1000
# Whitelist(ing) ratio :
# Top servers :
# Top URI(s) :
# Top Zone(s) :
# Top Peer(s) :

naxsi rules geted from nginx-naxsi ubuntu-package

Whereis trouble?

**Comment by hobochili** [comment]
There was a previous issue with event insertion when the GeoIP python module is absent from the system (#207). Does it work with the GeoIP module installed?

**Comment by mikhail-yarosh** [comment]
Still same trouble with adding data. Warning about GeoIP missing now cleared.

**Comment by mikhail-yarosh** [comment]
./nxtool.py -c test.json --files=nginx.log
# size :1000
WARNING:root:List of files :['nginx.log']
log open
WARNING:root:Malformed/incomplete event [no zone]
{'date': '2016-05-04T13:50:16+03', 'events': []}
WARNING:root:Malformed/incomplete event [no zone]
{'date': '2016-05-04T13:52:16+03', 'events': []}
WARNING:root:Malformed/incomplete event [no zone]
{'date': '2016-05-04T13:52:41+03', 'events': []}
WARNING:root:Malformed/incomplete event [no zone]
{'date': '2016-05-04T13:53:09+03', 'events': []}
WARNING:root:Malformed/incomplete event [no zone]
{'date': '2016-05-04T13:59:17+03', 'events': []}
WARNING:root:Malformed/incomplete event [no zone]
{'date': '2016-05-04T14:06:31+03', 'events': []}
WARNING:root:Malformed/incomplete event [no zone]
{'date': '2016-05-04T14:10:12+03', 'events': []}

**Comment by mikhail-yarosh** [comment]
Sorry guys, i found issue in configuration: # inlude _core rules; in /etc/nginx/nginx.conf.
So sad...
