### ISSUE TITLE
No match on ARGS with /?foo=

### ISSUE THREAD

**Issue by markussackmann** [nbs-system/naxsi#280]
Request with ARGS to / won't trigger a rule.

e.g. http://localhost/?foo=bar,foo doesn't produce a NAXSI_EXLOG with id 1015.

**Comment by buixor** [comment]
Hello,

I'm not sure to understand the problem :

 - if I enable $naxsi_extensive_log, I do get the NAXSI_EXLOG.
 - Without extensive log (and in learning mode), one hit on 1015 isn't enough to trigger a block, so it wouldn't be logged.

thanks,

**Comment by markussackmann** [comment]
Hi,

Id 1015 is just an example. There is no match to any rule on a url with only a single slash.

This gets a hit:
http://localhost/index.htm?foo=bar,foo

This doesn't get a hit:
http://localhost/?foo=bar,foo

Talking about tree improved-blacklist-matchzones. Version 0.55rc1 works correctly.

**Comment by buixor** [comment]
ah ok, thanks for the notice :)
I'll get a quick look and keep you posted, hopefully today !

**Comment by buixor** [comment]
Hello,

Sorry, but I didn't managed to reproduce the bug, can you provide some kind of reproducible test case ?

**Comment by markussackmann** [comment]
Must be something with my configuration. After installing original naxsi_core.rules everything works as expected. Sorry for wasting your time.

**Comment by buixor** [comment]
Don't worry and thank you for reporting :)
