### ISSUE TITLE
$URL_X fails

### ISSUE THREAD

**Issue by RobDana** [nbs-system/naxsi#286]
I'm unable to get $URL_X to work at all.
BasicRule wl:1000 "mz:$URL_X:^/foo$|ARGS";
I've used just a single rule as an example and it fails with: 
Naxsi-Config : Incorrect line BasicRule wl:1000 (/build/nginx-BU0ZJt/nginx-1.4.6/debian/modules/naxsi/naxsi_src/naxsi_skeleton.c/393)... in /etc/nginx/naxsi_whitelist.rules:1

**Comment by blotus** [comment]
Which version of naxsi do you use ? Regexes in whitelists are supported since version 0.52.

**Comment by RobDana** [comment]
Thank You @blotus This was indeed the issue. I had installed the 'latest' with apt-get on Ubuntu 14 and find that it's not 'the latest'
