### ISSUE TITLE
Add some undefined behaviour checkers

### ISSUE THREAD

**Issue by jvoisin** [nbs-system/naxsi#290]
It would be great to add some `-fsanitize` flags for the testsuite  , in order to catch *interesting* things :)
They are supported by [gcc]( https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html ) and [clang]( http://llvm.org/releases/3.4/tools/clang/docs/AddressSanitizer.html )

**Comment by buixor** [comment]
fsanitize bringed too much trouble to integrate in tests suite right now, but i'm working on valgrind integration :)
