### ISSUE TITLE
unable to make post after install naxsi please help me

### ISSUE THREAD

**Issue by prithamgit** [nbs-system/naxsi#296]
hi i'm using naxsi-nginx reverse proxy now i added this [whitelist.rules](https://github.com/nbs-system/naxsi-rules/blob/master/wordpress.rules) for my wordpress site some part of site workining fine after adding this rules but i'm not able to make posts and geting this error 406 Not Acceptable
please help me sir. sorry if i ask it in wrong place

**Comment by Doemela** [comment]
Provide log of this else nobody can help. I use it on +10 WP sites never had this

**Comment by prithamgit** [comment]
`2016/06/27 15:51:23 [error] 2787#2787: *355 NAXSI_FMT: seed_end=605&zone49=BODY|NAME&id49=1311&var_name49=ubermenu_general[scrollto_duration]&zone50=BODY|NAME&id50=1310&var_name50=ubermenu_general[collapse_after_scroll]&zone51=BODY|NAME&id51=1311&var_name51=ubermenu_general[collapse_after_scroll]&zone52=BODY|NAME&id52=1310&var_name52=ubermenu_general[collapse_after_scroll]&zone53=BODY|NAME&id53=1311&var_name53=ubermenu_general[collapse_after_scroll]&zone54=BODY|NAME&id54=1310&var_name54=ubermenu_general[remove_conflicts]&zone55=BODY|NAME&id55=1311&var_name55=ubermenu_general[remove_conflicts]&zone56=BODY|NAME&id56=1310&var_name56=ubermenu_general[remove_conflicts]&zone57=BODY|NAME&id57=1311&var_name57=ubermenu_general[remove_conflicts]&zone58=BODY|NAME&id58=1310&var_name58=ubermenu_general[autocomplete_max_term_results]&zone59=BODY|NAME&id59=1311&var_name59=ubermenu_general[autocomplete_max_term_results]&zone60=BODY|NAME&id60=1310&var_name60=ubermenu_general[autocomplete_max_post_results]&zone61=BODY|NAME&id61=1311&var_name61=ubermenu_general[autocomplete_max_post_results]&zone62=BODY|NAME&id62=1310&var_name62=ubermenu_general[autocomplete_disable]&zone63=BODY|NAME&id63=1311&var_name63=ubermenu_general[autocomplete_disable]&zone64=BODY|NAME&id64=1310&var_name64=ubermenu_general[dynamic_authors_disable]&zone65=BODY|NAME&id65=1311&var_name65=ubermenu_general[dynamic_authors_disable]&zone66=BODY|NAME&id66=1310&var_name66=ubermenu_general[admin_notices]&zone67=BODY|NAME&id67=1311&var_name67=ubermenu_general[admin_notices]&zone68=BODY|NAME&id68=1310&var_name68=ubermenu_general[admin_notices]&zone69=BODY|NAME&id69=1311&var_name69=ubermenu_general[admin_notices]&zone70=BODY|NAME&id70=1310&var_name70=ubermenu_general[accessible]&zone71=BODY|NAME&id71=1311&var_name71=ubermenu_general[accessible]&zone72=BODY|NAME&id72=1310&var_name72=ubermenu_general[accessible]&zone73=BODY|NAME&id73=1311&var_name73=ubermenu_general[accessible]&seed_start=714, client: 10.0.0.2, server: www.zk.in, request: "POST /wp-admin/options.php HTTP/
2016/06/27 15:51:23 [error] 2787#2787: *355 NAXSI_FMT: seed_end=714&zone74=BODY|NAME&id74=1310&var_name74=ubermenu_general[load_google_cse]&zone75=BODY|NAME&id75=1311&var_name75=ubermenu_general[load_google_cse]&zone76=BODY|NAME&id76=1310&var_name76=ubermenu_general[load_google_cse]&zone77=BODY|NAME&id77=1311&var_name77=ubermenu_general[load_google_cse]&zone78=BODY|NAME&id78=1310&var_name78=ubermenu_general[ubermenu_toolbar]&zone79=BODY|NAME&id79=1311&var_name79=ubermenu_general[ubermenu_toolbar]&zone80=BODY|NAME&id80=1310&var_name80=ubermenu_general[ubermenu_toolbar]&zone81=BODY|NAME&id81=1311&var_name81=ubermenu_general[ubermenu_toolbar]&zone82=BODY|NAME&id82=1310&var_name82=ubermenu_general[force_filter]&zone83=BODY|NAME&id83=1311&var_name83=ubermenu_general[force_filter]&zone84=BODY|NAME&id84=1310&var_name84=ubermenu_general[disable_class_filtering]&zone85=BODY|NAME&id85=1311&var_name85=ubermenu_general[disable_class_filtering]&zone86=BODY|NAME&id86=1310&var_name86=ubermenu_general[disable_custom_admin_walker]&zone87=BODY|NAME&id87=1311&var_name87=ubermenu_general[disable_custom_admin_walker]&zone88=BODY|NAME&id88=1310&var_name88=ubermenu_general[strict_mode]&zone89=BODY|NAME&id89=1311&var_name89=ubermenu_general[strict_mode]&zone90=BODY|NAME&id90=1310&var_name90=ubermenu_general[strict_mode]&zone91=BODY|NAME&id91=1311&var_name91=ubermenu_general[strict_mode]&zone92=BODY|NAME&id92=1310&var_name92=ubermenu_general[ubermenu_theme_location]&zone93=BODY|NAME&id93=1311&var_name93=ubermenu_general[ubermenu_theme_location]&zone94=BODY|NAME&id94=1310&var_name94=ubermenu_general[diagnostics]&zone95=BODY|NAME&id95=1311&var_name95=ubermenu_general[diagnostics]&zone96=BODY|NAME&id96=1310&var_name96=ubermenu_general[diagnostics]&zone97=BODY|NAME&id97=1311&var_name97=ubermenu_general[diagnostics]&zone98=BODY|NAME&id98=1310&var_name98=ubermenu_general[lite_mode]&zone99=BODY|NAME&id99=1311&var_name99=ubermenu_general[lite_mode], client: 10.0.0.2, server: www.zk.in, request: "POST /wp-admin/options.php HTTP/1.1", host: "zk.i
2016/06/28 03:48:11 [error] 2825#2825: *8 NAXSI_FMT: ip=10.0.0.2&server=zk.in&uri=/wp-admin/load-styles.php&learning=0&vers=0.55rc2&total_processed=55&total_blocked=1&block=1&cscore0=$XSS&score0=8&zone0=ARGS|NAME&id0=1310&var_name0=load[]&zone1=ARGS|NAME&id1=1311&var_name1=load[], client: 10.0.0.2, server: www.zk.in, request: "GET /wp-admin/load-styles.php?c=1&dir=ltr&load%5B%5D=dashicons,admin-bar,common,forms,admin-menu,dashboard,list-tables,edit,revisions,media,themes,about,nav-menus,widgets,site-icon,&load%5B%5D=l10n,buttons,wp-auth-check&ver=4.5.3 HTTP/1.1", host: "zk.in", referrer: "http://zk.in/wp-admin/"
2016/06/28 03:48:40 [error] 2825#2825: *8 NAXSI_FMT: ip=10.0.0.2&server=zk.in&uri=/wp-admin/load-styles.php&learning=0&vers=0.55rc2&total_processed=91&total_blocked=2&block=1&cscore0=$XSS&score0=8&zone0=ARGS|NAME&id0=1310&var_name0=load[]&zone1=ARGS|NAME&id1=1311&var_name1=load[], client: 10.0.0.2, server: www.zk.in, request: "GET /wp-admin/load-styles.php?c=1&dir=ltr&load%5B%5D=dashicons,admin-bar,common,forms,admin-menu,dashboard,list-tables,edit,revisions,media,themes,about,nav-menus,widgets,site-icon,&load%5B%5D=l10n,buttons,wp-auth-check&ver=4.5.3 HTTP/1.1", host: "zk.in", referrer: "http://zk.in/wp-admin/index.php"
2016/06/28 03:48:43 [error] 2825#2825: *8 NAXSI_FMT: ip=10.0.0.2&server=zk.in&uri=/wp-admin/load-styles.php&learning=0&vers=0.55rc2&total_processed=94&total_blocked=3&block=1&cscore0=$XSS&score0=8&zone0=ARGS|NAME&id0=1310&var_name0=load[]&zone1=ARGS|NAME&id1=1311&var_name1=load[], client: 10.0.0.2, server: www.zk.in, request: "GET /wp-admin/load-styles.php?c=1&dir=ltr&load%5B%5D=dashicons,admin-bar,common,forms,admin-menu,dashboard,list-tables,edit,revisions,media,themes,about,nav-menus,widgets,site-icon,&load%5B%5D=l10n,buttons,wp-auth-check&ver=4.5.3 HTTP/1.1", host: "zk.in", referrer: "http://zk.in/wp-admin/media-new.php"
2016/06/28 03:48:47 [error] 2825#2825: *8 NAXSI_FMT: ip=10.0.0.2&server=zk.in&uri=/wp-admin/load-styles.php&learning=0&vers=0.55rc2&total_processed=99&total_blocked=4&block=1&cscore0=$XSS&score0=8&zone0=ARGS|NAME&id0=1310&var_name0=load[]&zone1=ARGS|NAME&id1=1311&var_name1=load[], client: 10.0.0.2, server: www.zk.in, request: "GET /wp-admin/load-styles.php?c=1&dir=ltr&load%5B%5D=dashicons,admin-bar,buttons,media-views,common,forms,admin-menu,dashboard,list-tables,edit,revisions,media,themes,about,nav-menu&load%5B%5D=s,widgets,site-icon,l10n,wp-auth-check&ver=4.5.3 HTTP/1.1", host: "zk.in", referrer: "http://zk.in/wp-admin/post-new.php"
`

this is my error log sir site is not loading. it is not learning mode.

**Comment by prithamgit** [comment]
i'm using this default whitelist  [wordpress.rules](https://github.com/nbs-system/naxsi-rules/blob/master/wordpress.rules)

**Comment by Doemela** [comment]
Add this to wordpress whitelist:
BasicRule wl:1310,1311 "mz:$URL:/wp-admin/load-styles.php|$ARGS_VAR:load[]|NAME|ARGS";

But I see allot of other errors due to plugins or deactivate those or make extra whitelist rules for them

Set naxsi on learning, use the blog for a while then do:
Install elasticsearch
cd /path/to/naxsi/nxapi
service elasticsearch start
./nxtool.py --config=/path/to/naxsi/nxapi/nxapi/nxapi.json --files=/var/log/nginx/error.log.of.domain
./nxtool.py -c nxapi.json  -x -s zk.in
./nxtool.py -c nxapi.json -s zk.in -f --slack --colors > wl.txt && sed -n '/BasicRule  wl.*;/p' wl.txt > wl-WP.txt && rm wl.txt

In wl-WP.txt you will see whitelist rules add the ones for the plugins you use to the whitelist wordpress.rules

**Comment by prithamgit** [comment]
thank you verymuch for your help sir. add this rule
BasicRule wl:1310,1311 "mz:$URL:/wp-admin/load-styles.php|$ARGS_VAR:load[]|NAME|ARGS";
i set the naxsi to learning mode sir
please tell me where can i get elasticseach rpm?
i tryed yum install elasticsearch it says No package elasticsearch available.


i installed naxsi-nginx with this rpm https://www.ulyaoth.net/resources/naxsi-nginx-stable.18/
i couldn't find the pasth of nxapi.. please help me sir

**Comment by prithamgit** [comment]
i found this guide  [here](http://www.greenacorn-websolutions.com/nginx/securing-your-app-with-nginx-naxsi.php) 
wget https://naxsi.googlecode.com/files/nx_util-1.0.tgz
tar -zxf nx_util-1.0.tgz
cd nx_util-1.0/nx_util
python nx_util.py -c nx_util.conf -l /var/log/virtualmin/zk.in_nginx_error_log -o
then after waiting for some time got this output
`########### Optimized Rules Suggestion ##################
# total_count:3724402 (133300.0%), peer_count:1 (50.0%) | open square backet ([)                                                                                        , possible js
BasicRule wl:1310 "mz:BODY|NAME";
# total_count:3654552 (130800.0%), peer_count:1 (50.0%) | close square bracket (                                                                                        ]), possible js
BasicRule wl:1311 "mz:BODY|NAME";
# total_count:11176 (400.0%), peer_count:1 (50.0%) | close square bracket (]), p                                                                                        ossible js
BasicRule wl:1311 "mz:BODY";
# total_count:11176 (400.0%), peer_count:1 (50.0%) | open square backet ([), pos                                                                                        sible js
BasicRule wl:1310 "mz:BODY";
# total_count:11176 (400.0%), peer_count:1 (50.0%) | comma
BasicRule wl:1015 "mz:BODY";
# total_count:11176 (400.0%), peer_count:1 (50.0%) | equal sign in var, probable                                                                                         sql/xss
BasicRule wl:1009 "mz:BODY";
# total_count:11176 (400.0%), peer_count:1 (50.0%) | semicolon
BasicRule wl:1008 "mz:BODY";
# total_count:11176 (400.0%), peer_count:1 (50.0%) | double quote
BasicRule wl:1001 "mz:BODY";
# total_count:8382 (300.0%), peer_count:1 (50.0%) | html close tag
BasicRule wl:1303 "mz:BODY";
# total_count:8382 (300.0%), peer_count:1 (50.0%) | html open tag
BasicRule wl:1302 "mz:BODY";
# total_count:8382 (300.0%), peer_count:1 (50.0%) | open parenthesis, probable s                                                                                        ql/xss
BasicRule wl:1010 "mz:BODY";
# total_count:5588 (200.0%), peer_count:1 (50.0%) | mysql comment (#)
BasicRule wl:1016 "mz:BODY";
# total_count:5588 (200.0%), peer_count:1 (50.0%) | simple quote
BasicRule wl:1013 "mz:BODY";
# total_count:5588 (200.0%), peer_count:1 (50.0%) | close parenthesis, probable                                                                                         sql/xss
BasicRule wl:1011 "mz:BODY";
# total_count:5588 (200.0%), peer_count:1 (50.0%) | mysql comment (--)
BasicRule wl:1007 "mz:BODY";
# total_count:5588 (200.0%), peer_count:1 (50.0%) | mysql keyword (&&)
BasicRule wl:1006 "mz:BODY";
# total_count:5588 (200.0%), peer_count:1 (50.0%) | mysql keyword (|)
BasicRule wl:1005 "mz:BODY";
# total_count:5588 (200.0%), peer_count:1 (50.0%) | mysql comment (*/)
BasicRule wl:1004 "mz:BODY";
# total_count:5588 (200.0%), peer_count:1 (50.0%) | mysql comment (/*)
BasicRule wl:1003 "mz:BODY";
# total_count:5588 (200.0%), peer_count:1 (50.0%) | sql keywords
BasicRule wl:1000 "mz:BODY";
# total_count:2794 (100.0%), peer_count:1 (50.0%) | empty POST
BasicRule wl:16 "mz:BODY";
# total_count:24 (0.86%), peer_count:1 (50.0%) | close square bracket (]), possi                                                                                        ble js
BasicRule wl:1311 "mz:$URL:/wp-admin/load-styles.php|$ARGS_VAR:load[]|NAME";
# total_count:24 (0.86%), peer_count:1 (50.0%) | open square backet ([), possibl                                                                                        e js
BasicRule wl:1310 "mz:$URL:/wp-admin/load-styles.php|$ARGS_VAR:load[]|NAME";
# total_count:20 (0.72%), peer_count:1 (50.0%) | html open tag
BasicRule wl:1302 "mz:$URL:/|$ARGS_VAR:a";
# total_count:7 (0.25%), peer_count:1 (50.0%) | sql keywords
BasicRule wl:1000 "mz:$URL:/wp-admin/options.php|$BODY_VAR:ubermenu_main[style_s                                                                                        ubmenu_dropshadow_opacity]|NAME";
# total_count:7 (0.25%), peer_count:1 (50.0%) | sql keywords
BasicRule wl:1000 "mz:$URL:/wp-admin/options.php|$BODY_VAR:ubermenu_main[dropdow                                                                                        n_within_mega]|NAME";
# total_count:4 (0.14%), peer_count:1 (50.0%) | http:// scheme
BasicRule wl:1100 "mz:$URL:/wp-admin/nav-menus.php|BODY";
# total_count:4 (0.14%), peer_count:1 (50.0%) | comma
BasicRule wl:1015 "mz:$URL:/wp-admin/load-scripts.php|$ARGS_VAR:load[]";
# total_count:3 (0.11%), peer_count:1 (50.0%) | html close tag
BasicRule wl:1303 "mz:$URL:/|$ARGS_VAR:a";
`

**Comment by Doemela** [comment]
You can download rpm here https://www.elastic.co/downloads/elasticsearch
path of nxapi is in the git u cloned

**Comment by prithamgit** [comment]
i'm just beginner i don't much about this sir can i use nxutil instead of nxapi to create whitelist rules? 
i used nzutil it gave me output of some whitelist rules [here](http://pastebin.com/raw/2RKQAcS1)

**Comment by Doemela** [comment]
Add id 1015 to:
BasicRule wl:1310,1311,1015 "mz:$URL:/wp-admin/load-styles.php|$ARGS_VAR:load[]|NAME|ARGS";

These for ubermenu
BasicRule wl:1000 "mz:$URL:/wp-admin/options.php|$BODY_VAR:ubermenu_main[style_submenu_dropshadow_opacity]|NAME";
BasicRule wl:1000 "mz:$URL:/wp-admin/options.php|$BODY_VAR:ubermenu_main[dropdown_within_mega]|NAME";

This for nav-menus
BasicRule wl:1100 "mz:$URL:/wp-admin/nav-menus.php|BODY";

You can make new post?

**Comment by prithamgit** [comment]
yes sir now i can make new posts :) 
so i noneed elasticsearch for now?

**Comment by Doemela** [comment]
elasticsearch is only needed to generate whitelist tools you can stop that proces

**Comment by prithamgit** [comment]
thanks you saved me :)

**Comment by buixor** [comment]
thanks @Doemela for helping ;)
