### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by sous-studio** [nbs-system/naxsi#297]
Hey folks!

I get elasticsearch, it works alright. I collect data and make output like this:
./nxtool.py -c nxapi.json -f --colors  --slack>whiterules.all

Now stupid question: how do I filter all these rules by 'peer', or in other words, leave only those for requests made from a particular (my) IP?

Thanks!

**Comment by sous-studio** [comment]
Found an answer:

./nxtool.py -c nxapi.json -f --filter 'ip YOURIP'

Folks, it's counter-intuitive to have 'peers' displayed in the output, yet --filter 'peers IP' is not working. I'd suggest removing peers term and replacing it by ip, so people don't get lost between two.

**Comment by buixor** [comment]
Hello,

thanks for the suggestion, we are rewritting nxtool and will take this into account :)

cheers !
