### ISSUE TITLE
nxapi/nxtool.py bug?

### ISSUE THREAD

**Issue by sous-studio** [nbs-system/naxsi#298]
Hey!

What I did:
1. copied nxapi.json to 123.json
2. replaced "index" : "nxapi" with "index" : "123.json"
3. created an index on elasticsearch curl -XPUT 'http://localhost:9200/123/'
3. launched parsing with ./nxtool.py -c 123.json --files=/nginx/123.log
4. run generator with ./nxtool.py -c 123.json -f --slack
And nothing.
5. ./nxtool.py -c 123.json -x
# size :1000
# Whitelist(ing) ratio :
# Top servers :
# Top URI(s) :
# Top Zone(s) :
# Top Peer(s) :
Nothing again.
6. I did curl -XPOST "http://localhost:9200/123/events/_search?pretty" -d '{}'  and it returns events, so the problem is not in elasticsearch.

Is this a bug or am I missing something?

Naxsi HTTP2 latest branch

**Comment by buixor** [comment]
Hello,

2. replaced "index" : "nxapi" with "index" : "123.json"

I think you mean "index" : "123" ?

**Comment by sous-studio** [comment]
Yes, sorry for mistyping here. Of course "index" : "123".
So what am I missing?

**Comment by buixor** [comment]
Are you using nxtool to inject data into ES ? I always used the default index myself :)
If it is the case I can reproduce it and try out !

**Comment by sous-studio** [comment]
Sorry, haven't noticed your answer before. Yes, I use nxtool to insert data into ES, but tried non-default numeric index and it failed.

**Comment by buixor** [comment]
Hello, can you check from master now ? 	#e2265e6 should address the issue :)

**Comment by buixor** [comment]
ping @sous-studio :)

**Comment by buixor** [comment]
closing, @sous-studio feel free to re-open if you have time to check this :)
