### ISSUE TITLE
Fail2ban failregex for server with multidomains

### ISSUE THREAD

**Issue by Doemela** [nbs-system/naxsi#299]
WIth failregex = NAXSI_FMT: ip=<HOST> on a server with several domains/sites when LearningMode; is set it will ban, maybe beter set is as below.

I have set in /etc/fail2ban/filter.d/nginx-naxsi.conf

`[INCLUDES]`
`before = common.conf`
`[Definition]`
`failregex = NAXSI_FMT: ip=<HOST>&server=.*&uri=.*&learning=0`
`ignoreregex =`

Now fail2ban won't ban when LearningMode; is set.

**Comment by buixor** [comment]
You referring to this ? https://github.com/nbs-system/naxsi/wiki/A-fail2ban-profile-for-Naxsi

If so, you are right, this was written *before* the learning flag was included within NAXSI_FMT :)

**Comment by Doemela** [comment]
> You referring to this ? https://github.com/nbs-system/naxsi/wiki/A-fail2ban-profile-for-Naxsi

>If so, you are right, this was written before the learning flag was included within NAXSI_FMT :)

@buixor Yes

**Comment by buixor** [comment]
I'm editing the wiki page (btw notice ! new wiki) and closing.

@Doemela don't hesitate to edit the wiki directly, it's open for edit on purpose :)
