### ISSUE TITLE
naxsi as nginx dynamic module

### ISSUE THREAD

**Issue by ufth** [nbs-system/naxsi#300]
Hi! Do you have any plans to provide NAXSI as a dynamic module?

https://www.nginx.com/blog/dynamic-modules-nginx-1-9-11/
https://www.nginx.com/resources/wiki/extending/converting/

**Comment by buixor** [comment]
Hi,
provide ? nope
can naxsi be built and used as a dynamic module ? yes (confirmed with 0.54 & later)
