### ISSUE TITLE
is the drupal.rules incorrect?

### ISSUE THREAD

**Issue by zzhclare** [nbs-system/naxsi#301]
**BasicRule wl:1310,1311 "mz:$URL:/|$ARGS_VAR_X:^destination|NAME";**
I find this sentence at line 33 in drupal.rules and I think it's totally opposite to the 
 document.
here is the warning in the document.
**mz:$ARGS_VAR_X:^foo$|$URL:/x or mz:$URL_X:/foo|$ARGS_VAR:x are wrong.**
By the way, I want to know whether all kinds of collocation of static and regex cannot show in matchzones?
ie.

1. mz:$URL:/|$BODY_VAR_X:^fields|NAME;
2. mz:$URL:/|$URL_X:regex;
3. mz:$ARGS_VAR:string|$HEADERS_VAR_X:regex;
4. mz:$BODY_VAR_X:regex|$BODY_VAR:string;

if all of them are wrong?
I also want to know whether as long as an action matches the rules , it will be logged regardless of I setting the checkrule or not?
another question..Is 'BasicRule "str:string" "mz:$URL_X:regex";' or 'BasicRule "rx:regex" "mz:$URL:/";' correct?

**Comment by Doemela** [comment]
A whitelist can't mix _X elements with _VAR or $URL items. ie:
mz:$URL:/|$BODY_VAR_X:^fields|NAME;
must be:
mz:$URL_X:^/$|$BODY_VAR_X:^fields$|NAME;

**Comment by zzhclare** [comment]
Thank for your answer. Do you know the last two questions answers?

**Comment by Doemela** [comment]
CheckRules instruct naxsi to take an action, so if action matches a rule it will do  (LOG, BLOCK, DROP, ALLOW) 
Last question has same answer I already gave

**Comment by buixor** [comment]
thanks @Doemela for answering these ones :)
I'm closing the issue as it is solved.

@zzhclare : when you have issues related to naxsi-rules repository, would you mind opening those in the naxsi-rules project ? the dev team has very little/no real involvment into those :)

cheers !
