### ISSUE TITLE
General question about naxsi

### ISSUE THREAD

**Issue by pimperator** [nbs-system/naxsi#302]
Hi Guys,

I am new to naxsi and right now I am trying to generate rules for an API with a hand full of possible URL-Paths and repeating headers. In detail there are 17 possible paths; some of them support posting json-bodies.
This means my Webapp has limited variation. Only a few paths with changing patterns and fixed headers, where only some few things are changing.
Due to having a lot of voodoo in headers I am unable to use nxapi. It is ignoring headers completely. :(

I tried to use the naxsi_core.rules available on naxsi’s github repo but it isn’t satisfiing my requirements. These are: Block everything and allowing a hand full of paths with specific headers.

Of course naxsi blocks everything with absent MainRule rules but this is due to misconfiguration as naxsi tells in extended logging mode. So this is not an option for me

Right now I have some questions but first of all I am trying to describe my setup.

I generated my own core-rules which have to deny everything. It looks like this:
```
MainRule "msg:block All URLs"      "rx:.*"  "mz:URL"                  "s:$GENERIC:1" id:1234;
MainRule "msg:block all Headers"   "rx:.*"  "mz:HEADERS"              "s:$GENERIC:1" id:1235;
MainRule "msg:block all Arguments" "rx:.*"  "mz:ARGS"                 "s:$GENERIC:1,BLOCK“ id:1236;
```

The header of my naxsi.rules file looks like this:
```
LearningMode;
SecRulesEnabled;

CheckRule "$GENERIC >= 3" BLOCK;

DeniedUrl "/RequestDenied";
```

Then first I tried to whitelist for all paths like this
`BasicRule wl:2100 "str:myHeaderValue" "mz:$URL:/path/to/interface|$HEADER_VAR:myHeader";`

Unfortunately this only works for one header, so I thought this would be better:
`BasicRule wl:2101 "rx:myHeader1Value|myHeader2Value|myBodyText" "mz:$URL:/path/to/interface|$HEADER_VAR:myHeader1|$HEADER_VAR:myHeader2|$BODY";`
This means that myHeader1 can have either the value "myHeader1Value" OR "myHeader2Value" OR my Body would fit and that is not good. Yet, I still have some more headers I want to check. It’s about six custom headers which MUST fit and no arguments after `URL`.

**Is there any better way to declare whitelists and to verify that some more Values match (not OR but AND, i.e. `URL` AND `$HEADER`s AND `BODY`)?**
This here works
`BasicRule wl:2101 "rx:value1|value2" "mz:$URL:/path/to/url|$HEADERS_VAR_X:header1|header2";`
but either the proper way
`curl -I -X POST -d "bonjours ca va" --Header "header1: value1" --Header "header2: value2" http://blog.hk24.net/path/to/url`
and the improper ways 
```
curl -I -X POST -d "bonjours ca va" --Header "header1: value2" --Header "header2: value2" http://blog.hk24.net/path/to/url
curl -I -X POST -d "bonjours ca va" --Header "header1: value1" --Header "header2: value1" http://blog.hk24.net/path/to/url
curl -I -X POST -d "bonjours ca va" --Header "header1: value2" --Header "header2: value1" http://blog.hk24.net/path/to/url
```
do work :( AND I can't verify the body for proper json. But according to the documentation it is the only way to combine more cases into one whitelist.

**Why does this here not work?**
`BasicRule wl:2102 "str:/path/to/url" "mz:$URL";`
OR 
`BasicRule wl:2103 "mz:$URL:/path/to/url";`

**Why do I have to use this instead and which one is better:**
`BasicRule wl:2104 "str:/path/to/url" "mz:$URL|URL";`
OR 
`BasicRule wl:2105 "mz:$URL:/path/to/url|URL";`

With my requirements mentioned above I decided to go a different way, so I switched to this setup:
core rules as mentioned above

location/vhost based rules:
```
LearningMode;
SecRulesEnabled;

CheckRule "$GENERIC >= 3" BLOCK;
CheckRule "$FUBAR_A >= 4“ ALLOW;
CheckRule "$FUBAR_B >= 6“ ALLOW;

BasicRule  "str:hostname.domain.tld" "msg:this is my host header" "mz:$HEADERS_VAR:host" "s:$VHOST:1,$FUBAR_A:1,$FUBAR_B:1,$FUBAR_C:1,$GENERIC:-1" id:3210;
BasicRule  "str:https://hostname.domain.tld" "msg:this is my origin header" "mz:$HEADERS_VAR:origin" "s:$VHOST:1,$FUBAR_A:1,$FUBAR_B:1,$FUBAR_C:1,$GENERIC:-1" id:3211;

#fubar_a
BasicRule  "rx:^\/path\/to\/([0-9]+)\/url$" "msg:this is my fubar_A url" "mz:$URL|URL" "s:$VHOST:1,$FUBAR_A:1,$GENERIC:-1" id:3220;
BasicRule  "rx:^https\:\/\/hostname\.domain\.tld\/path\/to\/([0-9]+)\/url$" "msg:this is my referer header" "mz:$HEADERS_VAR:referer" "s:$VHOST:1,$FUBAR_A:1,$FUBAR_C:1,$GENERIC:-1" id:3221;

#fubar_a
BasicRule  "str:/path/to/%2Fother" "msg:this is my fubar_B url" "mz:$URL|URL" "s:$VHOST:1,$FUBAR_A:1,$GENERIC:-1" id:3230;
BasicRule  "str:https://hostname.domain.tld/path/to/%2Fother" "msg:this is my referer header" "mz:$HEADERS_VAR:referer" "s:$VHOST:1,$FUBAR_B:1,$FUBAR_C:1,$GENERIC:-1" id:3231;
BasicRule  "rx:\{(([a-z]+): \"([a-z0-9]+)\,)+\}" "msg:checking for valid json" "mz:$BODY" "s:$VHOST:1,$FUBAR_B:2,$GENERIC:-1" id:3232;
```
This solution has the advantage that 
- $GENERAL will always match if it is not decreased below 3. So every invalid Request will be blocked
- I can combine weighted Rules via boolean AND and allow specific requests to access my api

So now my Questions on this solution:
- if $GENERIC has value 3 and $FUBAR_A has value 4 for one specific request. Which one wins? Will that request be BLOCKed or ALLOWed?
- With every match I decrease $GENERIC by one. Is it a problem when it becomes negative?
- Rule 3211 never matches. I assume it is because of ':' in str. How do I escape it?
- Rule 3230 seems to be detected as '/path/to/other'. Is '%' also not allowed? It is '%2F' means '/' and is often part of my urls (and no, I can't fix that to a proper URL)
- Is there a better way to allow specific paths ?

Another basic question is: how do I change naxsi to log into error.log?

Thanks for any ideas and help

Pimp

**Comment by blotus** [comment]
I'm not sure to understand what you're trying to achieve, so my response may be completely wrong :)                                                                                                                                            
                                                                                                                                                                                                                                               
If you want to enforce the content of some variables, i would probably use negative rules :                                                                                                                                                    
```                                                                                                                                                                                                                             
BasicRule negative "rx:\d+" "mz:$HEADERS_VAR:header1|$URL:/foobar" "s:DROP" id:4242;
```                                                                                                                                                                                                                                               
This rule will drop (block the request even while in learning mode) all request having a HTTP header "header1" with a value that is not a number on the URL /foobar.
 
Naxsi knows how to parse JSON (only if the content-type is application/json), so you can also enforce the validity of the JSON body : 
```
BasicRule negative "str:my_var_content" "mz:$BODY_VAR:my_json_key" "s:DROP" id:4243;
```
You can't change naxsi log file, it will always log to the file specified in error_log.

**Comment by pimperator** [comment]
Hi Blotus,

thanks a lot for your answer;
in part you answered my question.

**First question**
What happens if I set up these two rules:
```
BasicRule negative "str:foor" "mz:$HEADERS_VAR:header1|$URL:/foobar" "s:DROP" id:4242;
BasicRule negative "str:bar" "mz:$HEADERS_VAR:header2|$URL:/foobar" "s:DROP" id:4242;
```
Which one wins if I do the following:
`curl --Header "header1: foo" http://host.tld/foobar`
or even
`curl --Header "header3: anything" http://host.tld/foobar`
According to the space in between my ears both curl-Requests will not be dropped.

**Second question**
I have large json-Bodies. Is it sufficient for naxsi to match only for one rule to drop the request?
How does naxsi act if none of these below match in the body (ALLOW|BLOCK ?) ?
```
BasicRule negative "str:my_var_content1" "mz:$BODY_VAR:my_json_key1" "s:DROP" id:4245;
BasicRule negative "rx:([0-9]{8})" "mz:$BODY_VAR:my_json_key2" "s:DROP" id:4246;
BasicRule negative "rx:true|false" "mz:$BODY_VAR:my_json_key3" "s:DROP" id:4247;
BasicRule negative "str:my_var_content4" "mz:$BODY_VAR:my_json_key4" "s:DROP" id:4248;
```
My appologies for asking such dumb questions but I begin to get blind because doing this for the last month.

**Comment by pimperator** [comment]
another question is:
Why is this here never matching on "str"? I suppose it is because of ":". How do I escape it?
`BasicRule  "str:https://hostname.domain.tld" "msg:this is my origin header" "mz:$HEADERS_VAR:origin" "s:$VHOST:1,$FUBAR_A:1,$FUBAR_B:1,$FUBAR_C:1,$GENERIC:-1" id:3211;`

**Comment by buixor** [comment]
Hello,

For me it seems to be working (from master).

from naxsi_src:
```
make re
```
in /tmp/naxsi_ut/nginx.conf :

```
location / {
  BasicRule "str:https://hostname.domain.tld" "msg:this is my origin header" "mz:$HEADERS_VAR:origin" "s:DROP" id:3211;
   LearningMode;
```

`curl -H "origin: https://hostname.domain.tld"  127.0.0.1:4242/azaaa`

`2016/07/26 09:52:29 [error] 3680#0: *1 NAXSI_FMT: ip=127.0.0.1&server=127.0.0.1&uri=/azaaa&learning=1&vers=0.55rc2&total_processed=1&total_blocked=1&block=0&zone0=HEADERS&id0=3211&var_name0=origin, client: 127.0.0.1, server: localhost, request: "GET /azaaa HTTP/1.1", host: "127.0.0.1:4242"`

**Comment by buixor** [comment]
Regarding your first question :

```
BasicRule negative "str:foor" "mz:$HEADERS_VAR:header1|$URL:/foobar" "s:DROP" id:4241;
BasicRule negative "str:bar" "mz:$HEADERS_VAR:header2|$URL:/foobar" "s:DROP" id:4242;
```

#1 blocked  ('foor' is not found, thus rule 4241 matches)
```
$ curl -I --Header "header1: foo" http://127.0.0.1:4242/foobar
HTTP/1.1 418 
```

#2 not blocked (no rule applies to head3)
```
$ curl -I --Header "header3: anything" http://127.0.0.1:4242/foobar
HTTP/1.1 404 Not Found
```
