### ISSUE TITLE
nxtool filter and -g option works great when running from nxapi folder but not from /usr/local/bin

### ISSUE THREAD

**Issue by cryptofuture** [nbs-system/naxsi#305]
nxtool filter and `-g` option works great when running from nxapi folder but not from `/usr/local/bin`.  
When I run nxtool  filter or `-g`installed from `setup.py install` nxtool always gives 
`No hits for this filter`. Or gives empty files after -g run. Beside `-x` and files import works fine. I have no idea why this happens. But I'm pretty sure setup.py finished correctly. Lose a bit a lot time to figure this out. 
You could find more logs in survey, but I don't think that it worth repost standard nxtool output here. This is not definitely a bug in nxtool, but probably something in setup.py.   
Maybe better remove setup.py and write run more detail run instructions. I can help with it.

**Comment by buixor** [comment]
Hello,

I didn't manage to reproduce it.
Can you provide a bit more details ? (I just tried from a fresh install and it seems to run)

**Comment by buixor** [comment]
closing without reply, don't hesitate to re-open @cryptofuture if you can reproduce and/or have extra info :)
