### ISSUE TITLE
Blocking a request to a specific path doesn't work

### ISSUE THREAD

**Issue by piefox** [nbs-system/naxsi#307]
Dear naxsi team,

I'm trying to block all traffic which target an unknow API. To achieve that, i plan to use negative MainRule like this. I've tried to block what i want to allow and next i'll put negative keyword:

`MainRule "rx:.*" "msg:test" "mz:ARGS|$URL_X:/myapi" "s:DROP" id:99999; `
-> doesn't block http://10.170.171.49/myapi/test and will match with all /everythings/things?all

`MainRule "rx:.*" "msg:test" "mz:$URL_X:/myapi" "s:DROP" id:99999; `
-> nginx error when restart

Is there a way to block api path like this ( /myapi/* ) ?

Tested with Naxsi 0.55rc2.

Regards,

**Comment by buixor** [comment]
Hi,

Please look at : 
https://github.com/nbs-system/naxsi/wiki/rules-examples#blocking-dangerous-directories

**Comment by piefox** [comment]
Hello,

Thank you for response,

I've already tried: 
`MainRule "str:/magmi/" "msg:Access to magmi folder" "mz:URL" "s:$UWA:8" id:42000400;`

It block 127.0.0.1/magmi/ -> OK
but also 127.0.0.1/test/magmi/test.html 
and i want to block only the root subfolder.

However, i found a workaround to do that with:

`MainRule negative id:4242 "rx:^\/(onefolder|anotherfolder)\/" "msg:allow only the authorized subfolders" "mz:URL" s:DROP;`
