### ISSUE TITLE
Can't get example config to work

### ISSUE THREAD

**Issue by rhoerbe** [nbs-system/naxsi#310]
I could not get the [example config](https://github.com/nbs-system/naxsi/wiki/naxsi-setup) working on centos7/nginx-1.8.1/naxsi-0.54. URLs that should be filtered are not filtered. The problem is reproducible with this command:

   docker run -it --rm -u nginx02 rhoerbe/nginx02 /start_test.sh

And this is the corresponding [Dockerfile](https://github.com/identinetics/docker-nginx/blob/master/Dockerfile).

I am not sure about the proper place to ask for support for naxsi - I tried [serverfault](https://serverfault.com/questions/797753/nginx-naxsi-rules-not-catching-request-that-should-raise-an-error) but did not get an answer.

**Comment by blotus** [comment]
Hi,

Seems that your rule (or you request) is wrong.
Your rule will try to match testnaxsitest in the HTTP headers, but your request put testnaxsitest in a GET parameter, so naxsi wont block the request as the zones don't match.

For support, the best is to come on IRC on #naxsi on freenode.

**Comment by rhoerbe** [comment]
The problem was that naxsi does not trigger on = rules (like location = /)

Thank your for helping
