### ISSUE TITLE
throw a warning when naxsi is enabled in an internal location

### ISSUE THREAD

**Issue by buixor** [nbs-system/naxsi#311]
naxsi does not parse requests to internal location (to avoid loops and other weird things).
However it would be cool to throw a warning when this happens.

**Comment by buixor** [comment]
The warning will be thrown **once** at the first request that hits the internal location.
I could do this at every request, but it's - at most - just a clever way to fill up logs ?

Sadly, we can't do it at config time :/

**Comment by jvoisin** [comment]
- How can one issue a request to an internal location?
- What can happen if one can issue such a request?
- What kind of decision would the admin take upon such a notification?

**Comment by buixor** [comment]
Naxsi will simply not treat a request that is tagged as "internal" (because of re-entrant aspect of nginx).
So it means the admin must configure naxsi so that the request is processed before the request is tagged as internal. It might be changed in the future to allow an admin to specifically allow this behavior. For now, we just want to throw a warning in the logs.

**Comment by buixor** [comment]
Commited a fix attempt a548d60 let's see :)
