### ISSUE TITLE
Naxsi wrongly triggering id 11 for text/xml content-type

### ISSUE THREAD

**Issue by danlsgiga** [nbs-system/naxsi#312]
Naxsi is triggering the id 11 (unknown content-type) for an internal application that uses text/xml as the default content-type. For some reason Naxsi is not handling it correctly.

**Comment by buixor** [comment]
Hello,
It is the expected behaviour :) Naxsi doesn't know (yet?) how to parse xml, so it fires unknown content-type internal rule

**Comment by danlsgiga** [comment]
Ah... thanks!! Might be a good idea to have this piece of information on the docs! ;)
