### ISSUE TITLE
Configuration file parsing issue

### ISSUE THREAD

**Issue by L3V14TH4N** [nbs-system/naxsi#315]
Hii,

I'm not getting start nxtool.py

![image](https://cloud.githubusercontent.com/assets/6493983/18552570/559221ba-7b33-11e6-8c2f-92f6be7c8b73.png)

and when you run this command "./nxtool.py -c nxapi.json --files=/var/log/nginx/error.log" It appears the following:

![image](https://cloud.githubusercontent.com/assets/6493983/18552646/b270367e-7b33-11e6-8720-d40c2aa0a349.png)

what is this error?

**Comment by blotus** [comment]
It seems that you try to use SSL to connect to elasticsearch.
Can you try to set use_ssl in nxapi.json to False ?

**Comment by L3V14TH4N** [comment]
The version of Elasticsearch is 2.4

```
[root@naxsi nxapi]# cat nxapi.json
{
"elastic" : {
 "host" : "127.0.0.1:9200",
 "use_ssl" : "False",
 "index" : "nxapi",
 "doctype" : "events",
 "default_ttl" : "7200",
 "max_size" : "1000",
 "version" : "2"
},
"syslogd": {
 "host" : "0.0.0.0",
 "port" : "51400"
},
"global_filters" : {
 "whitelisted" : "false"
},
"global_warning_rules" : {
 "rule_ip" : ["<=", 10 ],
 "global_rule_ip_ratio" : ["<", 5]
},
"global_success_rules" : {
 "global_rule_ip_ratio" : [">=", 10],
 "rule_ip" : [">=", 10]
},
"global_deny_rules" : {
 "global_rule_ip_ratio" : ["<", 2]
},
"naxsi" : {
 "rules_path" : "/etc/nginx/naxsi_core.rules",
 "template_path" : [ "tpl/"],
 "geoipdb_path" : "nx_datas/country2coords.txt"
},
"output" : {
 "colors" : "true",
 "verbosity" : "5"
}
}
```

**Comment by L3V14TH4N** [comment]
The problem still persists.

./nxtool.py -c nxapi.json -x

`# size :1000
No handlers could be found for logger "elasticsearch"
Traceback (most recent call last):
  File "./nxtool.py", line 274, in <module>
    translate.fetch_top(cfg.cfg["global_filters"], "whitelisted", limit=2)
  File "/usr/local/src/naxsi/nxapi/nxapi/nxtransform.py", line 550, in fetch_top
    res = self.search(esq)
  File "/usr/local/src/naxsi/nxapi/nxapi/nxtransform.py", line 619, in search
    x = self.es.search(index=self.cfg["elastic"]["index"], doc_type=self.cfg["elastic"]["doctype"], body=esq)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 70, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 429, in search
    params=params, body=body)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 274, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 51, in perform_request
    raise ConnectionError('N/A', str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError([Errno 2] No such file or directory) caused by: SSLError([Errno 2] No such file or directory)`

**Comment by blotus** [comment]
I've just pushed a new default configuration that should correct your error (use_ssl should be a JSON true or false, not a string).

**Comment by L3V14TH4N** [comment]
It should stay that way?

```
{
"elastic" : {
 "host" : "127.0.0.1:443",
 "use_ssl" : "True",
 "host" : "127.0.0.1:9200",
 "use_ssl" : "False",
 "index" : "nxapi",
 "doctype" : "events",
 "default_ttl" : "7200",
 "max_size" : "1000",
 "version" : "2"
}
```

**Comment by blotus** [comment]
No, should be (based on your previous conf): 
```JSON
{
"elastic" : {
 "host" : "127.0.0.1:9200",
 "use_ssl" : false,
 "index" : "nxapi",
 "doctype" : "events",
 "default_ttl" : "7200",
 "max_size" : "1000",
 "version" : "2"
}
```

**Comment by L3V14TH4N** [comment]
Yeah!!! It worked!!
![image](https://cloud.githubusercontent.com/assets/6493983/18589665/21eb790e-7c02-11e6-9a48-079820b830fc.png)

Thanks!!
