### ISSUE TITLE
Kibana schedule (problem)

### ISSUE THREAD

**Issue by L3V14TH4N** [nbs-system/naxsi#317]
Hello gentlemen!!!

I noticed that the Kibana is not updating as the current schedule of logs.. I generated logs on schedule 'x' and updates the current time 'y' i.e:
![image](https://cloud.githubusercontent.com/assets/6493983/18836380/2a6ab0aa-83d6-11e6-9837-819392645634.png)

in which have begotten the logs in 09:55am, but there appears in the Kibana 03:55am
As it is possible to correct this situation?

**Excuse me for my bad English ;)

**Comment by L3V14TH4N** [comment]
Another example:
![image](https://cloud.githubusercontent.com/assets/6493983/18845541/7102709e-83f8-11e6-91c8-8c5c0d7aadd2.png)

I marked two options.. Where the field "date" should come with data contained in field 1 (comments).

**Comment by buixor** [comment]
Hello,

properly some inconsistency in nxapi's date parsing. Can you show me some raw log format (especially the date part).

cheers,

**Comment by L3V14TH4N** [comment]
Ok,
**Nginx error log:**

`2016/09/26 14:16:30 [error] 3792#0: *1 NAXSI_FMT: ip=10.0.97.51&server=10.0.97.10&uri=/umbraco/surface/Common/Search&learning=0&vers=0.55rc2&total_processed=4&total_blocked=2&block=1&cscore0=$SQL&score0=8&zone0=ARGS&id0=1000&var_name0=term&zone1=ARGS&id1=1007&var_name1=term, client: 10.0.97.51, server: localhost, request: "GET /umbraco/surface/Common/Search?term=select,1,2,3--&id=4277 HTTP/1.1", host: "10.0.97.10", referrer: "http://10.0.97.10/testando//pagina-de-exemplo/?keywords=select,1,2,3--"`

**And parser content:**

```
{'date': '2016-09-26T13:47:26+03', 'events': [{'zone': 'ARGS', 'ip': '10.0.97.51', 'uri': '/testando/pagina-de-exemplo/', 'server': '10.0.97.10', 'content': '', 'var_name': 'keywords', 'coords': [104.195397, 35.86166], 'country': 'CN', 'date': '2016-09-26T13:47:26+03', 'id': '1000'}, {'zone': 'ARGS', 'ip': '10.0.97.51', 'uri': '/negocios/pagina-de-resultados/', 'server': '10.0.97.10', 'content': '', 'var_name': 'keywords', 'coords': [104.195397, 35.86166], 'country': 'CN', 'date': '2016-09-26T13:47:26+03', 'id': '1015'}]}
{'date': '2016-09-26T14:16:23+03', 'events': [{'zone': 'ARGS', 'ip': '10.0.97.51', 'uri': '/umbraco/surface/Common/Search', 'server': '10.0.97.10', 'content': '', 'var_name': 'term', 'coords': [104.195397, 35.86166], 'country': 'CN', 'date': '2016-09-26T14:16:23+03', 'id': '1000'}, {'zone': 'ARGS', 'ip': '10.0.97.51', 'uri': '/umbraco/surface/Common/Search', 'server': '10.0.97.10','content': '', 'var_name': 'term', 'coords': [104.195397, 35.86166], 'country': 'CN', 'date': '2016-09-26T14:16:23+03', 'id':'1015'}]}
{'date': '2016-09-26T14:16:30+03', 'events': [{'zone': 'ARGS', 'ip': '10.0.97.51', 'uri': '/umbraco/surface/Common/Search', 'server': '10.0.97.10', 'content': '', 'var_name': 'term', 'coords': [104.195397, 35.86166], 'country': 'CN', 'date': '2016-09-26T14:16:30+03', 'id': '1000'}, {'zone': 'ARGS', 'ip': '10.0.97.51', 'uri': '/umbraco/surface/Common/Search', 'server': '10.0.97.10','content': '', 'var_name': 'term', 'coords': [104.195397, 35.86166], 'country': 'CN', 'date': '2016-09-26T14:16:30+03', 'id': '1007'}]}
{'date': '2016-09-26T14:16:38+03', 'events': [{'zone': 'ARGS', 'ip': '10.0.97.51', 'uri': '/umbraco/surface/Common/Search', 'server': '10.0.97.10', 'content': '', 'var_name': 'term', 'coords': [104.195397, 35.86166], 'country': 'CN', 'date': '2016-09-26T14:16:38+03', 'id': '1000'}]}
{'date': '2016-09-26T14:16:43+03', 'events': [{'zone': 'ARGS', 'ip': '10.0.97.51', 'uri': '/testando/pagina-de-exemplo/', 'server': '10.0.97.10', 'content': '', 'var_name': 'keywords', 'coords': [104.195397, 35.86166], 'country': 'CN', 'date': '2016-09-26T14:16:43+03', 'id': '1007'}, {'zone': 'ARGS', 'ip': '10.0.97.51', 'uri': '/testando/pagina-de-exemplo/', 'server': '10.0.97.10', 'content': '', 'var_name': 'keywords', 'coords': [104.195397, 35.86166], 'country': 'CN', 'date': '2016-09-26T14:16:43+03', 'id': '1009'}, {'zone': 'ARGS', 'ip': '10.0.97.51', 'uri': '/testando/pagina-de-exemplo/', 'server': '10.0.97.10', 'content': '', 'var_name': 'keywords', 'coords': [104.195397, 35.86166], 'country': 'CN', 'date': '2016-09-26T14:16:43+03', 'id': '1013'}]}

```

**Comment by buixor** [comment]
Hello,

Can you provide me with the full log line and the associate dict so I can reproduce ?
From what I see, it is probably a time-zone parsing issues, because the library we use in python doesn't handle the +X in the time form.

Cheers,

**Comment by L3V14TH4N** [comment]
`Can you provide me with the full log line and the associate dict so I can reproduce? I have already sent the above topic.`

Yes, I have already sent the above topic.

**Comment by buixor** [comment]
Hello,

Sorry, I really mean one line of log, with the associated / resulting json document in kibana.

**Comment by L3V14TH4N** [comment]
**[root@naxsi nxapi]#** ./nxtool.py -c nxapi.json --files=/var/log/nginx/naxsi.log

`{'date': '2016-10-18T10:17:34+02', 'events': [{'zone': 'ARGS', 'ip': '10.0.97.10', 'uri': '/agencia-de-exemplo/pagina-de-exemplo/', 'server': '10.0.134.101', 'content': '', 'var_name': 'keywords', 'country': '', 'date': '2016-10-18T10:17:34+02', 'id': '1007'}`

Date in Kibana:
