### ISSUE TITLE
Not work white list BasicRule wl:0 "mz:BODY|$URL/XXX";

### ISSUE THREAD

**Issue by perec007** [nbs-system/naxsi#319]
In nginx config include basic_core.rules and string :
`BasicRule wl:0 "mz:BODY|$URL:/user/update";`

this not work. String in log:
```
2016/09/30 16:45:51 [error] 124135#0: *83148795 NAXSI_FMT: ip=178.223.213.223&server=server.site.com&uri=/user/update/1140805&learning=1&vers=0.55rc2&total_processed=20&total_blocked=1&block=1&cscore0=$SQL&score0=20&cscore1=$XSS&score1=8&zone0=BODY&id0=1005&var_name0=user[admin_comment]&zone1=BODY&id1=1013&var_name1=user[admin_comment], client: 178.xxx.213.xxx, server: server.site.com, request: "POST /user/update/1140805 HTTP/1.1", host: "server.site.com", referrer: "https://server.site.com/user/update/1140805"
```

This work:
`BasicRule wl:0 "mz:BODY";`

Nginx version:
```
nginx version: nginx/1.10.1
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) 
built with OpenSSL 1.0.1e-fips 11 Feb 2013
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/tmp/client_temp --http-proxy-temp-path=/tmp/proxy_temp --http-fastcgi-temp-path=/tmp/fastcgi_temp --http-uwsgi-temp-path=/tmp/uwsgi_temp --http-scgi-temp-path=/tmp/scgi_temp --user=nginx --group=nginx --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_stub_status_module --with-http_auth_request_module --with-mail --with-mail_ssl_module --with-file-aio --with-ipv6 --with-cc-opt='-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic' --add-module=/tmp/build/naxsi-master/naxsi_src
```

Naxsi version: `vers=0.55rc2`

**Comment by buixor** [comment]
Hello,

from your naxsi log it seems that it's normal it doesn't work :
BasicRule wl:0 "mz:BODY|$URL:/user/update";

Your rule targets "/user/update" but your url is "/user/update/1140805" you should use regular expressions

**Comment by perec007** [comment]
for example, in the rules is the following:
BasicRule wl:0 "mz:BODY|$URL:*/account/changepassword.**";



and the logs I see that the lock is still going on:
[image: Встроенное изображение 3]
[image: Встроенное изображение 2]

----------------------------------------
С уважением
Сиденко Олег Михайлович
skype: root_menos
phone: +79031196815
icq: 11100101

2016-10-05 15:01 GMT+03:00 buixor <notifications@github.com>:

**Comment by perec007** [comment]
For example, in the rules is the following:
BasicRule wl:0 "mz:BODY|$URL:/account/changepassword.*";



and the logs I see that the lock is still going on:

Naxsi log:
2016/10/06 02:07:53 [error] 19991#0: *11847768 NAXSI_FMT: ip=24.XXX.31.XXX&server=site.com&uri=/account/changepassword/USERID&learning=1&vers=0.55&total_processed=116&total_blocked=1&block=1&cscore0=$SQL&score0=16&zone0=BODY&id0=1016&var_name0=passwordchangeform[password]&zone1=BODY&id1=1016&var_name1=passwordchangeform[password_repeat], client: 24.XXX.31.XXX, server: www.site.com, request: "POST /account/changepassword/USERID?code=2eaa9abdfe1c80fec7100dd82a1g52d2 HTTP/1.0", host: "site.com", referrer: "https://site.com/account/changepassword/USERID?code=2eaa9abdfe1c80fec7100dd82a1g52d2"

And post nginx log:
"24.XXX.31.XXX" - - [06/Oct/2016:02:07:53 +0200] POST /account/changepassword/USERID?code=2eaa9abdfe1c80fec7100dd82a1g52d2 HTTP/1.0 /index.php 302 BODY:PasswordChangeForm%5Bpassword%5D=%23%23gXXXX1010*&PasswordChangeForm%5Bpassword_repeat%5D=%23%23gXXXX1010*

**Comment by perec007** [comment]
Do I need to create a new ticket, or you can re-open it? :)

**Comment by buixor** [comment]
Hello,

Sorry for delay :)
Please look at the whitelist/rules syntax, you need to use $.._X if you wanna use regex in mz:

https://github.com/nbs-system/naxsi/wiki/matchzones-bnf

**Comment by perec007** [comment]
In some places it is necessary to disable checking the BODY entirely.
To test I have included a training mode. For example I have here is a rule in the config nginx, which should act on the entire location / user / update /. To allow the whole BODY, i use "wl:0":
BasicRule wl:0 "mz:BODY|$URL:/user/update/.*";

But this does not happen and the log I see that many users will be blocked.

2016/10/17 19:46:16 [error] 94386#0: *59382835 NAXSI_FMT: ip=XX.xx.XX.xx&server=site.abc.com&uri=/user/update/01010101&learning=1&vers=0.55&total_processed=117&total_blocked=3&block=1&cscore0=$SQL&score0=12&cscore1=$XSS&score1=8&zone0=BODY&id0=1011&var_name0=userprofile[phone_mobile]&zone1=BODY&id1=1005&var_name1=user[admin_comment], client: XX.xx.XX.xx, server: site.abc.com, request: "POST /user/update/01010101 HTTP/1.1", host: "site.abc.com", referrer: "https://site.abc.com/user/update/01010101"

Please tell me the example of how to resolve this location entire BODY?
Thank you!

**Comment by buixor** [comment]
You didn't read my answer, did you ? :)

What I mean is that you need to write your rule so that naxsi knows it's a regular expression :

```
BasicRule wl:0 "mz:BODY|$URL_X:^/user/update/";
```

But I think it's quite dangerous to do so, and should be kept for very specific use-case, as it opens a wide breach in filtering.
