### ISSUE TITLE
Try TIS to find bugs in naxsi

### ISSUE THREAD

**Issue by jvoisin** [nbs-system/naxsi#320]
I just read a report from [Trail of bits](https://blog.trailofbits.com/2016/10/04/first-ever-automated-code-audit/) about an automated code review. it seems that [tis](https://github.com/TrustInSoft/tis-interpreter) is pretty good at finding bugs.

It's likely worth taking a look at it for naxsi :)

**Comment by buixor** [comment]
we are relying on coverity for source code audit; and playing with afl for fuzzing :)
