### ISSUE TITLE
Error 403: Login and Contact Forms for Wordpress and Magento

### ISSUE THREAD

**Issue by cjavierto** [nbs-system/naxsi#322]
Hi,

We just started using Naxsi firewall and it prohibits us in logging in to CMS admin like wordpress, magento and others. And we also noticed that contact forms or other forms aren't working when Naxsi is running.

Please advise on how we can go about fixing this.

Thanks,
Chris

**Comment by jvoisin** [comment]
Read the [documentation]( https://github.com/nbs-system/naxsi/wiki ), naxsi needs configuration to work with your application, it won't play nice out of the box.

**Comment by jvoisin** [comment]
It seems that reading the documentation was enough.

**Comment by cjavierto** [comment]
Ok thanks.
