### ISSUE TITLE
make sure the ES module version used by client is the same as server version

### ISSUE THREAD

**Issue by shaddai** [nbs-system/naxsi#324]
I tried to use nxapi using a virtualenv, I installed the elasticsearch module and unfortunately I got a cryptic error message :

```
elasticsearch.exceptions.SSLError: ConnectionError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)) caused by: SSLError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661))
```

It seems that to connect to an Elastic Search server the client must use the same version as the one running on the server.
Please include a check running prior to the connection to the ES server to determine that both module version and ES server version are compatible.

**Comment by zhujintao** [comment]
nxtool.py does not support the new version elastic search server,
use this
https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/rpm/elasticsearch/2.4.2/elasticsearch-2.4.2.rpm
