### ISSUE TITLE
Do you support CC attacks?

### ISSUE THREAD

**Issue by zhujintao** [nbs-system/naxsi#326]
how to limit URL access frequency,CC attacks ?

**Comment by jvoisin** [comment]
You can do that with [nginx]( https://nginx.org/en/docs/http/ngx_http_limit_req_module.html ), no need for naxsi.

I don't get the [second]( https://www.urbandictionary.com/define.php?term=CC%20Attack ) [part]( https://en.wikipedia.org/wiki/Crowd_control_(video_gaming) ) of your question.
