### ISSUE TITLE
MainRule id 1007 matches on non-consecutive dashes

### ISSUE THREAD

**Issue by bbaassssiiee** [nbs-system/naxsi#327]
This rule is designed to catch mysql comments (--):

`MainRule "**str:--**" "msg:mysql comment (--)" "mz:BODY|URL|ARGS|$HEADERS_VAR:Cookie" "s:$SQL:4" id:1007;`

It catches however many other strings with multiple dashes embedded, like for instance date as:

**?driveOnDate=2016-11-29**

Can we get a better regex?

**Comment by buixor** [comment]
Hello,

Can you confirm you are not in 0.55 ? for me this one was fixed in 0.55 :)

cheers,

**Comment by bbaassssiiee** [comment]
We run from master

**Comment by buixor** [comment]
Ok, I'm going to add a unit test to check for this bug, I'll come back to you.
This was a known bug, but supposedly fixed in 0.55

**Comment by bbaassssiiee** [comment]
naxsi.h has #define NAXSI_VERSION "0.55"

**Comment by buixor** [comment]
hello,

I added a unit test, and it seems to pass for me.
Can you confirm it reproduces the bug on your side ?

If you have source code, simply `make re test` from naxsi_src, it will download & compile nginx in /tmp/ and run unit tests.

cheers,

**Comment by bbaassssiiee** [comment]
I am collecting logs from my Naxsi to see if there are no false positives on the string '--'.

As to your request, before running `make re` I had to install some things.
```
yum install -y lcov perl-CPAN
perl -MCPAN -e 'install Test::Nginx'

```

This is the last part of the output:

export PATH="/tmp/nginx//objs/:"/sbin:/bin:/usr/sbin:/usr/bin ; \
export PERL5LIB="~/perl5/lib/perl5/:/home/travis/perl5/lib/perl5/" ; \
cd .. ; prove -r "t/"
t/00naxsi_base.t ................. ok     
t/01naxsi_whitelists.t ........... ok     
t/02naxsi_bypass.t ............... ok     
t/03naxsi_profile.t .............. ok     
t/04naxsi_files.t ................ ok     
t/05naxsi_advanced_whitelists.t .. ok     
t/06naxsi_weirds.t ............... ok     
t/07naxsi_argnames.t ............. ok     
t/08negative_whitelists.t ........ ok     
t/09sqlmap_tamper.t .............. ok     
t/10naxsi_modifiers.t ............ ok     
t/11naxsi_newstyle_config.t ...... ok     
t/12naxsi_argnames_extended.t .... ok   
t/13test.t ....................... ok   
t/14json.t ....................... ok     
t/15json_wl.t .................... ok     
t/16rx_mz.t ...................... ok     
t/17case.t ....................... ok   
t/18ids.t ........................ ok     
t/19targets.t .................... ok     
t/20sqlmap.t ..................... ok     
t/22libinjection-base.t .......... ok     
t/23verylong.t ................... ok   
t/24rawbody.t .................... ok     
t/25extra-coverage.t ............. ok   
t/26improved-matchzones.t ........ ok     
t/27libinjection-blacklist.t ..... ok   
t/28log.t ........................ ok     
t/29regression.t ................. ok   
All tests successful.
Files=29, Tests=722, 87 wallclock secs ( 0.35 usr  0.07 sys + 20.49 cusr 17.20 csys = 38.11 CPU)
Result: PASS
lcov --directory /tmp/nginx//objs/addon/naxsi_src/ --capture --output-file naxsi.info --base-directory /tmp/nginx/
Capturing coverage data from /tmp/nginx//objs/addon/naxsi_src/
Found gcov version: 4.8.5
Scanning /tmp/nginx//objs/addon/naxsi_src/ for .gcda files ...
Found 6 data files in /tmp/nginx//objs/addon/naxsi_src/
Processing naxsi_src/naxsi_utils.gcda
Processing naxsi_src/naxsi_raw.gcda
Processing naxsi_src/naxsi_json.gcda
Processing naxsi_src/naxsi_config.gcda
Processing naxsi_src/naxsi_skeleton.gcda
Processing naxsi_src/naxsi_runtime.gcda
Finished .info-file creation
genhtml -s -o /tmp/naxsicov.html naxsi.info
Reading data file naxsi.info
Found 7 entries.
Found common filename prefix "/usr/local/src/naxsi-master"
Writing .css and .png files.
Generating output.
Processing file /usr/include/stdlib.h
Processing file naxsi_src/naxsi_runtime.c
Processing file naxsi_src/naxsi_skeleton.c
Processing file naxsi_src/naxsi_json.c
Processing file naxsi_src/naxsi_config.c
Processing file naxsi_src/naxsi_utils.c
Processing file naxsi_src/naxsi_raw.c
Writing directory view page.
Overall coverage rate:
  lines......: 92.9% (1616 of 1740 lines)
  functions..: 100.0% (65 of 65 functions)

**Comment by buixor** [comment]
Ok so seems the bug is not that easy to reproduce. Can you keep me posted if you happen to find a log that triggered it ?

**Comment by bbaassssiiee** [comment]
Sure, I'll collect a days data and will try to see if it is now resolved.

**Comment by bbaassssiiee** [comment]
Data no longer shows signs of this bug.
