### ISSUE TITLE
nxtool parse log, Written 0 events

### ISSUE THREAD

**Issue by mickaelmonsieur** [nbs-system/naxsi#331]
Hello,
I try to read my logs and add them to the elasticsearch server (it run) it seems to me that nxtool can not read my logs. Why?

> root@waf002:/opt/naxsi/nxapi# ./nxtool.py -c nxapi.json --files=/var/log/nginx/access.log 
> size :1000
> No handlers could be found for logger "elasticsearch"
> Unable to create the index/collection : nxapi events
> WARNING:root:List of files :['/var/log/nginx/access.log']
> log open
> Written 0 events
> root@waf002:/opt/naxsi/nxapi# 

My logs are in normal nginx format. I use nginx as a transparent proxy.

**Comment by dbiazus** [comment]
Maybe You should try  ./nxtool.py -c nxapi.json --files=/var/log/nginx/error.log

**Comment by mickaelmonsieur** [comment]
Ok thanks 👍 
With error.log i have : Written 1481401 events.

In the documentation, It is not specified to use error.log, but "/PATH/TO/LOGFILE.LOG" :-)

**Comment by mickaelmonsieur** [comment]
Sorry, i have another problem:

`root@waf002:/opt/naxsi/nxapi# ./nxtool.py -c nxapi.json -x
size :1000
Whitelist(ing) ratio :
No handlers could be found for logger "elasticsearch"
Traceback (most recent call last):
  File "./nxtool.py", line 274, in <module>
    translate.fetch_top(cfg.cfg["global_filters"], "whitelisted", limit=2)
  File "/opt/naxsi/nxapi/nxapi/nxtransform.py", line 550, in fetch_top
    res = self.search(esq)
  File "/opt/naxsi/nxapi/nxapi/nxtransform.py", line 619, in search
    x = self.es.search(index=self.cfg["elastic"]["index"], doc_type=self.cfg["elastic"]["doctype"], body=esq)
  File "/usr/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 68, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 440, in search
    params=params, body=body)
  File "/usr/lib/python2.7/dist-packages/elasticsearch/transport.py", line 284, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 55, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 97, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, {u'failed_shards': [{u'node': u'JewSL91LT5-oK9fBkYisuA', u'index': u'nxapi', u'reason': {u'reason': u'Fielddata is disabled on text fields by default. Set fielddata=true on [whitelisted] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory.', u'type': u'illegal_argument_exception'}, u'shard': 0}], u'root_cause': [{u'reason': u'Fielddata is disabled on text fields by default. Set fielddata=true on [whitelisted] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory.', u'type': u'illegal_argument_exception'}], u'caused_by': {u'reason': u'Fielddata is disabled on text fields by default. Set fielddata=true on [whitelisted] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory.', u'type': u'illegal_argument_exception'}, u'grouped': True, u'reason': u'all shards failed', u'phase': u'query', u'type': u'search_phase_execution_exception'})
root@waf002:/opt/naxsi/nxapi# 
`

**Comment by buixor** [comment]
Hello,

which version of ES are you using ?

**Comment by mickaelmonsieur** [comment]
Hi,

The latest version stable:

root@waf002:/home/mickael# dpkg-query -l | grep elastic
ii  elasticsearch                  5.0.2                       all          Elasticsearch is a distributed RESTful search engine built for the cloud. Reference documentation can be found at https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html and the 'Elasticsearch: The Definitive Guide' book can be found at https://www.elastic.co/guide/en/elasticsearch/guide/current/index.html
ii  python-elasticsearch           1.2.0-1                     all          Python client for Elasticsearch
root@waf002:/home/mickael# cat /etc/debian_version 
8.6

**Comment by buixor** [comment]
Hello,

Can you try from master ? thank @s8sg

**Comment by buixor** [comment]
should be good from master
