### ISSUE TITLE
naxsi_kibana.dash and kibana-5.0.2

### ISSUE THREAD

**Issue by mguesdon** [nbs-system/naxsi#332]
I'm trying to import naxsi_kibana.dash in Kibana via "Saved Objects"/"Import" but it fail with:
<<
Error: arr.map is not a function
Promise.map@https://localhost/bundles/commons.bundle.js?v=14476:75:21674
.controller/$scope.importAll@https://localhost/bundles/kibana.bundle.js?v=14476:65:10601
anonymous/fn@https://localhost/bundles/commons.bundle.js?v=14476 line 41 > Function:2:306
initializeDirectiveBindings/</destination[scopeName]@https://localhost/bundles/commons.bundle.js?v=14476:37:11200
.link/handleFile/reader.onload/<@https://localhost/bundles/kibana.bundle.js?v=14476:35:14915
$RootScopeProvider/this.$get</Scope.prototype.$eval@https://localhost/bundles/commons.bundle.js?v=14476:39:4607
$RootScopeProvider/this.$get</Scope.prototype.$apply@https://localhost/bundles/commons.bundle.js?v=14476:39:4945
.link/handleFile/reader.onload@https://localhost/bundles/kibana.bundle.js?v=14476:35:14890

https://localhost/bundles/commons.bundle.js?v=14476
Line 38
>>

I don't know if this is the right way to do :-(

**Comment by buixor** [comment]
We don't provide dashboard for kibana5, sorry.
If you want to add a wiki article, you are welcome :)
