### ISSUE TITLE
Nginx / Naxsi Blocking all file uploads except certain whitelisted ones

### ISSUE THREAD

**Issue by C0nw0nk** [nbs-system/naxsi#335]
So the following rule

```
#############################
## File uploads: 1500-1600 ##
#############################
MainRule "rx:\.ph|\.asp|\.ht" "msg:asp/php file upload" "mz:FILE_EXT" "s:$UPLOAD:8" id:1500;
```

It blocks php asp htaccess file type uploads but I wanted to block all. And allow only the following formats to be uploaded.

.mp4 .webm .jpg .jpeg (Hopefully upper case lower case don't matter hope it is not case sensative)

Is it possible to block all formats and work of a whitelist basis of allow only.

**Comment by C0nw0nk** [comment]
Ok so I figured it out and got it working via a whitelist only principle :) <3

Here is my rule that works if anyone sees a problem please do say.

`MainRule "rx:\.(?!jpeg|jpg|mov|mpeg|png|divx|flv|mpg|avi|mp4|webm|wmv|ogg|m4v|mkv)" "msg:Block all file uploads except those whitelisted" "mz:FILE_EXT" "s:$UPLOAD:8" id:1501;`

Tested uploading all sorts of files other than those file types defined in that list it and it blocks them all successfully. 👍

**Comment by buixor** [comment]
you are welcome !
As you are using regex, I suggest using '$' at the of your regex to avoid bypass ;)

**Comment by C0nw0nk** [comment]
Yes I am. But I am using the second rule I provided now since after looking at the Wiki it seems I should be using "negative" instead of "?!" or does that not matter they both methods I found are efficient ?

The rule now to avoid potential bypassing.
```
MainRule negative "rx:\.jpeg$|\.jpg$|\.mov$|\.mpeg$|\.png$|\.divx$|\.flv$|\.mpg$|\.avi$|\.mp4$|\.webm$|\.wmv$|\.ogg$|\.m4v$|\.mkv$" "msg:Block all file uploads except those whitelisted" "mz:FILE_EXT" "s:$UPLOAD:8" id:1501;
```
