### ISSUE TITLE
how to imply not  contain a variable name  in combine rules {not variable value or type}?

### ISSUE THREAD

**Issue by hahahaha0o1** [nbs-system/naxsi#336]
some unfriendly agents may send request  without specific headers {for example X-Forwarded-For},  how to refuse them ,i.e. : User-Agent:ua1,
and not contain headers X-Forwarded-For?

 > MainRule "str:ua1" "msg:header User-Agent1"  "mz:$HEADERS_VAR:User-Agent" "s:$TE:1" id:17003;
 > MainRule "str:X-Forwarded-For" "msg:head"  "mz:HEADERS" "s:$TE:-1"  id:17000;

>  CheckRule "$TE >= 1" DROP;

here is what I try:
1: 
> curl http://127.0.0.1:4242/  -H X-Forwarded-For:xx  -H User-Agent:ua1   
    result:pass

2:
> curl http://127.0.0.1:4242/  -H User-Agent:ua1    -H X-Forwarded-For:xx
   result:block

> 127.0.0.1 - - [22/Dec/2016:13:10:15 +0800] "GET / HTTP/1.1" 200 612 "-" "ua1"
> 127.0.0.1 - - [22/Dec/2016:13:10:50 +0800] "GET / HTTP/1.1" 502 172 "-" "ua1"

the access and error log:

> 2016/12/22 13:10:50 [error] 67655#0: *4 NAXSI_FMT: 

>ip=127.0.0.1&server=127.0.0.1&uri=/&learning=0&vers=0.54&total_processed=4&total_blocked=2&block=0&cscore0=$TE&score0=1&zone0=HEADERS&id0=17003&var_name0=user-agent, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:4242"

it seem the result is affected by  position of the headers  in packets.  so is there any way to imply not contain something ? or import as a future feature, like adding  "uncontain"  keyword
  
> MainRule "str:ua1" "msg:header User-Agent1"  "mz:$HEADERS_VAR:User-Agent" "s:$TE:1" id:17003;
> MainRule  *uncontain*  "str:X-Forwarded-For" "msg:head"  "mz:HEADERS" "s:$TE:1"  id:17000;

and modify  checkrule to

> CheckRule "$TE >= 2" DROP;

**Comment by C0nw0nk** [comment]
As i demonstraighted here https://github.com/nbs-system/naxsi/issues/335#issuecomment-267972230

You can do so using the value "negative".
```
MainRule negative "str:x-forwarded-for"  "msg:head" "mz:HEADERS" "s:$TE:1" id:17000;
```
or you can use negative value in regex example (!?x-forwarded-for)
```
MainRule "rx:(!?x-forwarded-for)"  "msg:head" "mz:HEADERS" "s:$TE:1" id:17000;
```

**Comment by buixor** [comment]
@hahahaha0o1 would you mind closing the issue if the anwsers satisfies you ?
thanks @C0nw0nk :)

**Comment by hahahaha0o1** [comment]
thank you

**Comment by hahahaha0o1** [comment]
I want to detect a header name "myhead" in headers, if "myhead" not  is shown ,  to drop this packet
here is what I am try,  ie "myhead" is an user-deine header
> MainRule negative "rx:myhead" "msg:myhead " "mz:HEADERS" "s:$UWA:8" id:19001;
> CheckRule "$UWA >= 8" BLOCK;

I put  it in the /tmp/naxsi_ut/nginx.conf
when try   
with myhead
> curl http://127.0.0.1:4242/ -H "myhead: blabla"

and
without myhead
> curl http://127.0.0.1:4242/ 

it got

> [error] 26185#0: *1 NAXSI_FMT: ip=127.0.0.1&server=127.0.0.1&uri=/&learning=0&vers=0.55&total_processed=1&total_blocked=1&block=1&cscore0=$UWA&score0=8&zone0=HEADERS&id0=19001&var_name0=user-agent, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:4242"
> [error] 26185#0: *2 NAXSI_FMT: ip=127.0.0.1&server=127.0.0.1&uri=/&learning=0&vers=0.55&total_processed=2&total_blocked=2&block=1&cscore0=$UWA&score0=8&zone0=HEADERS&id0=19001&var_name0=user-agent, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:4242"

it seems it check user-agent and found there is no "myhead" in it ,then block it;

-----------------------------------------------------
then append  "|NAME" to zone, it got the same , both blocked.
>  MainRule negative "rx:myhead" "msg:myhead " "mz:HEADERS|NAME" "s:$UWA:8" id:19001;

 --------------------------------------------------
then try specify  "myhead" zone , got confused 
> MainRule negative "rx:myhead" "msg:myhead " "mz:$HEADERS_VAR:myhead|NAME" "s:$UWA:8" id:19001;

 with "myhead" request, expected to pass, it got error,  
 without "myhead" request, expct to drop, it got pass.

hope for help;
