### ISSUE TITLE
naxsi as a module over several nginx-versions

### ISSUE THREAD

**Issue by pimperator** [nbs-system/naxsi#341]
Hi Guys,

I've built naxsi 0.55.1 with nginx 1.10.2 as a module with naxsi's own Makefile (in naxsi-0.55.1/naxsi_src).

Later on I copy the module ngx_http_naxsi_module.so to /usr/lib64/nginx/modules/ngx_http_naxsi_module.so, install nginx 1.10.2 from the nginx-repo below ( I want a clean nginx for using naxsi as a module) and include the module into nginx.conf:
`load_module /usr/lib64/nginx/modules/ngx_http_naxsi_module.so;
...
include /etc/nginx/naxsi.rules; #file contains naxsi_core.rules`

`[root@localhost naxsi_src]# cat /etc/yum.repos.d/nginx.repo
[nginx]
name=nginx repo
baseurl=http://nginx.org/packages/centos/7/x86_64/
gpgcheck=0
enabled=1`

This is what I've modified in Makefile:
`NGINX_VERS := "1.10.2"

#the options are generated due to output of 
# nginx -V
NGINX_OPTIONS="--error-log-path=/tmp/naxsi_ut/error.log"
#NGINX_OPTIONS+="--add-dynamic-module=../naxsi_src"
NGINX_OPTIONS+="--prefix=/etc/nginx"
NGINX_OPTIONS+="--sbin-path=/usr/sbin/nginx"
NGINX_OPTIONS+="--modules-path=/usr/lib64/nginx/modules"
NGINX_OPTIONS+="--conf-path=/etc/nginx/nginx.conf"
NGINX_OPTIONS+="--error-log-path=/var/log/nginx/error.log"
NGINX_OPTIONS+="--http-log-path=/var/log/nginx/access.log"
NGINX_OPTIONS+="--pid-path=/var/run/nginx.pid"
NGINX_OPTIONS+="--lock-path=/var/run/nginx.lock"
NGINX_OPTIONS+="--http-client-body-temp-path=/var/cache/nginx/client_temp"
NGINX_OPTIONS+="--http-proxy-temp-path=/var/cache/nginx/proxy_temp"
NGINX_OPTIONS+="--http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp"
NGINX_OPTIONS+="--http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp"
NGINX_OPTIONS+="--http-scgi-temp-path=/var/cache/nginx/scgi_temp"
NGINX_OPTIONS+="--user=nginx"
NGINX_OPTIONS+="--group=nginx"
#NGINX_OPTIONS+="--with-http_ssl_module"
NGINX_OPTIONS+="--with-http_realip_module"
NGINX_OPTIONS+="--with-http_addition_module"
NGINX_OPTIONS+="--with-http_sub_module"
NGINX_OPTIONS+="--with-http_dav_module"
NGINX_OPTIONS+="--with-http_flv_module"
NGINX_OPTIONS+="--with-http_mp4_module"
NGINX_OPTIONS+="--with-http_gunzip_module"
NGINX_OPTIONS+="--with-http_gzip_static_module"
NGINX_OPTIONS+="--with-http_random_index_module"
NGINX_OPTIONS+="--with-http_secure_link_module"
NGINX_OPTIONS+="--with-http_stub_status_module"
NGINX_OPTIONS+="--with-http_auth_request_module"
NGINX_OPTIONS+="--with-http_xslt_module=dynamic"
#NGINX_OPTIONS+="--with-http_image_filter_module=dynamic"
NGINX_OPTIONS+="--with-http_geoip_module=dynamic"
NGINX_OPTIONS+="--with-http_perl_module=dynamic"
#NGINX_OPTIONS+="--add-dynamic-module=njs-1c50334fbea6/nginx"
NGINX_OPTIONS+="--with-threads"
NGINX_OPTIONS+="--with-stream"
#NGINX_OPTIONS+="--with-stream_ssl_module"
NGINX_OPTIONS+="--with-http_slice_module"
NGINX_OPTIONS+="--with-mail"
#NGINX_OPTIONS+="--with-mail_ssl_module"
#NGINX_OPTIONS+="--with-file-aio"
NGINX_OPTIONS+="--with-ipv6"
#NGINX_OPTIONS+="--with-http_v2_module"
#NGINX_OPTIONS+="--with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -mtune=generic'"
#NGINX_OPTIONS+="--with-ld-opt=-Wl,-E"
NGINX_OPTIONS+="--add-dynamic-module=$(MOD_PATH)"`

I am using the nginx-options because by using the default options I recieve an error not being binary compatible to nginx from the repository:
`[root@localhost nginx]# nginx -t
nginx: [emerg] module "/usr/lib64/nginx/modules/ngx_http_naxsi_module.so" is not binary compatible in /etc/nginx/nginx.conf:4
nginx: configuration file /etc/nginx/nginx.conf test failed`

I do use a standard whitelist for the default vhost (which is generated after installing nginx-rpm):
`SecRulesEnabled;

DeniedUrl "/RequestDenied";`

After Downgrading nginx (either to 1.10.0 or 1.10.1) or doing the opposite (compiling naxsi with nginx 1.10.0 and upgrading either to 1.10.1 or 1.10.2) I recieve the following errors:
`==> error.log <==
2016/12/27 16:20:51 [emerg] 29487#29487: module "/usr/lib64/nginx/modules/ngx_http_naxsi_module.so" version 1010002 instead of 1010001 in /etc/nginx/nginx.conf:4
2016/12/27 16:20:51 [notice] 29489#29489: using inherited sockets from "6;"
2016/12/27 16:20:51 [emerg] 29489#29489: module "/usr/lib64/nginx/modules/ngx_http_naxsi_module.so" version 1010002 instead of 1010001 in /etc/nginx/nginx.conf:4
nginx: [emerg] module "/usr/lib64/nginx/modules/ngx_http_naxsi_module.so" version 1010002 instead of 1010001 in /etc/nginx/nginx.conf:4
2016/12/27 16:20:57 [emerg] 29495#29495: module "/usr/lib64/nginx/modules/ngx_http_naxsi_module.so" version 1010002 instead of 1010001 in /etc/nginx/nginx.conf:4`
Nginx is running, but unable to restart.

Do you have any hints how to build naxsi to be able to use it as a module for more than the version it was built with or even any newer versions?

Thanks in advance

Erik

**Comment by buixor** [comment]
Hello,

Afaik, you can't because of the way modules are built and used for nginx. modular version doesn't require any modification in the code, so it's not really apache-style modules. Thus I think you have a hard dependency on the major/minor nginx version :)
