### ISSUE TITLE
Not getting entire error log line

### ISSUE THREAD

**Issue by madhur** [nbs-system/naxsi#342]
My NAXSI_FMT log lines look like this:

`2017/01/03 16:08:34 [error] 5810#0: *683 NAXSI_FMT: ip=117.215.164.119&server=dummy&uri=/consumers/v1/customers/me/category/addresses&learning=1&vers=0.55&total_processed=41&total_blocked=41&block=1, client: 117.215.164.119, server: dummy, request: "GET /consumers/v1/customers/me/category/addresses?pick_lon=80.2564957&pick_lat=13.0011774&category=CABS&company=UBER HTTP/1.1", host: "dummy"`

Here the Uri only contains partial parameters i.e. `total_blocked` and `block`. I am not getting the full parameter details such as `cscore0=$XSS&score0=32&cscore1=$SQL&score1=12&zone0=HEADERS&id0=1315&var_name0=cookie&zone1=ARGS&id1=1007&var_name1=asd`

This is the log line which I get from my other server. What is the issue in my original server?

**Comment by buixor** [comment]
I think you forgot to include your naxsi_core.rules :)

**Comment by buixor** [comment]
https://github.com/nbs-system/naxsi/wiki/olds-faq

**Comment by madhur** [comment]
:+1:
