### ISSUE TITLE
How to whitelist everything except a specific path like /rest?

### ISSUE THREAD

**Issue by danlsgiga** [nbs-system/naxsi#346]
I'm looking into a way to whitelist everything except a specific path list /rest.

So far I've tried setting this unique rule:
`BasicRule wl:0 "mz:$URL_X:^!/rest/.*$|URL"`

But I don't think it is being effective.

Is there any way to do that?

**Comment by buixor** [comment]
Hello,

Doing a negative rule should do the trick :
https://github.com/nbs-system/naxsi/wiki/rules-examples#negative-rule
