### ISSUE TITLE
Drupal update page - whitelist problem

### ISSUE THREAD

**Issue by Mato-Z** [nbs-system/naxsi#348]
Hello,

I have installed Naxsi on Nginx for secure my Drupal 7 website. I use recommended whitelist, but I had to add some exceptions yet. But I have problem with update Drupal modules. When I start automated update on page /admin/reports/updates/ I get 404 and in my Naxsi log is:

`2017/02/10 22:27:35 [error] 1979#0: *187 NAXSI_FMT: ip=MY_IP&server=MY_WEBSITE&uri=/admin/reports/updates/update&learning=0&vers=0.55&total_processed=181&total_blocked=3&block=1&cscore0=$XSS&score0=8&zone0=BODY|NAME&id0=1310&var_name0=projects[ctools]&zone1=BODY|NAME&id1=1311&var_name1=projects[ctools], client: MY_IP, server: MY_WEBSITE, request: "POST /admin/reports/updates/update HTTP/1.1", host: "MY_WEBSITE", referrer: "https://MY_WEBSITE/admin/reports/updates/update"`

I have tried use these whitelist rules:
```
BasicRule wl:0 "mz:$URL_X:^/admin|BODY";
BasicRule wl:0 "mz:BODY|$URL:/admin/reports/updates/update";
BasicRule wl:0 "mz:BODY|$URL_X:^/admin";
```
But I have the same problem... 
What rule I have to use please?

Thank you for help.

**Comment by buixor** [comment]
Hello,

From :
```
2017/02/10 22:27:35 [error] 1979#0: *187 NAXSI_FMT: ip=MY_IP&server=MY_WEBSITE&uri=/admin/reports/updates/update&learning=0&vers=0.55&total_processed=181&total_blocked=3&block=1&cscore0=$XSS&score0=8&zone0=BODY|NAME&id0=1310&var_name0=projects[ctools]&zone1=BODY|NAME&id1=1311&var_name1=projects[ctools], client: MY_IP, server: MY_WEBSITE, request: "POST /admin/reports/updates/update HTTP/1.1", host: "MY_WEBSITE", referrer: "https://MY_WEBSITE/admin/reports/updates/update"
```

You should whitelist 1310 and 1311 in BODY|NAME (and here, specifically on the URL of your exception):

`BasicRule wl:1310,1311 "mz:$URL:/admin/reports/updates/update|BODY|NAME";`

**Comment by buixor** [comment]
You
