### ISSUE TITLE
Nginx-naxi MainRule problem

### ISSUE THREAD

**Issue by ubuntutest** [nbs-system/naxsi#352]
Good morning,
I have compiled nginx with naxsi, following an online guide.
It worked until a few minutes ago.
I run a simple "apt-get update" on my ubuntu server and now nginx does not work anymore, I'm getting the following error:
```
feb 22 15:29:44 vps systemd[1]: Starting LSB: Stop/start nginx...
feb 22 15:29:44 vps nginx[1990]: nginx: [emerg] unknown directive "MainRule" in /etc/nginx/naxsi_core.rules:19
feb 22 15:29:44 vps systemd[1]: nginx.service: Control process exited, code=exited status=1
feb 22 15:29:44 vps systemd[1]: Failed to start LSB: Stop/start nginx.
```

Possible that my installation and configuration has been destroyed for having launched a ubuntu update? I have to delete everything and recompile nginx with naxsi?

EDIT: pagespeed module is broken too

**Comment by buixor** [comment]
Hello,

> Possible that my installation and configuration has been destroyed for having launched a ubuntu update? 

yes I think your nginx was upgraded, but to a version without naxsi. But your config should still be here :)

Yes, you will need to recompile it, or get a package from someone :)

**Comment by ubuntutest** [comment]
How i can block automatic upgrade of nginx from apt?
