### ISSUE TITLE
Add hardening flags to the Makefile

### ISSUE THREAD

**Issue by jvoisin** [nbs-system/naxsi#355]
Currently, the `Makefile` doesn't contain any hardening flags :/

**Comment by buixor** [comment]
`Makefile` itself is only used for unit tests, fuzzing, code coverage etc.
It's the `config` file in the `naxsi_src/` directory that is used by nginx for compilation.
So for me that's out of our scope, and it would be fairely intrusive to try to push our compilation options ?

Thoughts ?

**Comment by jvoisin** [comment]
I hope that adding stuff into the `config` file won't put them for the whole compilation process: this would be ridiculous. We should indeed add options in this file.
