### ISSUE TITLE
Creating rules for small servers?

### ISSUE THREAD

**Issue by Onyx808** [nbs-system/naxsi#361]
Hi,

I was trying to use nxapi to generate rules as recommended, however elasticsearch does not run in small servers with 512mb ram.

How would we go about generating rules?

Thank you!

**Comment by dbiazus** [comment]
Buy a 2GB RAM server at Digital Ocean for 20 bucks and be happy :-)
https://www.digitalocean.com/pricing/

**Comment by buixor** [comment]
Hello :)
nxtool-ng (https://github.com/nbs-system/nxtool-ng) is supposed be able to work with flat files !

**Comment by Onyx808** [comment]
@buixor thank you! I gave it a try but it didn't generate any rules on my test site, any ideas why?

Please see--> https://github.com/nbs-system/nxtool-ng/issues/22

**Comment by buixor** [comment]
Ok, let me get back to you :)
I'm closing this issue so we can handle it in nxtool repo's
