### ISSUE TITLE
nxtool

### ISSUE THREAD

**Issue by kacofoboj** [nbs-system/naxsi#363]
Please make NORMAL nxtool and docs, delete elasticsearch this is crap, how to configure rules on VPS RAM 512M and 1 CPU 2.6GHz, for make rules me need, elasticsearch JAVA, java, what?! over memory, for whaaat? simple rules...

Please delete elasticsearch, make old school!!!

**Comment by mosidze** [comment]
dont use it, it's not mandatory.

**Comment by kacofoboj** [comment]
@mosidze How???
```
root@root:/tmp/naxsi-0.55.3/nxapi# ./nxtool.py -c nxapi.json
Traceback (most recent call last):
  File "./nxtool.py", line 6, in <module>
    import elasticsearch
ImportError: No module named elasticsearch
root@root:/tmp/naxsi-0.55.3/nxapi# ./nxtool.py -x --colors -c nxapi.json
Traceback (most recent call last):
  File "./nxtool.py", line 6, in <module>
    import elasticsearch
ImportError: No module named elasticsearch
```

**Comment by aarvee11** [comment]
"pip install elasticsearch" This shall fix the issue. nxtool has a dependency on the python elasticsearch library
