### ISSUE TITLE
 white list rule 

### ISSUE THREAD

**Issue by dcalixto** [nbs-system/naxsi#366]
Instead of the white list the session for tommy i would like to white list for all users, below a code example.
`BasicRule wl:1000 "mz:$URL:/sessions/tommy|$BODY_VAR:_method";`

So, how can i white list the session for all users?

**Comment by snottycrustacean** [comment]
You should use $URL_X:regexp
e.g.
BasicRule wl:1000 "mz:$URL_X:/sessions/*|$BODY_VAR:_method";

**Comment by aarvee11** [comment]
PCRE Regex works. So generate a regex for all your usernames. http://regexr.com/ is your friend

**Comment by dcalixto** [comment]
so, should be?
BasicRule wl:1000 "mz:$URL_X:regexp:/|$BODY_VAR:_method";

**Comment by buixor** [comment]
Hello,

if you use regex-style expression, the whole match-zone must be in regex, see :
https://github.com/nbs-system/naxsi/wiki/matchzones-bnf

**Comment by dcalixto** [comment]
Hello @buixor 
so that's is the properly way?
BasicRule wl:1000 "mz:$URL_X:regexp:/|$BODY_VAR:regex:_method";

**Comment by buixor** [comment]
Hello,

```
BasicRule wl:1000 "mz:$URL_X:regexp:/|$BODY_VAR_X:regex";
```

Would be the way :)
