### ISSUE TITLE
naxsi 0.55.3 nonsupport nginx subrequest ?

### ISSUE THREAD

**Issue by knight06** [nbs-system/naxsi#367]
Hi,
it seem that the naxsi does not take effect within the nginx internal subrequest?

- nginx: `1.10.1`
- modsecurity: `0.55.3`
- nginx.conf:
```nginx
location /loc1 {
   #SecRulesEnabled;
   #DeniedUrl "/50x.html"; 
   #CheckRule "$SQL >= 8" BLOCK;
   #CheckRule "$RFI >= 8" BLOCK;
   #CheckRule "$TRAVERSAL >= 4" BLOCK;
   #CheckRule "$EVADE >= 4" BLOCK;
   #CheckRule "$XSS >= 8" BLOCK;
   
   content_by_lua ' ngx.location.capture('/loc2')';
}

location /loc2 {
   SecRulesEnabled;
   DeniedUrl "/50x.html"; 
   CheckRule "$SQL >= 8" BLOCK;
   CheckRule "$RFI >= 8" BLOCK;
   CheckRule "$TRAVERSAL >= 4" BLOCK;
   CheckRule "$EVADE >= 4" BLOCK;
   CheckRule "$XSS >= 8" BLOCK;

   proxy_pass http://192.168.0.11:8080$request_uri;
}
```

1. enable naxsi SecRule in /loc1, the rules take effect.
2. disable SecRule in /loc1, only enable naxsi SecRule in /loc2, the rules have no effect. that is to say, the naxsi does not take effect in the nginx internal subrequest.

Any good suggestions? Thanks!

**Comment by buixor** [comment]
Hello,
Yes, so far naxsi does not process any requests tag as internal, does content by lua enables this flag ?

**Comment by buixor** [comment]
Hello, merging with #364 if you don't mind
