### ISSUE TITLE
What does the ALLOW action do?

### ISSUE THREAD

**Issue by Annihil** [nbs-system/naxsi#368]
I did not found any documentation regarding actions of the CheckRules.
If I understand correctly, `DROP` will block the request no matter the learning mode state, while `BLOCK` will block the request only if not in learning mode.
`LOG` will just write learning log without blocking the request.
What will `LOG` do if learning mode is disabled?
Moreover, I checked the code, `ctx->allow` is set but never used (no `if (ctx->allow)`).
What is the purpose of `ALLOW` ?

Thanks.

**Comment by buixor** [comment]
Hello,

`allow` score aims at overriding other rules to force a pass action, but it should not be used for now, as it is not fully implemented.

**Comment by buixor** [comment]
see #374 :)
