### ISSUE TITLE
error log field "cscore" lost when blocking "$EVADE" attack

### ISSUE THREAD

**Issue by lsqworld** [nbs-system/naxsi#369]
Version:  0.55.1

When I made a "$EVADE" attack , I could not find the "cscore" field in it's blocked log line.

What request I've made:
**http://10.110.20.19/?a=%U**
And the blocked log:
![qq 20170327162435](https://cloud.githubusercontent.com/assets/8489467/24347288/5fcc9ef2-130a-11e7-9793-b6d25eba28cf.png)

And the following is a normal "$SQL" attack block log: 
![qq 20170327162724](https://cloud.githubusercontent.com/assets/8489467/24347300/6f56f052-130a-11e7-8c00-9e820d34aedd.png)

So is it just a bug or I made some error?
Thank you very much!

**Comment by buixor** [comment]
Hello,

It is because you triggered an `internal` rule. Those do not set a specific named score, but just set the block flag in the request.

**Comment by lsqworld** [comment]
I feel so sorry for wasted your time! @buixor

**Comment by buixor** [comment]
Fixed doc : https://github.com/nbs-system/naxsi/wiki/internal-rules
