### ISSUE TITLE
Error creating Whitelist rule with pipe "|"

### ISSUE THREAD

**Issue by buliverd53** [nbs-system/naxsi#372]
Hey guys, i'm trying to create an rule of the follow URI
```
/{{event.backgroundUrl%20|%20imageUrl}}
```
But i got error, here's the rule that i've tried to use:
```
BasicRule wl:15 "mz:$URL_X:ˆ([ A-Za-z0-9_@./%#&%{}+-]*)([|])([ A-Za-z0-9_@./#%{}&+-]*)?|URL";
```

**Comment by buixor** [comment]
Hello,

Yes, this is the price of a poor design decision, we hope to add a workaround in next version, but so far, you are stuck, sorry :(

**Comment by buixor** [comment]
see #271
