### ISSUE TITLE
Naxsi Rules Ips Community suite

### ISSUE THREAD

**Issue by ubuntutest** [nbs-system/naxsi#378]
Hi, is there a basic set of naxsi rules  for the invisionpower platform? Ips Community Suite.

I tried different configurations, the platform works, but in /var/log/nginx I have a lot of errors of different kinds, like this: https://pastebin.com/1MUPSXg8

UPDATE:
I have to comment on these rules otherwise the platform does not want to work

`    #CheckRule "$SQL >= 10" BLOCK;
 #CheckRule "$XSS >= 8" BLOCK;`

I'm making naxsi useless, but at the moment I do not know how to solve.
I'm getting a lot errors about pagespeed now 
24038#24038: *421 NAXSI_FMT: `ip=...........&server==...........&&uri=/ngx_pagespeed_beacon&learning=0&vers=0.55.3&total_processed=926&total_blocked=18&block=1&cscore0=$RFI&score0=8&zone0=ARGS&id0=1101&var_name0=url, client: =...........&, server: =...........&, request: "POST /ngx_pagespeed_beacon?url=https%3A%2F%2F=...........&%2Findex.php%3F%2Fblogs%2F HTTP/1.1", host: "=...........&"`

Thank you

**Comment by buixor** [comment]
Hello,
Did you try performing learning on the logs ?
Have a look as well to : https://github.com/nbs-system/naxsi-rules
