### ISSUE TITLE
which rule is 452?

### ISSUE THREAD

**Issue by dcalixto** [nbs-system/naxsi#379]
i'm trying to white list this but i added the 452 as wl the nginx show error, someone can help?
`BasicRule wl:452 "mz:$URL_X:/(?:.*)/|$ARGS_VAR:simpletabs_selected_tab|message";`
`
2017/05/10 18:40:31 [error] 12357#0: *452 NAXSI_FMT: ip=xxx.xx.xxx.xxx&server=xx.xx.xxx.xx&uri=/conversations&learning=0&vers=0.54&total_processed=239&total_blocked=1&block=1&cscore0=$SQL&score0=6&cscore1=$XSS&score1=8&zone0=BODY&id0=1009&var_name0=authenticity_token&zone1=BODY&id1=1016&var_name1=conversation_participants[user_id]&zone2=BODY&id2=1302&var_name2=conversation_participants[user_id], client: xxx.xx.xxx.xxx, server: xx.com, request: "POST /conversations HTTP/1.1", host: "xx.xx.xxx.xx", referrer: "http://xx.xx.xxx.xx/users/2?simpletabs_selected_tab=message"`

**Comment by buixor** [comment]
Hello !

in ```
2017/05/10 18:40:31 [error] 12357#0: *452 NAXSI_FMT: ip=xxx.xx.xxx.xxx&server=xx.xx.xxx.xx&uri=/conve``` the `452` is not naxsi ID, but nginx worker.

You IDs here are :
```id0=1009&id1=1016&id2=1302```

You can always refer to :
https://github.com/nbs-system/naxsi/wiki/internal-rules
and naxsi_core.rules
