### ISSUE TITLE
[FEATURE] i'd like to acces naxsi.$SCORE from within nginx as an $var

### ISSUE THREAD

**Issue by rogerthat** [nbs-system/naxsi#383]
this would allow me to extend naxsi's capabilities with the power of lua, e.g. use counters, thresholds, dynamic blocks or return zipbombs for obvious maliciius requests or botnet-attacks.

**Comment by marcelomd** [comment]
Hi,
We have a commit that exposes the variables that compose NAXSI_FMT. If this is what you're looking for I can make a PR later this week.

**Comment by rogerthat** [comment]
Hi,

exactly, that would be perfetct

i could and would test this under live-conditions

**Comment by marcelomd** [comment]
Done! #388

**Comment by marcelomd** [comment]
By the way, we use it live. Works as expected, but we appreciate an extra set of eyes =)

**Comment by buixor** [comment]
Commented on your MR ;)
