### ISSUE TITLE
Naxis nginx rpm binary or yum repo for CentOS 6.x / CentOS 7.x

### ISSUE THREAD

**Issue by kaushalshriyan** [nbs-system/naxsi#385]
Are there any rpm binary package or yum repo for CentOS 6.x / CentOS 7.x to install Naxsi Nginx security module in nginx webserver?

**Comment by pimperator** [comment]
I'd also be happy about that!!

**Comment by jvoisin** [comment]
No, there isn't (yet), sorry; you'll have to compile naxsi yourself for now.
