### ISSUE TITLE
Whitelist file path..

### ISSUE THREAD

**Issue by rakesh-eltropy** [nbs-system/naxsi#387]
Hi,
I am using following to generate whitelist rules:
`./nxtool.py -c nxapi.json -f
`
I get following output:

> # size :1000
> #  template :tpl/URI/site-wide-id.tpl 
> Nb of hits : 25
> #  template matched, generating all rules.
> 1 whitelists ...
> #  template :tpl/URI/global-url-0x_in_pircutres.tpl 
> Nb of hits : 0
> #  template :tpl/URI/url-wide-id.tpl 
> Nb of hits : 25
> #  template matched, generating all rules.
> 1 whitelists ...
> #  template :tpl/HEADERS/cookies.tpl 
> Nb of hits : 13
> #  template matched, generating all rules.
> 3 whitelists ...
> #  template :tpl/ARGS/url-wide-id-NAME.tpl 
> Nb of hits : 0
> #  template :tpl/ARGS/site-wide-id.tpl 
> Nb of hits : 11
> #  template matched, generating all rules.
> 3 whitelists ...
> #  template :tpl/ARGS/precise-id.tpl 
> Nb of hits : 11
> #  template matched, generating all rules.
> 3 whitelists ...
> #  template :tpl/ARGS/url-wide-id.tpl 
> Nb of hits : 11
> #  template matched, generating all rules.
> 3 whitelists ...
> #  template :tpl/APPS/google_analytics-ARGS.tpl 
> Nb of hits : 0
> #  template :tpl/BODY/site-wide-id.tpl 
> Nb of hits : 25
> #  template matched, generating all rules.
> 8 whitelists ...
> #  template :tpl/BODY/precise-id.tpl 
> Nb of hits : 25
> #  template matched, generating all rules.
> 13 whitelists ...
> #  template :tpl/BODY/url-wide-id-BODY-NAME.tpl 
> Nb of hits : 7
> #  template matched, generating all rules.
> 1 whitelists ...
> #  template :tpl/BODY/var_name-wide-id.tpl 
> Nb of hits : 25
> #  template matched, generating all rules.
> 13 whitelists ...
> #  template :tpl/BODY/url-wide-id.tpl 
> Nb of hits : 25
> #  template matched, generating all rules.
> 11 whitelists ...
> 

But not sure where is the whitelist rules file.

Thanks,
Rakesh Goyal

**Comment by buixor** [comment]
Hello,

I don't see any whitelists neither.
Can you please use nxtool-ng ? nxapi should be considered as deprecated :D
