### ISSUE TITLE
Questions about naxsi tool/api

### ISSUE THREAD

**Issue by ajrpayne** [nbs-system/naxsi#390]
1.) What is the difference between https://github.com/nbs-system/naxsi/tree/master/nxapi and https://github.com/nbs-system/nxtool-ng?

Is the latter replacing the former?

2.) What template/mapping is produced in elasticsearch by either of the above?

**Comment by buixor** [comment]
Hello,

Yes, nxtool-ng is a replacement of nxapi, and nxapi should soon disappear.



@sabban : I guess we should clarify the documentation of nxtool-ng, especially now that it has implemented all the features of the old nxtool :)

**Comment by sabban** [comment]
done
