### ISSUE TITLE
Info about naxsi logs

### ISSUE THREAD

**Issue by ManuelRighi** [nbs-system/naxsi#396]
Hello,
I'm try to build parser for monitoring naxsi logs.
I have a simple question.
Take an example from this piece of log

2017/09/15 15:55:55 [error] 4868#4868: *377580 NAXSI_FMT: ip=xxxx

*377580 is a unique number that does not repeat itself in the same log?
If I have multiple virtual hosts on same server, this number remain unique in all logs ?

Thanks
Manuel

**Comment by nadzree** [comment]
From my understanding that the error log using ngx_log_error and by reading on the lxr, the *377580 http://lxr.nginx.org/source/src/core/ngx_log.c?v=nginx-1.12.0 line 0123 it may reffer to the process ID

**Comment by nadzree** [comment]
If this could help..my parser regex looks like this:
/\d{4}.\d{2}.\d{2}\s\d{2}\:\d{2}\:\d{2}.*NAXSI_FMT/

**Comment by sabban** [comment]
4868#4868 are respectively pid and tid.
377850 is a global connection counter as stated in https://github.com/Fleshgrinder/nginx-configuration/wiki/Log-Formatting
