### ISSUE TITLE
Naxsi blocks when in learning mode for internal rules 

### ISSUE THREAD

**Issue by albertvaka** [nbs-system/naxsi#398]
I've seen that some POSTs from Android are triggering the internal MainRule 13 (invalid POST format) in my environment. The problem, though, is that those requests only end up in my DeniedUrl, and not the original location, even though I'm in LearningMode. 

Why is this happening? Are internal rules a special case that always cause requests to be blocked?

This is my config:
```
            SecRulesEnabled;
            LearningMode;
            DeniedUrl "/naxsi-intercepted-request";
            BasicRule wl:16; # Whitelist: Empty POST body.
            CheckRule "$SQL >= 1" LOG;
            CheckRule "$RFI >= 1" LOG;
            CheckRule "$TRAVERSAL >= 1" LOG;
            CheckRule "$XSS >= 1" LOG;
            CheckRule "$EVADE >= 1" LOG;
            CheckRule "$UPLOAD >= 1" LOG;
```

I also have (a slightly modified version of) `naxsi_core.rules` included.

Thanks!

**Comment by albertvaka** [comment]
I can see from the source code [1], that indeed built-in rules are always blocking.

Is there any way that this can be overridden?

[1] https://github.com/nbs-system/naxsi/blob/master/naxsi_src/naxsi_runtime.c#L42

**Comment by buixor** [comment]
Hello,

Sorry for the delay, I was busy working on [snuffleupagus](https://snuffleupagus.readthedocs.io/) :)
You can whitelist the internal rule as any rule. However, by doing so, you will render naxsi completly blind of what is happening. Internal rules that drop request even in learning-mode means that naxsi usually cannot parse the request at all, and thus can't inspect it.
