### ISSUE TITLE
nxapi/nxtools.py support ES 6.x

### ISSUE THREAD

**Issue by volp1s** [nbs-system/naxsi#408]
At this moment nxapi/nxtools.py supports only Elasticsearch 1 / 2 / 5
Why this limitation? Is this compatibility planned to be extended?
I'm trying to get this working with ES 6.1
Thx

**Comment by buixor** [comment]
Hello,
We don't use ES6 yet. If you happen to make it work, we'll gladly review and merge MR ;)

**Comment by stephanelange** [comment]
Hi,
Just need to replace all "2", "5" by "2", "5", "6" in the nxtransform.py file
ES 5 and 6 seems to have a good backward compatibility
It has worked fine for me, no troubles by now

**Comment by jaygooby** [comment]
I had to change https://github.com/nbs-system/naxsi/blob/master/nxapi/nxapi/nxparse.py#L406 from 

```
if self.es_version == '5':
```

to 

```
if self.es_version == '5' or self.es_version == '6':
```

Before it would work for me. 

Also watch out for using paths you might expect the shell to expand. Once I'd made the above change, I didn't get any errors, but it looked like the error log file had been ignored:

```
./nxtool.py -c nxapi.json --files=~/nginx/log/error.log
# size :1000
WARNING:root:List of files :[]
```

The `~` didn't get expanded by python. But using:

```
./nxtool.py -c nxapi.json --files=/Users/jay/nginx/log/error.log
```

did
