### ISSUE TITLE
Can I analyze the logs from a different server?

### ISSUE THREAD

**Issue by chancarlo** [nbs-system/naxsi#414]
I have a small VPS with only 1GB memory. I don't want to install Elasticsearch as it will eat my RAM. I can install Naxsi with my NGINX stack and set it to learning mode. Once it has generated enough log, can I copy the log to another temporary higher memory VPS where I will install Elasticsearch and nxtool and generate the whitelist rules from there then copy it back to my server?

**Comment by buixor** [comment]
yes ofc the tools coming with naxsi can work from flat logfiles as well :)

**Comment by chancarlo** [comment]
Ah so that's what flat files meant. Thanks this is great!
