### ISSUE TITLE
Naxsi is blocking traffic even though learningmode is enabled.

### ISSUE THREAD

**Issue by melaraj2** [nbs-system/naxsi#416]
I am completely confused, I have installed Naxsi and it is running in learningmode.  I am slowly analyzing the log and adding rules.  But as soon as I add new custom rules, naxsi is blocking traffic.  Why?? I wanted to stay in learning mode until I have added all of my rules, and decided that they are good enough.  Am I misunderstanding the learning mode option?

**Comment by buixor** [comment]
Hello,
Can you provide more info on what happens, like logs ?
The only things that might be blocking in learning-mode are :
 - explicit black-list rules that use the `DROP` action
 - internal rules related to naxsi unability to parse incoming request
