### ISSUE TITLE
Naxsi doesn't support application/csp-report content type

### ISSUE THREAD

**Issue by z0r0** [nbs-system/naxsi#419]
Hello,

During testing, it appears as though naxsi doesn't support the content type used by CSP in browsers.

More detailed information can be seen [Here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy-Report-Only), but the fix would simply be to treat content-type: application/csp-report the same as application/json, as the payload of the csp-report should be a json object.

**Comment by buixor** [comment]
Hello,

Thanks for the report.
Do you have any suggestion on how you would like this header to be treated ?

**Comment by z0r0** [comment]
Hows about this? #421

**Comment by buixor** [comment]
<3 let me have a look :)

**Comment by buixor** [comment]
closing and watching MR
