### ISSUE TITLE
Naxsi encoding / character in EXLOG but not FMT

### ISSUE THREAD

**Issue by dravison** [nbs-system/naxsi#427]
Hi,

I've upgraded to nginx 1.14 with the latest naxsi release and since then the slashes in the EXLOG logs are encoded (%2F) but the slashes in the FMT log aren't being encoded. Example:

EXLOG:
```
uri=%2Fwp-login.php&id=42000261
```

FMT:
```
uri=/wp-login.php
```

Is this a bug?

**Comment by buixor** [comment]
Hello,

The difference is due to the fact that NAXSI_EXLOG uses `NGX_ESCAPE_URI_COMPONENT` while NAXSI_FMT uses `NGX_ESCAPE_ARGS`.

Both ensure that `&` is encoded, avoiding log injection, but it might be worth changing :)
