### ISSUE TITLE
comment and code inconsistency: handler set in REWRITE phase, not ACCESS phase

### ISSUE THREAD

**Issue by mlakes** [nbs-system/naxsi#435]
Comment for setting the handler says it will be set for the ACCESS phase:
https://github.com/nbs-system/naxsi/blob/master/naxsi_src/naxsi_skeleton.c#L356
But the code actually sets handler for REWRITE phase - which should be ok - but what is the intention?

**Comment by buixor** [comment]
Nice catch, changing the comment right away :)
