### ISSUE TITLE
Why do I compile nginx with naxsi or I will prompt the MainRule directive?

### ISSUE THREAD

**Issue by youzizzz** [nbs-system/naxsi#439]
My machine is ubuntu16.04
Nginx module information screenshots are as follows
![image](https://user-images.githubusercontent.com/28948945/47061219-20185300-d203-11e8-9502-6f286b3b4fa3.png)
Nginx config information screenshots are as follows
![image](https://user-images.githubusercontent.com/28948945/47061282-666db200-d203-11e8-8a18-a1879e0e81b9.png)
The naxsi_core.rules configuration is exactly the same as the example you gave.
But the startup result is
![image](https://user-images.githubusercontent.com/28948945/47061334-9ae16e00-d203-11e8-8d09-299b88e25eb4.png)
Excuse me, why is this? thank you

**Comment by jvoisin** [comment]
Have you checked the [relevant documentation]( https://github.com/nbs-system/naxsi/wiki/naxsi-setup )? Also, are you sure that `naisi_core_rules` doesn't contain a typo?

On a side note, please avoid using screenshot for texts: they do not permit text selection, aren't great to zoom on, and aren't readable by blind people.

**Comment by youzizzz** [comment]
Ok, verified, it’s true that my personal negligence caused this problem. The file name was written as naisi..., sorry, thank you for your answer.
