### ISSUE TITLE
Whitelist all as default ?

### ISSUE THREAD

**Issue by ManuRgh** [nbs-system/naxsi#444]
Hello,
it's possible to `ACCEPT`/Whitelist by default instead of `DROP` by default ?

Basically if I create 

```
MainRule wl:0 "mz:URL|BODY|ARGS|HEADERS";
```

and after I insert many `MainRule` for block only specif requests .... works ?

Thanks

**Comment by jvoisin** [comment]
While it's possible, it sounds like a super-duper bad idea, and it's unlikely that someone will help you to shoot yourself in the foot :/

**Comment by ManuRgh** [comment]
> While it's possible, it sounds like a super-duper bad idea, and it's unlikely that someone will help you to shoot yourself in the foot :/
> 
> What is your usecase exactly?

Naxsi seems very good and easy to use, but for each web application a lot of learning time is spent to implement whitelists.
So I thought if it is possible to act in reverse, accept everything by default, and implement minimum security rules, for do not have to work too much every time a web application is published.

**Comment by jvoisin** [comment]
This won't work, there is not such thing as "minimum security rules" : naxsi has little intelligence, it blocks everything; it's up to its operators to be smart and whitelist what is legit. The other way around doesn't work at all :/
