### ISSUE TITLE
When naxsi.rule sets up log policy，Return 504 error

### ISSUE THREAD

**Issue by loki008** [nbs-system/naxsi#447]
When naxsi.rule sets up log policy，After rule matching，Return 504 error，And there is no log record.
When naxsi.rule sets up block policy，it's OK，it can block and record log.
why？Please help，thanks.

nginx.conf information：

```nginx
user admin admin;

worker_processes auto;
worker_cpu_affinity auto;

error_log /data/logs/nginx/error.log crit;
pid /var/run/nginx.pid;

worker_rlimit_nofile 65535;

include dso_conf/ngx_dso_modules.conf;

events {
    use epoll;
    worker_connections 10240;
}

http {
    include naxsi_core.rules;
    server_tokens off;
    server_tag off;
    autoindex off;
    access_log off;
    include mime.types;
    default_type application/octet-stream;

    server_names_hash_bucket_size 128;
    client_header_buffer_size 128k;
    large_client_header_buffers 4 128k;
    client_max_body_size 2m;
    client_body_buffer_size 256k;

    sendfile on;
    tcp_nopush on;
    keepalive_timeout 900;
    tcp_nodelay on;

    gzip on;
    gzip_min_length 1k;
    gzip_buffers 4 16k;
    gzip_http_version 1.1;
    gzip_comp_level 6;
    gzip_types "image/jpeg;charset=utf-8" text/plain application/x-javascript text/css application/xml application/javascript text/javascript image/jpeg image/gif image/png;
    gzip_vary on;

    proxy_connect_timeout 900;
    proxy_read_timeout 900;
    proxy_send_timeout 900;
    proxy_buffer_size 128k;
    proxy_buffers 4 128k;
    proxy_busy_buffers_size 256k;
    proxy_temp_file_write_size 256k;
    proxy_headers_hash_max_size 1024;
    proxy_headers_hash_bucket_size 128;

    proxy_redirect off;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_cache_path /data/logs/nginx/cache1 levels=1:2 keys_zone=cache1:100m max_size=50g inactive=90d;
    proxy_temp_path /data/logs/nginx/nginx_temp/nginx_temp;

    log_format access '$remote_addr - $remote_user [$time_local] "$request"'
                      '$status $body_bytes_sent "$http_referer"'
                      '"$http_user_agent" $http_x_forwarded_for';

    log_format ha     '$remote_addr\t$time_local\t$host\t"$request"\t'
                      '$status\t$body_bytes_sent\t"$http_referer"\t'
                      '"$http_user_agent"\t$request_time\t$sent_http_content_type\t'
                      '$upstream_addr\t$upstream_status\t$upstream_response_time\t'
                      '"$http_x_forwarded_for"';

    log_format main '$remote_addr\t$time_local\t"$request"\t'
                '$status\t$body_bytes_sent\t"$http_referer"\t'
                '"$http_user_agent"\t$request_time\t'
                '$upstream_addr\t$upstream_status\t$upstream_response_time\t'
                '"$http_x_forwarded_for"\t$host';

    log_format json '$remote_addr\t-\t$remote_user\t[$time_local]\t"$request"\t'
                      '$status $body_bytes_sent\t"$http_referer"\t'
                      '"$http_user_agent"\t$request_time\t'
                      '$http_x_requested_with\t$sent_http_content_type\t'
                      '$host\t$upstream_response_time';



    map $http_x_forwarded_proto $https_status {
        default off;
        https on;
    }
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    ## reqstat
    req_status_zone server_reqstat_monitor "$host" 100M;


   ##
    # limit req zone
    ##
    limit_req_zone $binary_remote_addr $http_user_agent zone=limit_with_user_agent:50m rate=30r/m;
    limit_req_zone $binary_remote_addr $uri zone=limit_with_uri:50m rate=3r/m;
    limit_req_zone $server_name zone=limit_server_qps:10m rate=3500r/s;
    limit_req_zone $binary_remote_addr zone=limit_with_remote_addr:20m rate=5r/m;

    include conf.d/*.conf;
    include upstream/*.conf;
    include vhost.d/*.conf;
}

vhost.d/conf information：
server {

  listen   80;
  server_name 10.10.10.10 test.fc.17.com;

  access_log  /data/logs/nginx/test.fc.17.com_access.log main;
  error_log   /data/logs/nginx/test.fc.17.com_error.log;

  root /home/admin/app-run/fc.17.com/dist;
#  include /opt/app/nginx/conf/web.spa.node.conf;
  include /opt/app/nginx/conf/global.conf;


gzip on;
gzip_min_length 1k;
gzip_comp_level 2;

location / {
    include /opt/app/nginx/conf/naxsi.rules;
#    include /opt/app/nginx/conf/naxsi_BasicRule.conf;
    try_files $uri $uri/ /index.html;
}
location ~* \.(html)$ {
    expires -1;
}
location ~* \.(js|css|png|jpg|jpeg|gif|ico|icon|bmp|swf)$ {
    expires 1y;
}
location  /p/ {
    include /opt/app/nginx/conf/naxsi.rules; 
    proxy_pass http://test.node.17.com;
    #proxy_set_header X-Forwarded-For  $remote_addr;
    proxy_set_header Host test.node.17.com;
}
location /RequestDenied {       
    return 403;
}

error_page  403  /403.html;
location = /403.html {
    root   html;
}

error_page   500 502 503 504  /50x.html;
location = /50x.html {
    root   html;
}
}
```

naxsi.rule information：
```
SecRulesEnabled;
DeniedUrl "/RequestDenied";
CheckRule "$SQL >= 8" BLOCK;
CheckRule "$RFI >= 8" LOG;
CheckRule "$TRAVERSAL >= 8" LOG;
CheckRule "$EVADE >= 8" LOG;
CheckRule "$XSS >= 8" LOG;
CheckRule "$CMD >= 8" BLOCK;
CheckRule "$INCLUSION >= 8" LOG;
```

**Comment by buixor** [comment]
(updated your issue for formatting)

**Comment by buixor** [comment]
@loki008 : Can you provide example of the requests that doesn't generate expected results ?
We need a bit more context ;)

**Comment by loki008** [comment]
naxsi.rules:
SecRulesEnabled;
DeniedUrl "/RequestDenied";
CheckRule "$SQL >= 8" LOG;
CheckRule "$RFI >= 8" LOG;
CheckRule "$TRAVERSAL >= 8" LOG;
CheckRule "$EVADE >= 8" LOG;
CheckRule "$XSS >= 8" LOG;
CheckRule "$CMD >= 8" BLOCK;
CheckRule "$INCLUSION >= 8" LOG;

naxsi_core.rules:
MainRule "rx:(?:count|length|sleep|char|ascii|hex|unhex|conv|benchmark|md5)\(" "mz:BODY|ARGS|$HEADERS_VAR:Cookie" "s:$SQL:8" id:1021;

if use paymentNo="md5"
request
GET http://test.fc.17shihui.com/p/order/v3/order/select/orderList?beginTime=1534089600000&endTime=1542124799999&paymentNo=md5&partner=12219&orderType=104 HTTP/1.1

response
HTTP/1.1 200 OK

if use paymentNo="md5("
request
GET http://test.fc.17shihui.com/p/order/v3/order/select/orderList?beginTime=1534089600000&endTime=1542124799999&paymentNo=md5(&partner=12219&orderType=104 HTTP/1.1

response
HTTP/1.1 504

if change naxsi_core.rules
MainRule "rx:count|length|sleep|char|ascii|hex|unhex|conv|benchmark|md5" "mz:BODY|ARGS|$HEADERS_VAR:Cookie" "s:$SQL:8" id:1021;

if use paymentNo="md5"
request
GET http://test.fc.17shihui.com/p/order/v3/order/select/orderList?beginTime=1534089600000&endTime=1542124799999&paymentNo=md5&partner=12219&orderType=104 HTTP/1.1

response
HTTP/1.1 504

naxsi.log:
2018/11/12 15:09:20 [error] 16685#0: *38368 NAXSI_FMT: ip=172.29.110.96&server=test.fc.17shihui.com&uri=/p/operate/api/agencys&vers=0.56&total_processed=6&total_blocked=4&config=block&cscore0=$CMD&score0=8&zone0=ARGS&id0=1601&var_name0=serial_number, client: 172.29.110.96, server: 10.120.180.54, request: "GET /p/operate/api/agencys?pageSize=10&serial_number=net%20user HTTP/1.1", host: "test.fc.17shihui.com", referrer: "http://test.fc.17shihui.com/serviceCenter/list
Display block log only，no display log log

**Comment by loki008** [comment]
After matching rules, there is no log record for access.log.
HTTP packet analysis using fiddler，display 504 error. if use burpSuite analysis，response is null.

**Comment by buixor** [comment]
Hello @loki008 :)

In your example, it seems you get a `504`, however, naxsi is configured to return `403` when it's triggered.

I'm not sure to understand what is the bug exactly ? From the request and your rule, the request seem to be bocked as expected. 


> After matching rules, there is no log record for access.log.
If the request is blocked, the NAXSI_FMT should end up in your error log and you won't see anything in the access log.

When the `LOG` target is triggered, you should see a `NAXSI_FMT` as well, but request isn't blocked :)


Thanks :)


PS: Please [use markdown `](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) when pasting configuration of logs for readability :)

**Comment by buixor** [comment]
Hi @loki008 

Sorry, I don't understand your last message.
Can you please provide me :
 - The version you were using (or even the git tag if it's not from releases)
 - The request that led to the crash ?

Thank you very much,

**Comment by loki008** [comment]
hi @buixor 
nginx：http://nginx.org/download/nginx-1.7.9.tar.gz 
naxsi：https://codeload.github.com/nbs-system/naxsi/zip/master

configure inaxsi.rules：CheckRule "$SQL >= 8" LOG;

if i access http://www.naxsi.com/?a=select11
wrong information：
![default](https://user-images.githubusercontent.com/42764998/48613512-eafc4d80-e9c6-11e8-8bbe-7e7b65f65c64.png)

later I change naxsi（https://codeload.github.com/nbs-system/naxsi/zip/0.56）

configure inaxsi.rules：CheckRule "$SQL >= 8" LOG;

if i access http://www.naxsi.com/?a=select11
![default](https://user-images.githubusercontent.com/42764998/48613930-fd2abb80-e9c7-11e8-85a4-da055c14a30d.png)

Is there a problem with the Naxis version or something else?
you can try.
according to nginx debug log，i discover information：
s: /tmp/naxsi-master/naxsi_src/naxsi_runtime.c:849: ngx_http_nx_log: Assertion `strlen(fmt_config) != 0' failed.
I hope you can understand this information.
Thank you very much.

**Comment by buixor** [comment]
Thanks ! I'm looking if this is a bug in master :)

**Comment by buixor** [comment]
Hello,

I was unable to reproduce from master neither, can you attempt on your side.
nginx.conf :
```
master_process off;
#worker_processes  1;
daemon off;

load_module /tmp/naxsi_ut/modules/ngx_http_naxsi_module.so;
events {
 worker_connections  1024;
 use select;
}
http {
 include /tmp/naxsi_ut/naxsi_core.rules;
 include       mime.types;
 default_type  application/octet-stream;
 sendfile        on;
 keepalive_timeout  65;
 server {
  listen 4242;
#  ssl_certificate /tmp/nginx.crt;	
#  ssl_certificate_key /tmp/nginx.key;
  server_name  localhost;
  set $naxsi_extensive_log 1;
  location / {
   LearningMode;
   SecRulesEnabled;
   DeniedUrl "/50x.html";
   CheckRule "$SQL >= 8" LOG;
   return 200;
#   error_log /tmp/ngx_error.log debug;
#   access_log /tmp/ngx_access.log;
#   root   html;
#   index  index.html index.htm;
  }
  error_page   500 502 503 504  /50x.html;
  location = /50x.html {
  return 500;
  #   root   html;
  }
 }
}


```

```
$ curl -v "localhost:4242/?foi=select+union"
> GET /?foi=select+union HTTP/1.1
> Host: localhost:4242
> User-Agent: curl/7.62.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx/1.15.5

```

Logs:
```
2018/11/23 12:13:04 [error] 19961#0: *4 NAXSI_EXLOG: ip=127.0.0.1&server=localhost&uri=%2F&id=1000&zone=ARGS&var_name=foi&content=select%2Bunion, client: 127.0.0.1, server: localhost, request: "GET /?foi=select+union HTTP/1.1", host: "localhost:4242"
2018/11/23 12:13:04 [error] 19961#0: *4 NAXSI_FMT: ip=127.0.0.1&server=localhost&uri=/&vers=0.56&total_processed=4&total_blocked=0&config=learning&cscore0=$SQL&score0=8&zone0=ARGS&id0=1000&var_name0=foi, client: 127.0.0.1, server: localhost, request: "GET /?foi=select+union HTTP/1.1", host: "localhost:4242"
```

**Comment by loki008** [comment]
2018/11/26 11:12:52 [error] 10703#0: *88231 NAXSI_FMT: ip=172.29.28.205&server=test.fc.17shihui.com&uri=/p/bankroll/v2/accounts/apply&learning=0&vers=0.56&total_processed=22&total_blocked=3&block=1&zone0=BODY&id0=20&var_name0=, client: 172.29.28.205, server: 10.120.180.54, request: "POST /p/bankroll/v2/accounts/apply HTTP/1.1", host: "test.fc.17shihui.com", referrer: "http://test.fc.17shihui.com/bankrollAccount/apply"

what is id0=20？

**Comment by loki008** [comment]
Internal rules has not id：20
how many has Internal rules？what is id？

**Comment by loki008** [comment]
which other  Internal rules are there ，besides id1, 2, 10, 11, 12, 13, 14, 15, 16, 17, 18?

**Comment by buixor** [comment]
Please see : https://github.com/nbs-system/naxsi/wiki/internal-rules

**Comment by loki008** [comment]
The last one is id:19，no id：20，I want to add all Internal rules to the whitelist, so I need all Internal rules ID number，thanks

**Comment by buixor** [comment]
sorry, I now properly documented it :)
would you  mind providing me the payload the triggered the id `20` ? I'd be curious about that, as it might be a false positive.

**Comment by loki008** [comment]
POST 'http://test.11.com/p/bankroll/v2/accounts/apply' 
'Origin: http://test.11.com' 
'Accept-Encoding: gzip, deflate' 
'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8'
'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36'
'Content-Type: application/json' 
'Accept: */*' 
'Referer: http://test.11.com/bankrollAccount/apply' 
'Cookie: PHPSESSID=e3sfs2oc8qq173pbraq8haq521; 
portal_name=006%E6%9C%8D%E5%8A%A1%E4%B8%AD%E5%BF%8302; 
wm__sess=UD%2Byxi%2B1bvmTBqHMuPyfi8ZUsy3k2Kj24pcYcH7YusGSm5VC2k8AZ%2FX42406dcZHZ%2FfUkotR%2FhqqjWh2pJel6O9YpvJw2k%2Fnk9mVZSa%2BjoyqkJS6B5cvXYJJcET5Vp%2BwkYbsqoapYS7eSR%2BqAFrXblQTvAorbyTbd91F5xdeEoA1KoNv4KCLLenllIFGJadH0KGASblFVVZePMGk4%2BZFs4G7iK8ScbmBuzq59yuPNi8QGfDaCweHTCj3uN4abPz%2FsSD8rySTmRRG3pOQeL6sEPztvlgqS0%2BzR2qtGp636R%2BYXauaP3rs980DQH9mOEW29eyK6807eELLrO3%2FarQTnbZhC6WrOkhq726PstBa5CYjle6DoNzmbTwG610%2B8vjnWwtvBxAn%2BZM8Q4zbE6Mb6ogMksu%2BMWZnTxAw2wokNHk%3D; 
token=16082384535bfb6bc314e21484742734' -H 'Connection: keep-alive' 

--data-binary $'{"cert_name":"test_zx0","cert_number":"911111111111111111","link_phone":"12201008790","bank_code":"CCB","bank_name":"\u4e2d\u56fd\u5efa\u8ace\u00f6\u884c",
"bank_branch":"\u5927\u1b81\u634f\u774cb81\u634f\u774c","bank_city":"1","undefined":"1","bank_province":"3","bank_card":"62141111021111111","cert_type":2,
"payment_password":"hangxing1","re_payment_password":"hangxing1","phone":"12201008790","sms_verify_code":"1188"}' --compressed

**Comment by loki008** [comment]
![image](https://user-images.githubusercontent.com/42764998/50372760-69c05800-060f-11e9-858f-e1721332385d.png)
Naxsi log and nginx error log are written in naxsi. log. Is there any way to separate them? 
thanks

**Comment by jvoisin** [comment]
Please use plain-text instead of screenshots for the logs.
Also, it seems that your question is unrelated to this issue, feel free to create a new one instead.
