### ISSUE TITLE
Rule 10 now aggressive ?

### ISSUE THREAD

**Issue by vladimir000** [nbs-system/naxsi#456]
Was rule 10 updated during the last year?

I've noticed it is blocking body var if some they contain for example "i'm 90% sure of that!"

I don't remember this rule causing issues in the past, is it the normal behavior ?

**Comment by buixor** [comment]
Hello,

Would you be able to provide a full http request that actually triggers the rule and that you supposed was not triggering in the past ?

Thanks,
