### ISSUE TITLE
NAXSI with phpmyadmin

### ISSUE THREAD

**Issue by wqazo** [nbs-system/naxsi#458]
I'm having trouble with phpmyadmin. It's doesn't work correct with NAXSI. How to add phpmyadmin url (sitename.com/pmx/) to whitelist?

for example:
2019/03/13 10:46:06 [error] 29841#29841: *1202 NAXSI_FMT: ip=1.1.1.2&server=1.1.2.2&uri=/pmx/js/export.js&vers=0.56&total_processed=14&total_blocked=14&config=learning&cscore0=$XSS&score0=352&zone0=HEADERS&id0=1315&var_name0=cookie, client: 1.1.1.2, server: 1.1.2.2, request: "GET /pmx/js/export.js?v=4.8.5 HTTP/1.1", host: "1.1.2.2"

Thanks!

**Comment by he2ss** [comment]
Hi wqazo,

First, you need to know, using NAXSI without doing some whitelisting will necessarily block some requests identified as suspicious following default rules. 

You can follow the [documentation](https://github.com/nbs-system/naxsi/wiki/whitelists-examples) to write whitelist rules. For your example, the whitelist is : 

```
BasicRule wl:1315 "mz:$HEADERS_VAR:cookie";
```

This rule will authorize the id `1315` on the header variable `cookie` on all URIs. If you want to limit this rule only on the targeted URI, write the rule is :

```
BasicRule wl:1315 "mz:$URL:/pmx/js/export.js|$HEADERS_VAR:cookie";
```
