### ISSUE TITLE
Change default country location from CN to something else

### ISSUE THREAD

**Issue by fernandomariano** [nbs-system/naxsi#460]
The actual python code translates from internal IPs to China (for instance, 172.18.4.237) when it fails to get the right geolocation from the GeoIP library (country_code_by_addr(ip)).  I believe that should be better to change the default value to from CN to something else (for instance, ZZ).

{'date': '2019-03-06T15:24:23+06', 'events': [{'zone': 'ARGS', 'ip': '172.18.12.136', 'uri': '/login', 'server': 'my.example.com', 'content': '', 'var_name': 'returnurl', 'coords': [37.09024, -95.712891], 'country': 'CN', 'date': '2019-03-06T15:24:23+06', 'id': '1101'}]}

    def ip2cc(self, ip):
        """ translates an IP to a country code """
        country = self.gi.country_code_by_addr(ip)
        # pun intended
        if country is None or len(country) < 2:
            country = "CN" --> "ZZ"

**Comment by buixor** [comment]
Yes I think it's a good idea, would you mind submitting a MR ? ;)

**Comment by fernandomariano** [comment]
Sure, I will do that soon.

**Comment by fernandomariano** [comment]
Hi @buixor, here is my MR - https://github.com/nbs-system/naxsi/pull/462

**Comment by buixor** [comment]
thanks ! forgot to close :)
