### ISSUE TITLE
Can't whitelist json child fields

### ISSUE THREAD

**Issue by oswaldquek** [nbs-system/naxsi#469]
I need to write a rule that will whitelist anything under a json node. So for example I want to send the following in an HTTP request body and whitelist a rule for `metadata` that will apply to any child node:
```
{
  "metadata": {
    "foo": "I'm hungry",
    "foo2": "I'm hungry"
  }
}
```
where anything under `metadata` (so `foo` and `foo2`) are user defined.
Is it possible to do this? I can't find anything in the documentation.

My current rule is `BasicRule wl:1013 "mz:$URL_X:^/v1/payments/?$|$BODY_VAR_X:metadata"` which doesn't work.

**Comment by buixor** [comment]
Hello,

Unfortunately, I don't think the json parser supports this yet, but I need to look into it, as I have already issue #457 that is somehow related.
