### ISSUE TITLE
Whitelisting a IP subnet or multiple IP addresses

### ISSUE THREAD

**Issue by tjosm** [nbs-system/naxsi#471]
I recently had some trouble with PayPal IPN. Although I have written some white-list rules, I want to make sure that any request from PayPal gets through.

I have a few IP addresses. And I came up with this code from Naxsi wiki,
`                if ($remote_addr = "173.0.81.1") {
                        set $naxsi_flag_learning 1;
                }`
This goes just above my main location block. What I want to do now is add multiple IP addresses. Can I add a comma separated list? Is a subnet like 173.0.81.0/24 supported?

Thanks in advance.

**Comment by fernandomariano** [comment]
Hi @tjosm. 

I think you can try using map directive: http://nginx.org/en/docs/http/ngx_http_map_module.html

**Comment by buixor** [comment]
@tjosm : if it's good, can you close issue ?
