### ISSUE TITLE
Custom Search page on WordPress shows 406 error with Naxsi Learning mode off. 

### ISSUE THREAD

**Issue by cshirish** [nbs-system/naxsi#472]
Hi,

I am running WordPress on Nginx and have setup NAXSI as per the instruction. For some reason when I use search functionality developed by the Author of a theme which uses the URL structure as ?mcf%5Blvl_1%5D=11&search=clear&bacs=1 the page shows 406 error.

What rule should I write to whitelist this URL?

It would be great help if you could provide a solution.

Thank you,
Shirish

**Comment by he2ss** [comment]
Hi @cshirish,

Could you please provide Naxsi error log you have when this error occurs.

**Comment by cshirish** [comment]
Hi, 

Following is the error:

Domain name I have changed to example.com

2019/05/28 17:01:11 [error] 25743#0: *6729 NAXSI_FMT: ip=157.49.162.176&server=www.example.com&uri=/market-compare/&vers=0.56&total_processed=741&total_blocked=23&config=learning&cscore0=$XSS&score0=8&zone0=ARGS|NAME&id0=1310&var_name0=mcf%5Blvl_1%5D&zone1=ARGS|NAME&id1=1311&var_name1=mcf%5Blvl_1%5D, client: 157.49.162.176, server: example.com, request: "GET /market-compare/?mcf%5Blvl_1%5D=18&search=camera&bacs=1 HTTP/2.0", host: "www.example.com", referrer: "https://www.example.com/market-compare/?mcf%5Blvl_1%5D=18&search=watch&bacs=1"
2019/05/28 17:02:30 [error] 25743#0: *6729 NAXSI_FMT: ip=157.49.162.176&server=www.example.com&uri=/market-compare/&vers=0.56&total_processed=743&total_blocked=24&config=learning&cscore0=$XSS&score0=8&zone0=ARGS|NAME&id0=1310&var_name0=mcf%5Blvl_1%5D&zone1=ARGS|NAME&id1=1311&var_name1=mcf%5Blvl_1%5D, client: 157.49.162.176, server: example.com, request: "GET /market-compare/?mcf%5Blvl_1%5D=18&search=camera&bacs=1 HTTP/2.0", host: "www.example.com", referrer: "https://www.example.com/market-compare/"

**Comment by he2ss** [comment]
Hi, 

These request is blocked because the name variable in the ARGS `mcf%5Blvl_1%5D` which triggers the 1310 & 1311 IDs.
This whitelist can resolve your issue :

```
BasicRule wl:1310,1311 "mz:$URL_X:^/market-compare|ARGS|NAME";
```

**Comment by cshirish** [comment]
After adding the above mentioned code the website is working fine. Thanks a lot :-)

**Comment by cshirish** [comment]
Hi, 

I have issue with another such URL.

your-compared-product/?compareids=4770,4756,4208,4202&cat=50&filter=avg

Following is the Error log from Nginx:

Domain changed to example.com.

2019/06/04 19:47:09 [error] 26465#0: *1 NAXSI_FMT: ip=49.206.0.78&server=www.example.com&uri=/your-compared-product/&vers=0.56&total_processed=2&total_blocked=2&config=block&cscore0=$SQL&score0=12&zone0=ARGS&id0=1015&var_name0=compareids, client: 49.206.0.78, server: example.com, request: "GET /your-compared-product/?compareids=4770,4756,4208,4202&cat=50&filter=avg HTTP/2.0", host: "www.example.com"

I tried adding the following whitelist but was unsuccessful:
BasicRule wl:1015,1310,1311 "mz:$URL_X:^/your-compared-product|ARGS|NAME";

Can you please help me?

Thank you,
Shirish

**Comment by cshirish** [comment]
Hi Guys, 

Can you please help me with a rule that can help me whitelist the URL? I have put NAXSI in learning mode until I solve this. 

Please help me

Thank you,
Shirish

**Comment by he2ss** [comment]
Hi @cshirish,

 Your rule doesn't work because of the wrong zone, you specified `ARGS|NAME` but your request is blocked because of `zone0=ARGS&id0=1015&var_name0=compareids`. It means there is a comma in your variable (compareids) content.

This rule should solve the issue :

```
BasicRule wl:1015 "mz:$URL_X:^/your-compared-product|$ARGS_VAR_X:compareids";
```
I recommend you to look at the wiki to learn how to understand NAXSI error logs and how to do a whitelist.

Thank you,
Hamza.

**Comment by cshirish** [comment]
This is working great. Thank you
