### ISSUE TITLE
Any benefit to running it on a Keycloak server?

### ISSUE THREAD

**Issue by menathor** [nbs-system/naxsi#473]
Hi all

I use naxsi on all my web servers. Recently we've set up a separate Keycloak server for SSO. nginx is  being used as a reverse proxy port 443 to Keycloak's internal port 8080.

Will naxsi block malicious attacks on the Keycloak login form? I couldn't find any information online about this.

Thanks!

**Comment by inetshell** [comment]
I'm using NAXSI to protect a Keycloak server and is working smoothly.
btw, I had to add this whilelist:

`BasicRule wl:1001,1015,1101,1205 "mz:$URL_X:^/auth/admin/realms/|BODY" "msg: Account creation";`

**Comment by menathor** [comment]
Awesome, thanks a lot!
