### ISSUE TITLE
hello  openresty use  naxsi Unable to start, error reporting  

### ISSUE THREAD

**Issue by zhangxuebao** [nbs-system/naxsi#478]
Hello, Sorry, my English is a little poor，may I ask you a question?
 openresty-1.15.8.1     use   Newest naxsi
[root@kl conf]# nginx -t
nginx: [emerg] unknown directive "MainRule" in /data/openresty/nginx/conf/naxsi_core.rules:19
nginx: configuration file /data/openresty-1.15.8.1/nginx/conf/nginx.conf test failed

Excuse me, where is my configuration error?

**Comment by zhangxuebao** [comment]
[root@kl conf]# egrep -v "^$|#" nginx.conf
worker_processes  1;
events {
    worker_connections  1024;
}
http {
    include       mime.types;
    include   /data/openresty/nginx/conf/naxsi_core.rules;
    default_type  application/octet-stream;
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
    sendfile        on;
    keepalive_timeout  65;
    server {
        listen       80;
        server_name  localhost;
        location / {
            root   html;
            index  index.html index.htm;
        }
                                 return 403;
        error_page  403  500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
}

**Comment by buixor** [comment]
Hello,

`nginx: [emerg] unknown directive "MainRule" in /data/openresty/nginx/conf/naxsi_core.rules:19` makes me thing that naxsi wasn't compiled in, or that the module has been disabled
