### ISSUE TITLE
Missing tar.gz.asc file

### ISSUE THREAD

**Issue by sant0s** [nbs-system/naxsi#479]
At https://github.com/nbs-system/naxsi/wiki/naxsi-compile, section "Get naxsi", the 3rd command line is

`wget https://github.com/nbs-system/naxsi/releases/download/$NAXSI_VER/naxsi-$NAXSI_VER.tar.gz.asc -O naxsi_$NAXSI_VER.tar.gz.asc`

but for NAXSI_VER 0.56 the URL is broken (https://github.com/nbs-system/naxsi/releases/download/0.56/naxsi-0.56.tar.gz.asc).

**Comment by buixor** [comment]
Thank you for spotting this, I fixed the sigs filenames, can you confirm it's good ?

**Comment by sant0s** [comment]
You're welcome. Link is still broken.

**Comment by buixor** [comment]
Oops, answered a bit too fast, should be good now :)
