### ISSUE TITLE
Problème to compile naxsi

### ISSUE THREAD

**Issue by forting** [nbs-system/naxsi#480]
Hello all,

I would like to compile naxsi on my debian 10 (amd64).

So i run those commands:
`apt update
apt upgrade -y
apt install build-essential libpcre3-dev zlib1g-dev
export NAXSI_VER=0.56
cd /tmp
wget https://github.com/nbs-system/naxsi/archive/$NAXSI_VER.tar.gz -O naxsi_$NAXSI_VER.tar.gz
export NGINX_VER=1.17.3
wget https://nginx.org/download/nginx-$NGINX_VER.tar.gz
tar vxf naxsi_$NAXSI_VER.tar.gz
tar vxf nginx-$NGINX_VER.tar.gz
cd nginx-$NGINX_VER
./configure --add-dynamic-module=../naxsi-$NAXSI_VER/naxsi_src/
make modules
`

So when i run ./configure:
`
checking for OS
 + Linux 4.19.0-5-amd64 x86_64
checking for C compiler ... found
 + using GNU C compiler
 + gcc version: 8.3.0 (Debian 8.3.0-6) 
checking for gcc -pipe switch ... found
checking for -Wl,-E switch ... found
checking for gcc builtin atomic operations ... found
checking for C99 variadic macros ... found
checking for gcc variadic macros ... found
checking for gcc builtin 64 bit byteswap ... found
checking for unistd.h ... found
checking for inttypes.h ... found
checking for limits.h ... found
checking for sys/filio.h ... not found
checking for sys/param.h ... found
checking for sys/mount.h ... found
checking for sys/statvfs.h ... found
checking for crypt.h ... found
checking for Linux specific features
checking for epoll ... found
checking for EPOLLRDHUP ... found
checking for EPOLLEXCLUSIVE ... found
checking for O_PATH ... found
checking for sendfile() ... found
checking for sendfile64() ... found
checking for sys/prctl.h ... found
checking for prctl(PR_SET_DUMPABLE) ... found
checking for prctl(PR_SET_KEEPCAPS) ... found
checking for capabilities ... found
checking for crypt_r() ... found
checking for sys/vfs.h ... found
checking for nobody group ... not found
checking for nogroup group ... found
checking for poll() ... found
checking for /dev/poll ... not found
checking for kqueue ... not found
checking for crypt() ... not found
checking for crypt() in libcrypt ... found
checking for F_READAHEAD ... not found
checking for posix_fadvise() ... found
checking for O_DIRECT ... found
checking for F_NOCACHE ... not found
checking for directio() ... not found
checking for statfs() ... found
checking for statvfs() ... found
checking for dlopen() ... not found
checking for dlopen() in libdl ... found
checking for sched_yield() ... found
checking for sched_setaffinity() ... found
checking for SO_SETFIB ... not found
checking for SO_REUSEPORT ... found
checking for SO_ACCEPTFILTER ... not found
checking for SO_BINDANY ... not found
checking for IP_TRANSPARENT ... found
checking for IP_BINDANY ... not found
checking for IP_BIND_ADDRESS_NO_PORT ... found
checking for IP_RECVDSTADDR ... not found
checking for IP_SENDSRCADDR ... not found
checking for IP_PKTINFO ... found
checking for IPV6_RECVPKTINFO ... found
checking for TCP_DEFER_ACCEPT ... found
checking for TCP_KEEPIDLE ... found
checking for TCP_FASTOPEN ... found
checking for TCP_INFO ... found
checking for accept4() ... found
checking for eventfd() ... found
checking for int size ... 4 bytes
checking for long size ... 8 bytes
checking for long long size ... 8 bytes
checking for void * size ... 8 bytes
checking for uint32_t ... found
checking for uint64_t ... found
checking for sig_atomic_t ... found
checking for sig_atomic_t size ... 4 bytes
checking for socklen_t ... found
checking for in_addr_t ... found
checking for in_port_t ... found
checking for rlim_t ... found
checking for uintptr_t ... uintptr_t found
checking for system byte ordering ... little endian
checking for size_t size ... 8 bytes
checking for off_t size ... 8 bytes
checking for time_t size ... 8 bytes
checking for AF_INET6 ... found
checking for setproctitle() ... not found
checking for pread() ... found
checking for pwrite() ... found
checking for pwritev() ... found
checking for sys_nerr ... found
checking for localtime_r() ... found
checking for clock_gettime(CLOCK_MONOTONIC) ... found
checking for posix_memalign() ... found
checking for memalign() ... found
checking for mmap(MAP_ANON|MAP_SHARED) ... found
checking for mmap("/dev/zero", MAP_SHARED) ... found
checking for System V shared memory ... found
checking for POSIX semaphores ... not found
checking for POSIX semaphores in libpthread ... found
checking for struct msghdr.msg_control ... found
checking for ioctl(FIONBIO) ... found
checking for struct tm.tm_gmtoff ... found
checking for struct dirent.d_namlen ... not found
checking for struct dirent.d_type ... found
checking for sysconf(_SC_NPROCESSORS_ONLN) ... found
checking for sysconf(_SC_LEVEL1_DCACHE_LINESIZE) ... found
checking for openat(), fstatat() ... found
checking for getaddrinfo() ... found
configuring additional dynamic modules
adding module in ../naxsi-0.56/naxsi_src/
 + ngx_http_naxsi_module was configured
checking for PCRE library ... found
checking for PCRE JIT support ... found
checking for zlib library ... found
creating objs/Makefile

Configuration summary
  + using system PCRE library
  + OpenSSL library is not used
  + using system zlib library

  nginx path prefix: "/usr/local/nginx"
  nginx binary file: "/usr/local/nginx/sbin/nginx"
  nginx modules path: "/usr/local/nginx/modules"
  nginx configuration prefix: "/usr/local/nginx/conf"
  nginx configuration file: "/usr/local/nginx/conf/nginx.conf"
  nginx pid file: "/usr/local/nginx/logs/nginx.pid"
  nginx error log file: "/usr/local/nginx/logs/error.log"
  nginx http access log file: "/usr/local/nginx/logs/access.log"
  nginx http client request body temporary files: "client_body_temp"
  nginx http proxy temporary files: "proxy_temp"
  nginx http fastcgi temporary files: "fastcgi_temp"
  nginx http uwsgi temporary files: "uwsgi_temp"
  nginx http scgi temporary files: "scgi_temp"
`

and when i run make modules:
`make -f objs/Makefile modules
make[1] : on entre dans le répertoire « /tmp/nginx-1.17.3 »
cc -c -fPIC -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules \
	-o objs/addon/naxsi_src/naxsi_runtime.o \
	../naxsi-0.56/naxsi_src//naxsi_runtime.c
../naxsi-0.56/naxsi_src//naxsi_runtime.c: In function ‘ngx_http_dummy_is_rule_whitelisted_n’:
../naxsi-0.56/naxsi_src//naxsi_runtime.c:728:5: error: ‘strncat’ specified bound 1 equals source length [-Werror=stringop-overflow=]
     strncat((char*)tmp_hashname.data, "#", 1);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../naxsi-0.56/naxsi_src//naxsi_runtime.c:731:3: error: ‘strncat’ specified bound 1 equals source length [-Werror=stringop-overflow=]
   strncat((char*)tmp_hashname.data, "#", 1);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [objs/Makefile:1235: objs/addon/naxsi_src/naxsi_runtime.o] Error 1
make[1] : on quitte le répertoire « /tmp/nginx-1.17.3 »
make: *** [Makefile:14: modules] Error 2
`

So how i can patch this to build naxsi ?

Thanks,
Guillaume F

**Comment by forting** [comment]
I have solved this issue by the file objs/Makefile of the nginx-VERSION folder.
So i have remove all -W.. flags of the CFLAGS option.

So if anyone have another solution?

**Comment by Christian1998** [comment]
Have same issue :/

**Comment by buixor** [comment]
Hello, what version of gcc are you using please ? it might be related to this.

**Comment by forting** [comment]
Hi,
gcc is gcc (Debian 8.3.0-6) 8.3.0
g++ is g++ (Debian 8.3.0-6) 8.3.0

**Comment by AdrianaWarlock** [comment]
same question，
gcc version 8.3.0 (Debian 8.3.0-6)

**Comment by AdrianaWarlock** [comment]
apt install gcc-6;
./configure --add-dynamic-module=../naxsi/naxsi_src
make CC=gcc-6 modules

Specify the GCC version to resolve

**Comment by forting** [comment]
sorry for my late answer but, on debian 10 gcc-6 aren't available.
I've used gcc-7 and it's works to compile naxsi module.
but gcc-8 doesn't compile.
