### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by Noctis0227** [nbs-system/naxsi#481]
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC  -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules -I src/http/v2 -I src/mail -I src/stream \
	-o objs/addon/naxsi_src/naxsi_skeleton.o \
	../naxsi/naxsi_src/naxsi_skeleton.c
In file included from /usr/include/string.h:638,
                 from src/os/unix/ngx_linux_config.h:27,
                 from src/core/ngx_config.h:26,
                 from ../naxsi/naxsi_src/naxsi.h:38,
                 from ../naxsi/naxsi_src/naxsi_skeleton.c:37:
In function 'strncpy',
    inlined from 'ngx_http_dummy_init' at ../naxsi/naxsi_src/naxsi_skeleton.c:417:3:
/usr/include/bits/string3.h:120:10: error: '__builtin_strncpy' output truncated before terminating nul copying 17 bytes from a string of the same length [-Werror=stringop-truncation]
  120 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function 'strncpy',
    inlined from 'ngx_http_dummy_init' at ../naxsi/naxsi_src/naxsi_skeleton.c:418:3:
/usr/include/bits/string3.h:120:10: error: '__builtin_strncpy' output truncated before terminating nul copying 17 bytes from a string of the same length [-Werror=stringop-truncation]
  120 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [objs/addon/naxsi_src/naxsi_skeleton.o] Error 1
make[1]: Leaving directory `/root/nginx-1.17.3'
make: *** [build] Error 2

- nginx  1.17.3
- naxsi   0.56
- centos 7

**Comment by buixor** [comment]
duplicatite of #480
