### ISSUE TITLE
BasicRule wl:0 "mz:$BODY_VAR:channelid"; Why not manifest

### ISSUE THREAD

**Issue by linkimfly** [nbs-system/naxsi#485]
#### BasicRule
```shell
BasicRule wl:0 "mz:$BODY_VAR:channelid";
```
> Set the post name equal to channelid, pass all the rules but it has no effect, it is still blocked

#### BasicRule
```shell
BasicRule wl:0 "mz:$URL_X:(^.*?article_edit.*$)|URL";
```
> Similarly, I match a certain URL and then pass all the rules. Does not take effect

> What is the correct rule?

**Comment by linkimfly** [comment]
@buixor Ask God to help me

**Comment by linkimfly** [comment]
My environment：
Centos6.9
Nginx 1.16.1

**Comment by buixor** [comment]
`BasicRule wl:0 "mz:$BODY_VAR:channelid";` It will whitelist rules, but only in the channelId post variable, is it what you meant ?

**Comment by linkimfly** [comment]
Yes, there is a parameter name = channelid in my post request, I want to let Naxsi pass and not intercept requests with parameter name = channelid
