### ISSUE TITLE
Add whitelist and blacklist of IPs incl. CIDR (netmask) + JSON output

### ISSUE THREAD

**Issue by marcinguy** [nbs-system/naxsi#486]
Hi Team,

I am using in my project currently modsecurity to filter out bad IPs and allow good ones:

Something like this:

```
   modsecurity_rules '
      SecRuleEngine On
      SecRule REMOTE_ADDR "@ipMatchFromFile /etc/modsecurity/whitelist.txt" id:1,phase:1,allow
      SecRule REMOTE_ADDR "@ipMatchFromFile /etc/modsecurity/blacklist.txt" id:2,phase:1,deny,status:429,msg:\'blacklist\'
```

What would be the best approach to add this functionality to NAXSI?

Should I add a Rule or modify the code? Can you give some tips on either one, both or none, when this is not possible (are there any performance implications or implications in general)

Any other possibility to achieve this goal in NGINX setup?

Thanks,

**Comment by marcinguy** [comment]
Decided to use this approach

############################
## Block rules: 1700-1800 ##
############################

MainRule "str:1.1.1.1" "msg:IP Blacklist" "mz:$HEADERS_VAR:X-Forwarded-For" "s:$BLACK:8" id:1701;
MainRule "str:2.2.2.2" "msg:IP Blacklist" "mz:$HEADERS_VAR:X-Forwarded-For" "s:$BLACK:8" id:1702;

Where 1.1.1.1 and 2.2.2.2 will be IP I want to block (from Blacklist) - I will generate the config/list daily.

However, I still don't know how to whitelist some IPs, so that they will never be blocked (through block rules but also through other rules). Any ideas?

Was thinking about Whitelist rule for all: 

MainRule wl:0 "mz:$HEADERS_VAR|X-Forwarded-For:xxx.xxx.xxx.xxx";

BUT it is also not a valid rule ....

What approach would you suggest?

**Comment by marcinguy** [comment]
Made a PR: https://github.com/nbs-system/naxsi/pull/488 Please take a look and let me know how I can improve it/change it.

A feature to have global Whitelist would be great.

**Comment by marcinguy** [comment]
I tried to carefully modify code not to break NAXSI, but somehow some Travis CI checks fail. 

Help to get this resolved and as I said on adding this feature would be great.

**Comment by marcinguy** [comment]
FYI Decided to use ModSecurity (for blacklist and whitelist) chained with NAXSI (need to add whitelist support and JSON output as mentioned in PR). ModSecurity was the fastest to block IP via Blacklist, also have Netmask and CIDR support. Making rules to block in NAXSI was too slow, since I had to make ca 2k rules etc. FYI ModSecuritxy + NAXSI together seem to work well.

**Comment by marcinguy** [comment]
Added this to NGINX config:

```
location / {
    SecRulesEnabled; #enable naxsi
    #LearningMode; #enable learning mode
    LibInjectionSql; #enable libinjection support for SQLI
    LibInjectionXss; #enable libinjection support for XSS

    DeniedUrl "/RequestDenied"; #the location where naxsi will redirect the request when it is blocked
    CheckRule "$SQL >= 8" BLOCK; #the action to take when the $SQL score is superior or equal to 8
    CheckRule "$RFI >= 8" BLOCK;
    CheckRule "$TRAVERSAL >= 8" BLOCK;
    CheckRule "$UPLOAD >= 8" BLOCK;
    CheckRule "$XSS >= 8" BLOCK;
    CheckRule "$BLACK >= 8" BLOCK;
```

**Comment by marcinguy** [comment]
Also use this ngrok parsing rule in DataDog to show the the Dasboard:

`myParsingrule %{date("yyyy/MM/dd HH:mm:ss"):connect_date} \[%{word:status}\] %{number:id}\#0: \*%{number:value} %{data::json}`

**Comment by marcinguy** [comment]
I am also in AWS setup behind LB, so I only care about X-Forwarded-For as being user IP.

**Comment by marcinguy** [comment]
Reformatted the PR to match original formatting in Naxsi. Easier to see what have changed. One bug is that somehow only first IP is whitelisted from /etc/nginx/whitelist.txt. Looking into it ....

**Comment by marcinguy** [comment]
Bug is fixed in latest commit, was some pesky newlines in hashmap. So this should be working now properly.

**Comment by marcinguy** [comment]
Some more relevant info:

![datadog-dashboard](https://user-images.githubusercontent.com/20355405/71809752-09148980-3071-11ea-92f4-6f443c85654b.png)

Adding Dashboard to DataDog is very easy. Above is sample Dashboard.

Also did some speed tests in comparison to ModSecurity:

https://gist.github.com/marcinguy/3a106991d3a84995efacc473f8db21a9

**Comment by buixor** [comment]
Hello,

sorry for the reply delay.
I will backlog into details later, but to answer your first question "how to whitelist IPs with naxsi", I suggest using this : 

https://github.com/nbs-system/naxsi/wiki/runtime-modifiers


```
 # Disable naxsi if client ip is 127.0.0.1
 if ($remote_addr = "127.0.0.1") {
  set $naxsi_flag_enable 0;
 }
```

It would allow you to disable naxsi or to turn learning on for some specific context (ip, cookies etc.)

**Comment by marcinguy** [comment]
@buixor Nice tip. Thanks. I would have to use howevever the ` real_ip_header X-Forwarded-For;` etc to make sure I get the user IP, not the balancer. Wondering what would be faster/more performant: Nginx config with several dozen rules (and other complexity) or whitelist.txt (hashmap approach from my PR).

So the other question would be: 
1) Efficient Blacklisting

Now I want to use ModSecurity chained with Naxsi. Any ideas for this?

**Comment by rickygm** [comment]
> Hello,
> 
> sorry for the reply delay.
> I will backlog into details later, but to answer your first question "how to whitelist IPs with naxsi", I suggest using this :
> 
> https://github.com/nbs-system/naxsi/wiki/runtime-modifiers
> 
> ```
>  # Disable naxsi if client ip is 127.0.0.1
>  if ($remote_addr = "127.0.0.1") {
>   set $naxsi_flag_enable 0;
>  }
> ```
> 
> It would allow you to disable naxsi or to turn learning on for some specific context (ip, cookies etc.)

Hi , I have this working and it works, the only thing that if the network does not work for me , for example : if ($remote_addr = "192.168.11.0/24") {

**Comment by marcinguy** [comment]
@buixor @rickygm Nice!

So the open issues are:

- Efficient Blacklisting
- JSON Output in log for DataDog digestion and possibly other systems

Can you add them to the official release? Since I don't want to work with my fork in the fear of future maintenance. 

JSON output sample:
https://github.com/nbs-system/naxsi/pull/488/files#diff-c94873dd7eede49a9d55290d07f66ef1R981

Thanks,

**Comment by marcinguy** [comment]
FYI Current logs can be parsed with more of like this rule:

`myRule %{date("yyyy/MM/dd HH:mm:ss"):date}\s\[%{word:level}\]\s%{data:token}:\s%{data:token2}\:\sip=%{data:ip}&server=%{data:server}&uri=%{data:uri}&vers=%{data:vers}&total_processed=%{data:total_processed}&total_blocked=%{data:total_blocked}&config=%{data:block}&cscore0=%{data:cscore0}&zone0=%{data:zone0}&id0=%{data:id0}&var_name0=%{data:var_name0}&zone1=%{data:zone1}&id1=%{data:id1}&var_name1=%{data:var_name1}\,\sclient:\s%{data:client},\sserver:\s%{data:serverip}\,\srequest:\s\"%{data:request}\"\,\shost:\s\"%{data:host}\".*`

But I am not sure it will catch requests that trigger several NAXSI rules i.e SQL Injection and Directory Traversal.

JSON output would solve this.

Thanks,

**Comment by rickygm** [comment]
but still, can't be added by CIDR? , 192.168.20.0/24 ?...I've lost the thread a bit, but it would be great to add a direct whitelist to the naxsi module

**Comment by marcinguy** [comment]
@rickygm @wargio Will work on adding CIDR to my changes in my last PR. Now it only supports one IP per line.

Also just realized I can do Blacklist rule faster, since in the past/last attempt I used one rule per IP. This created many rules for a CIDR, maybe I can somehow make one rule for a CIDR and than code will check the Src ip against the whole CIDR. I think that's how mod_security does it also.

**Comment by marcinguy** [comment]
https://github.com/nbs-system/naxsi/pull/507

CIDR was added in this PR. Also a bug was fixed, where fname sometimes contained garbage (weird), which would result in whitelist sometimes being added, sometimes not.

cc @wargio @rickygm

**Comment by marcinguy** [comment]
@wargio @rickygm 

I did some research on this. 

It works with Modsecurity + Naxsi since Modsecurity intercepts request in earlier phase

```
 h_preaccess = ngx_array_push(&cmcf->phases[NGX_HTTP_PREACCESS_PHASE].handlers);
```
https://github.com/SpiderLabs/ModSecurity-nginx/blob/f1a7ab6e3c3e010dbbf2cfc37ae7f81fa410dc57/src/ngx_http_modsecurity_module.c


You can use ModSecurity for Blacklist then or other module:

https://github.com/nginx/nginx/blob/master/src/http/modules/ngx_http_access_module.c

Both hook up in this phase.

Seems like Naxsi is working in this Phase:
```
 h = ngx_array_push(&cmcf->phases[NGX_HTTP_REWRITE_PHASE].handlers);
```
https://github.com/nbs-system/naxsi/blob/07a056ccd36bc3c5c40dc17991db226cb8cf6241/naxsi_src/naxsi_skeleton.c#L351

Alternatively, this could be added to Naxsi (if this makes sense to add it, since modules should be modular :) )

Closing this on my end.
