### ISSUE TITLE
Unable to download signature from naxsi tag untagged-afabfc163946baa8036f

### ISSUE THREAD

**Issue by VictorMorenoJimenez** [nbs-system/naxsi#489]
We have a Docker container with a webproxy with nginx and naxsi.

In order to compile naxsi we need to download the .sig file. It was okey till some months ago that stopped working.

We download the .sig file with:

```docker
    curl \
        -fSL \
        https://github.com/nbs-system/naxsi/releases/download/$NAXSI_TAG/naxsi-$NAXSI_VERSION.tar.gz.sig \
        -o naxsi.tar.gz.sig \
    ; \
```

Where 
```docker
ENV NAXSI_VERSION=0.56 \
    NAXSI_TAG=untagged-afabfc163946baa8036f \
    NGINX_VERSION=1.17.0
```

That download url stopped working for some reason.

Thanks for your help.

**Comment by Niemi** [comment]
Same result for me. 

> + curl -fSL https://github.com/nbs-system/naxsi/releases/download/untagged-afabfc163946baa8036f/naxsi-0.56.tar.gz.sig -o naxsi.tar.gz.sig
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
The command '/bin/sh -c set -ex ;     gpg_keys="        0xB0F4253373F8F6F510D42178520A9993A1C052F8        251A28DE2685AED4        " ;     apk add --no-cache --virtual .build-deps         curl         gnupg     ;     curl         -fSL         http://nginx.org/download/nginx-$NGINX_VERSION.tar.gz         -o nginx.tar.gz     ;     curl         -fSL         http://nginx.org/download/nginx-$NGINX_VERSION.tar.gz.asc         -o nginx.tar.gz.asc     ;     curl         -fSL         https://github.com/nbs-system/naxsi/archive/$NAXSI_VERSION.tar.gz         -o naxsi.tar.gz     ;     curl         -fSL         https://github.com/nbs-system/naxsi/releases/download/$NAXSI_TAG/naxsi-$NAXSI_VERSION.tar.gz.sig         -o naxsi.tar.gz.sig     ;         export GNUPGHOME="$(mktemp -d)" ;     gpg         --keyserver "ha.pool.sks-keyservers.net"         --keyserver-options timeout=10         --recv-keys $gpg_keys     ;     gpg --batch --verify nginx.tar.gz.asc nginx.tar.gz ;     gpg --batch --verify naxsi.tar.gz.sig naxsi.tar.gz ;     rm -rf         "$GNUPGHOME"         naxsi.tar.gz.sig         nginx.tar.gz.asc     ;     apk del .build-deps ;' returned a non-zero code: 22
make: *** [Makefile:15: image/mainline] Error 22

**Comment by Niemi** [comment]
Need to replace naxsi-0.56 signature URL in Dockerfile to:
https://github.com/nbs-system/naxsi/releases/download/0.56/naxsi-0.56.tar.gz.asc

**Comment by wargio** [comment]
@VictorMorenoJimenez i suggest you to use the release version.
