### ISSUE TITLE
Documentation error on "load_module"

### ISSUE THREAD

**Issue by HanXHX** [nbs-system/naxsi#495]
Hi,

I found a small error on your documentation (https://github.com/nbs-system/naxsi/wiki/naxsi-compile).

On Nginx doc, [load_module](http://nginx.org/en/docs/ngx_core_module.html#load_module) must be set on main context, not in http block.

Should be:
```
usr@008885ac189c:~$ cat /etc/nginx/nginx.conf
...
load_module /etc/nginx/modules/ngx_http_naxsi_module.so; # load naxsi

http {
    include /etc/nginx/naxsi_core.rules; # load naxsi core rules
    ...
}
...
```

Kind regards,

EM

**Comment by wargio** [comment]
Thanks, for that. i've fixed it.
