### ISSUE TITLE
Add blacklistd support

### ISSUE THREAD

**Issue by psa** [nbs-system/naxsi#499]
BSDs have a hook to the packet filter called blacklistd and it would be nice to be able to call that for block requests.

I'm thinking the implementation can be simple, a flag `SecRulesBlacklistd On|Off;` which enables|disables calls to blacklistd on any block action.

An example of adding blacklistd support to postfix can be found here: https://github.com/NetBSD/src/commit/3ae4028

**Comment by wargio** [comment]
Reference to blacklistd https://www.freebsd.org/doc/handbook/firewalls-blacklistd.html
