### ISSUE TITLE
Rules accept match zone of a url

### ISSUE THREAD

**Issue by christophe-freijanes** [nbs-system/naxsi#502]
Hello,

I get a lot of blockages in this game zone.
` "mz:$URL_X:^/dada/[A-Za-z0-9_]*/search|ARGS"; `

Example:
```
 BasicRule wl:1100,1101,1109,1200,1310,1311,1312,1315,1400,1401 "mz:$URL_X:^/dada/[A-Za-z0-9_]*/tools/ranking|$BODY_VAR_X:url"; 
 BasicRule wl:1000,1001,1005,1006,1007,1008,1009,1010,1011,1013,1015,1016 "mz:$URL_X:^/dada/[A-Za-z0-9_]*/track/alerts/content-extract-url|$ARGS_VAR_X:url"; 
```
I've been thinking about making that rule

`#MainRule "str:https://" "msg:https:// scheme" "mz:$URL_X:^/dada/[A-Za-z0-9_]*/*URL|BODY|NAME|ARGS|$HEADERS_VAR:Cookie" "s:$RFI:8" id:4202;`

I'd like to create a rule that would allow me to accept all my regex requests before and after /dada/.

Can you rescue me?

**Comment by wargio** [comment]
can you make a few examples of urls that are blocked and that you want to allow?

**Comment by christophe-freijanes** [comment]
I would like to allow all requests before and after /dada/ e.g. all regex before and after: https://www.monsite.com/dada/

**Comment by wargio** [comment]
ok then the rule should be defined like this:

`BasicRule  wl:xxxx,yyyy,zzzz "mz:$URL_X:^/dada/(.*)?|ARGS|NAME|URL|...";`

but if the issue is related to something similar to backoffice, admin panel, etc.. i suggest to disable naxsi completely by having rules on nginx on where to include/activate naxsi

**Comment by christophe-freijanes** [comment]
Ok thank you for your responsiveness I will test this ;)

**Comment by christophe-freijanes** [comment]
Resolving.
