### ISSUE TITLE
Very high cpu usage without LearningMode

### ISSUE THREAD

**Issue by kanitan** [nbs-system/naxsi#509]
When doing stress testing, I found Naxsi performs very well when in Leaning Mode.But when I turned to block mode and CPU usage starts to go up to almost 100%. Is there any wrong in my configuration or any key steps before enable block mode?

location{}:
```
SecRulesEnabled;
#LearningMode; 
LibInjectionSql; 
LibInjectionXss; 
DeniedUrl "/RequestDenied"; 
CheckRule "$SQL >= 8" BLOCK;
CheckRule "$RFI >= 8" BLOCK;
CheckRule "$TRAVERSAL >= 5" BLOCK;
CheckRule "$UPLOAD >= 5" BLOCK;
CheckRule "$XSS >= 8" BLOCK;
error_log /var/log/naxsi_audit.log;
include naxsi/*.wl;
```

http{}:
```
include /etc/nginx/naxsi/naxsi_core.rules;
```

**Comment by wargio** [comment]
Hello, thanks for the bug report. can you try to use the eb66a60f2150c52477d2a4ca2b776c7602773771 version ?
