### ISSUE TITLE
Remove old badges and create new release?

### ISSUE THREAD

**Issue by marcinguy** [nbs-system/naxsi#516]
Hi,

2 questions:

1) Is there any use of old badges, they seem to be not actual, recent:

https://scan.coverity.com/projects/1883
https://codecov.io/github/nbs-system/naxsi?branch=master
https://coveralls.io/github/nbs-system/naxsi?branch=master

Maybe they can be removed to clean up the README.md

I think the above will also show the project is taken care of. Not that it isn't :)

2) Can a new release be made? Maybe that way packages by Ubuntu/Debian will be also updated.

Will show the project is taken care of, new features release (WhitelistFile, JSON logs output)

For 1) I can make a PR when needed.

Thanks,

**Comment by wargio** [comment]
has been a while since a release was done and with your contribs we should definetely do this, but i can't because i need to wait a go internally before doing one. yes it sound stupid and it is stupid.
