### ISSUE TITLE
Unable to download signature from naxsi tag 1.0

### ISSUE THREAD

**Issue by Hubok** [nbs-system/naxsi#518]
`wget https://github.com/nbs-system/naxsi/releases/download/$NAXSI_VER/naxsi-$NAXSI_VER.tar.gz.asc -O naxsi_$NAXSI_VER.tar.gz.asc`

Just a 404 error, looks like this file isn't in the release assets.

**Comment by wargio** [comment]
there is none. i didn't have time to sign it yet. maybe tomorrow i'll add it.

**Comment by wargio** [comment]
fixed.
