### ISSUE TITLE
Change Naxsi version defined in headers per branch/release and used in logs

### ISSUE THREAD

**Issue by marcinguy** [nbs-system/naxsi#520]
Hi,

It seems even the 1.0 release is using 0.56 version info in the logs

Could be confusing:

Maybe this can be changed per release:

https://github.com/nbs-system/naxsi/blob/a8dd4816460314c511f1fd3a322d882dbc2fb9db/naxsi_src/naxsi.h#L10

I can open PR to master for Version 1.1 pre-release for it.

Please let me know.

Thanks,

**Comment by wargio** [comment]
yes please.

**Comment by wargio** [comment]
fixed.

**Comment by wargio** [comment]
release & tag also updated. thanks again.
