### ISSUE TITLE
Bump libinjection version. 

### ISSUE THREAD

**Issue by wargio** [nbs-system/naxsi#523]
might break a lot of things, but is a good idea to update it to the latest version: https://github.com/client9/libinjection

**Comment by marcinguy** [comment]
@wargio Seems like this is the new repo for Libinjection:
https://github.com/libinjection/libinjection

Fixes should be there. Some are already fixed. 

See this:
https://portswigger.net/daily-swig/amp/libinjections-sql-injection-defenses-cracked
