### ISSUE TITLE
Whitelist PDFs files with regex

### ISSUE THREAD

**Issue by tdefise** [nbs-system/naxsi#531]
Dear NAXSI Team,

We are currently facing an issue where we want to whitelist a specific(s) URL that points to PDFs files.
URL are for instance: 

- /images/Kudu\ServiceMail\2020\UpdateNationality_nl_15092020.pdf

We tried to created both folowing whitelist rules which didn't work:

- BasicRule wl:1000 "mz:$URL_X:^\/images\/Kudu\\ServiceMail\\2020\\UpdateNationality_(.*)\.pdf$|URL";
- BasicRule wl:1205 "mz:$URL_X:^\/images\/Kudu\\ServiceMail\\2020\\UpdateNationality_(.*)\.pdf$|URL";

We had the following issue:
Reloading nginx configuration: nginx: [emerg] Naxsi-Config : Incorrect line BasicRule wl:1000 (../naxsi 0.55.3/naxsi_src//naxsi_skeleton.c/474)... 
in /etc/nginx/naxsi.rules:104 nginx: configuration file /etc/nginx/nginx.conf test failed

Thanks in advance, 
Thomas

**Comment by wargio** [comment]
if solved, please close the issue.

**Comment by tdefise** [comment]
Hello @wargio,

First, let me thanks you for your help.
We tried with the syntax you gived but we have the same error :/

Thomas,

**Comment by wargio** [comment]
@tdefise ok, i think i found the issue. the `\\` gets simplified to `\` by nginx, but in reality you need a `\\` in the regex, so for those rules, you need to use `\\\\`. 

the main issue is that it tries to compile the regex `\U` which is not acceptable by the regex compiler. 

```
BasicRule wl:1000 "mz:$URL_X:^/images/Kudu\\\\ServiceMail\\\\2020\\\\UpdateNationality_(.*).pdf$|URL";
BasicRule wl:1205 "mz:$URL_X:^/images/Kudu\\\\ServiceMail\\\\2020\\\\UpdateNationality_(.*).pdf$|URL";
```

**Comment by tdefise** [comment]
Thanks a lot @wargio, it solved our issues.
Thanks also for notify me about the version.

**Comment by wargio** [comment]
Thanks for using naxsi.
