### ISSUE TITLE
Add a "peer" filter to nxapi

### ISSUE THREAD

**Issue by gbwebdev** [nbs-system/naxsi#533]
Hi,

Thanks a lot for naxsi and nxapi.

It would be very nice to add a "peer" filter to nxapi.
I have a static IP address at home, and I'am absolutly sure that all requests coming from this IP are safe.
So it would be nice to be able to filter on this IP when generating whitlists.

Thanks !

**Comment by wargio** [comment]
Hi, yes this could be a nice improvement. in the meantime i suggest as workaround to just use `cat <mylogfile.log> | grep -v "1\.2\.3\.4" > mynewlogfile.log`

**Comment by gbwebdev** [comment]
Thank you for the workaround !
And again, thanks for the great work.
