### ISSUE TITLE
Why abandon nx_util

### ISSUE THREAD

**Issue by sule01u** [nbs-system/naxsi#540]
I looked it up and I couldn't see why I wanted to drop nx_util, which makes it a little bit easier to do

**Comment by wargio** [comment]
we never said we want to drop nx_utils

**Comment by BigTree975** [comment]
> 我们从未说过要删除nx_utils

Naxsi is now using nxapi to generate whitelist instead of using nx_util, I just want to know what's different, because I'm going to consider whitelist generation using the older version of nx_util, is there any problem?

**Comment by wargio** [comment]
NXAPI is the tool you can use to graphically see the blocked requests.
nx_tools are a set of tools to generate the whitelist.

**Comment by BigTree975** [comment]
https://github.com/nbs-system/naxsi/issues/191
<img width="1330" alt="截屏2020-12-18 18 02 14" src="https://user-images.githubusercontent.com/33783361/102601550-47f4ff80-415b-11eb-9c0b-1b24d4c35f17.png">

<img width="787" alt="截屏2020-12-18 18 05 04" src="https://user-images.githubusercontent.com/33783361/102601819-a621e280-415b-11eb-822b-f59a4469642c.png">

我想问的是nx_util.py为什么不建议使用，是否我的话有歧义

**Comment by wargio** [comment]
i do not see why it should be deprecated. i anyway suggest to use NXAPI for writing rules, because you will have the situation under control.
