### ISSUE TITLE
LOG checkrule causing assert

### ISSUE THREAD

**Issue by HughePaul** [nbs-system/naxsi#541]
We've been having nginx processes crashing under load with the the following error:
```
2020/12/16 07:48:59 [alert] 1108#0: worker process 1114 exited on signal 6
../naxsi/naxsi_src/naxsi_runtime.c:825: ngx_http_nx_log: Assertion `strlen(fmt_config) != 0' failed.
```

On low load the process crashes after the end of the request, but on high load it kills other requests in flight on the same nginx process.

Rules configuration:
```
CheckRule "$LIBINJECTION_SQL >= 8" LOG;
checkRule "$LIBINJECTION_XSS >= 8" LOG;
```

There doesn't seem to be anything to handle a case of only the log score being reached
```
const char* fmt_config = "";

  if (ctx->learning) {
    fmt_config = ctx->drop ? "learning-drop" : "learning";
  } else if (ctx->drop) {
    fmt_config = "drop";
  } else if (ctx->block) {
    fmt_config = "block";
  } else if (ctx->ignore) {
    fmt_config = "ignore";
  }
```

And so it asserts and kills the nginx process
```
  assert(strlen(fmt_config) != 0);
```

I'm aware that this is not the latest code, but I can't see any changes in code that would prevent this

**Comment by wargio** [comment]
sorry about that. i have missed it when i changed the behaviour.
