### ISSUE TITLE
Naxsi rule to block XXE

### ISSUE THREAD

**Issue by cyndy08** [nbs-system/naxsi#542]
Hello everybody,

i am currently writing my bachelor thesis on web application Firewalls. For this i have to test a few open source WAFs and then compare them. I chose Modsecurity and Naxsi for my work. I am currently trying to write a rule to block XXE (XML External Entities). For example if i upload the following code it should be blocked by the waf and not executed:

` <?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE foo [
<!ELEMENT foo ANY >
<!ENTITY xxe SYSTEM "file:///etc/passwd" >]>
<foo>&xxe;</foo> `

i also add a checkrule: CheckRule "$XXE >= 4" BLOCK;

I tried with this rule but it not working: MainRule "rx:Entity|System" "msg:XML Entity detected" "mz:ARGS|URL|BODY|$HEADERS_VAR:Cookie" "s:$XXE:4" id:1700. It seems like  the uploaded file is not beeing expected by naxsi.

I write a rule to block the upload of xml.files and it works. But if i upload the xml file using curl -d , it doesnt work anymore and the XXE attack successes.

Any suggestion will be really appreciated.#
Thank you

**Comment by wargio** [comment]
remove the `|$HEADERS_VAR:Cookie`
i would also split the rule in 2 sets

```
MainRule "str:Entity" "msg:XML Entity detected" "mz:ARGS|URL|BODY" "s:$XXE:4" id:1700;
MainRule "str:System" "msg:XML System detected" "mz:ARGS|URL|BODY" "s:$XXE:4" id:1701;
```

**Comment by cyndy08** [comment]
Thank you  for your suggestion.  It still doesnt work with these rules. It seems like Naxsi is not able to read the content of the file that is uploaded.

**Comment by wargio** [comment]
oh, i know why. you need to use `RAW_BODY`.
```
MainRule "str:Entity" "msg:XML Entity detected" "mz:RAW_BODY" "s:$XXE:4" id:1700;
MainRule "str:System" "msg:XML System detected" "mz:RAW_BODY" "s:$XXE:4" id:1701;
```

**Comment by cyndy08** [comment]
It still doesn't work.  The XXE attack succeed. 
Is it anyway to see debug informations?

**Comment by wargio** [comment]
can you show me what the content of the request looks like? so i know what you are doing.
and also logs from nginx

**Comment by cyndy08** [comment]
I  have a php file on a webserver with following content:
```
<?php 
    libxml_disable_entity_loader (false);
    $xmlfile = file_get_contents('php://input');
    $dom = new DOMDocument();
    $dom->loadXML($xmlfile, LIBXML_NOENT | LIBXML_DTDLOAD);
    $creds = simplexml_import_dom($dom);
    $userid = $creds->userid;
    echo "You have logged in as user $userid";
?> 
````
Then i upload this xml file  as argument to run the php code:
````
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE foo [
<!ELEMENT foo ANY >
<!ENTITY xxe SYSTEM "file:///etc/passwd">]>
<creds>
    <userid>&xxe;</userid>
</creds>
````
To send the request i use: 
```` curl -d  @attack.xml -D header.txt http://ip/DVWA/hackable/uploads/xxe.php````
I expected the waf to block this POST-request, like ModSecurity did.  Since the request is not blocked there is no Logs from nginx in the error-log file. In the acces.log file i have:
```` ip - - [04/Jan/2021:10:48:17 -0800] "POST /DVWA/hackable/uploads/xxe.php HTTP/1.1" 200 2746 "-" "curl/7.72.0" ````

I hope you can understand what  i did.

Thank you

**Comment by wargio** [comment]
whats your configuration?

**Comment by cyndy08** [comment]
Which configuration? You mean my nginx.conf file?

**Comment by cyndy08** [comment]
hello @wargio , could you find something useful from the configuration files?

**Comment by wargio** [comment]
looks like you haven't enabled naxsi in the `*.php$` location and also in the `/` location.
please check the wiki: https://github.com/nbs-system/naxsi/wiki/naxsi-setup#example-configuration
You are missing `SecRulesEnabled`, `DeniedUrl` and `CheckRule` are required **per location**

**Comment by cyndy08** [comment]
I have already included ````/etc/nginx/naxsi.rules````  in ````/```` location and this file defines ````SecRulesEnabled````, ```DeniedUrl``` and ``CheckRule``. So it is basicall the same. This my naxsi.rules  file:
````
SecRulesEnabled;
DeniedUrl "/error.html";
CheckRule "$SQL >= 8" BLOCK;
CheckRule "$RFI >= 8" BLOCK;
CheckRule "$TRAVERSAL >= 4" BLOCK;
CheckRule "$EVADE >= 4" BLOCK;
CheckRule "$XSS >= 8" BLOCK;
CheckRule "$UPLOAD >= 8" BLOCK;
CheckRule "$SCANNER >= 4" BLOCK;
CheckRule "$XML >= 4" BLOCK;
CheckRule "$XXE >= 4" BLOCK;
````

**Comment by wargio** [comment]
if you use naxsi on an reverse proxy (RP), the web server behind the RP will never see the request.
i would suggest to enable json logs (because it's easier to read them) and use also NXAPI for visualizing the data produced by naxsi.

Everything is explained on the wiki.
