### ISSUE TITLE
Supported protocols in Naxsi

### ISSUE THREAD

**Issue by cyndy08** [nbs-system/naxsi#543]
Hello everyone,

i would like to know if Naxsi supports other protocols than HTTP like FTP, DNS , LDAP or anything else. And also which HTPP-versions are supported by naxsi?

I could not find any information regarding this in the documentation.

Thank you

**Comment by wargio** [comment]
I'm sorry but this question makes no sense.
Naxsi is a web application firewall, not a firewall nor a deep packet inspection tool.
Naxsi knows only what a HTTP request is and [FTP](https://tools.ietf.org/html/rfc959), [DNS](https://tools.ietf.org/html/rfc1035) and [LDAP](https://tools.ietf.org/html/rfc4511) does not use [HTTP](https://tools.ietf.org/html/rfc7231).
- FTP is an old text based protocol.
- DNS is binary based.
- LDAP is a ASN.1 based protocol, usually DER encoded.

also Naxsi is a NGINX module, this means that he does not handle HTTP request/connections, but NGINX does, so Naxsi does support whatever HTTP version NGINX supports.
