### ISSUE TITLE
Rules default does not contain Match Pattern and MatchZone

### ISSUE THREAD

**Issue by vncloudsco** [nbs-system/naxsi#556]
https://github.com/nbs-system/naxsi/blob/0395b102b7e9b5165e89e99bb62e9ddaa0a74910/naxsi_config/naxsi_core.rules#L4-L16

I'm implementing the system and having trouble with these rules I don't know what rules doing. What data do rules look for and what is their search Match Pattern? 

How can I edit these data, or know what this rules  doing search?

I don't know how it works yet, my system is pretty much blocked by this rules.

**Comment by vncloudsco** [comment]
the same log:

```
2021/04/13 16:06:50 [error] 19204#19204: *331882 NAXSI_FMT: ip=x.x.x.x&server=x.x.x.x&uri=/11111111/newTeaser&vers=1.3&total_processed=152&total_blocked=9&config=block&zone0=BODY&id0=11&var_name0=, client: x.x.x.x, server: x.x.x.x, request: "POST /11111111/newTeaser HTTP/2.0", host: "x.x.x.x", referrer: "https://x.x.x.x"
```

**Comment by wargio** [comment]
These are hardcoded rules and they are always present unless you whitelist them globally. you have to deep dive in the C code to modify them

**Comment by vncloudsco** [comment]
I know that, but why are these rules not mentioned in the program document? and then it also doesn't show blocked value like normal rules.?

**Comment by wargio** [comment]
https://github.com/nbs-system/naxsi/wiki/internal-rules

**Comment by wargio** [comment]
BODY is body values and raw body
