### ISSUE TITLE
Does Naxsi work with mongo?

### ISSUE THREAD

**Issue by anthugo** [nbs-system/naxsi#557]
I need to use it on a system that use mango, but does it work fine with mongo DB?

**Comment by wargio** [comment]
?I don't get your question. you want to put naxsi between the frontend and the backend?

**Comment by anthugo** [comment]
Nope, sorry my question was really bad formulate. i wanted to ask if naxsi can detect injection on mongo? Because mango is not based on SQL (like mariaDB, SQLlite,...), and the injection "pattern" are not the same.

**Comment by wargio** [comment]
as is no, but you can always do input sanitization via its rules

**Comment by wargio** [comment]
but you need to manually write them

**Comment by anthugo** [comment]
Okay thanks. I will try :).
