### ISSUE TITLE
Enable naxsi error.

### ISSUE THREAD

**Issue by sajjadjafaribojd** [nbs-system/naxsi#558]
Hi everyone. I installed nginx 1.20.0 and compiled from source. then created dynamic module from naxsi and loaded in to nginx.conf.

`load_module modules/ngx_http_naxsi_module.so;
`

`include /etc/nginx/naxsi/naxsi_core.rules; # load naxsi core rules
`

Then I entered the following code snippet here:

> location / {
>         #Enable naxsi
>         SecRulesEnabled;
> 

But when restarting nginx, the following error is displayed:

`nginx: [emerg] Missing DeniedURL, abort. in /etc/nginx/nginx.conf:115
`

`nginx: configuration file /etc/nginx/nginx.conf test failed`

Someone can help me solve the problem.

**Comment by wargio** [comment]
you need to define a DeniedURL.

```
server {
    listen ...;
    server_name  ...;
    location / {
        #Enable naxsi
        SecRulesEnabled;
        #Enable learning mode
        LearningMode;
        #Define where blocked requests go
        DeniedUrl "/MyDeniedRequestPath";  # <-------------------------------------------- THIS
        #CheckRules, determining when naxsi needs to take action
        CheckRule "$SQL >= 8" BLOCK;
        CheckRule "$RFI >= 8" BLOCK;
        CheckRule "$TRAVERSAL >= 4" BLOCK;
        CheckRule "$EVADE >= 4" BLOCK;
        CheckRule "$XSS >= 8" BLOCK;
        #naxsi logs goes there
        error_log /.../foo.log;
        ...
    }
    #This is where the blocked requests are going
    location = /MyDeniedRequestPath { # <------------------------------------ AND THIS
        return 403;
    }
}
```
