### ISSUE TITLE
Block Wordpress POST Request

### ISSUE THREAD

**Issue by sajjadjafaribojd** [nbs-system/naxsi#569]
Hi. I use Naxsi with Nginx.
I loaded the rules related to WordPress with out any problem.
I get a 403 error when I try to insert or edit a post. Naxsi blocked it.
The following value is recorded in the logs.

`NAXSI_FMT: ip=3.181.87.59&server=domain.ir&uri=/wp-admin/admin-ajax.php&vers=1.3&total_processed=316&total_blocked=1&config=block&zone0=BODY&id0=2&var_name0=, client: 3.181.87.59, server: domain.ir, request: "POST /wp-admin/admin-ajax.php HTTP/2.0", host: "domain.ir", referrer: "https://domain.ir/wp-admin/post.php?post=343&action=edit" NAXSI_FMT: ip=3.181.87.59&server=domain.ir&uri=/wp-admin/post.php&vers=1.3&total_processed=317&total_blocked=2&config=block&zone0=BODY&id0=2&var_name0=, client: 3.181.87.59, server: domain.ir, request: "POST /wp-admin/post.php HTTP/2.0", host: "domain.ir", referrer: "https://domain.ir/wp-admin/post.php?post=343&action=edit"`

No IDs and cscore types are seen.
How do I fix this problem?

**Comment by wargio** [comment]
you have 2 choices: you either whitelist the IP via IgnoreIP or whitelist the id based on the content.

**Comment by sajjadjafaribojd** [comment]
thank you so much.
I created whitelist and solve problem temporary.
