### ISSUE TITLE
naxsi whitelist rules on domain vhost

### ISSUE THREAD

**Issue by vncloudsco** [nbs-system/naxsi#570]
I'm using the software on a load balancer server that contains multiple vhosts, How do I whitelist only a specific domain in a file whitelist? I don't want to use each vhost to have a separate whitelist file, I want to merge them, is it possible? Currently I am configuring whitelist for all domains but there is a problem that domains have different api systems, so it is not possible to apply all the same rules to all domains.

**Comment by wargio** [comment]
i do not understand what you mean with "whitelist a domain", but you can create a file, fill it with whatever you need and use the NGINX directive `include`
