### ISSUE TITLE
is Naxsi will work for gRPC request? 

### ISSUE THREAD

**Issue by pandey-adarsh147** [nbs-system/naxsi#575]
Curious to know, we are exploring WAF which can work in gRPC request. Most of the WAF like ModSecurity not able to analyse grpc request body. Any suggestion.

**Comment by wargio** [comment]
Potentially it could via RAW_BODY rules, but it will be a pain to maintain, and configure due the protocol buffer encoding.
I would not suggest to use NAXSI for this usage
