### ISSUE TITLE
Delete the issue

### ISSUE THREAD

**Issue by cuper6** [nbs-system/naxsi#578]
Please delete (not only close) the issue #577 https://github.com/nbs-system/naxsi/issues/577
It does not relate to Naxsi and showed  in my Contribution History at Profile (
Thank you!

P.S. Of course this issue should be deleted (not only closed) too.

**Comment by wargio** [comment]
GH does not allow deleting issues.

**Comment by cuper6** [comment]
https://docs.github.com/en/issues/tracking-your-work-with-issues/deleting-an-issue
