### ISSUE TITLE
Delete the issues (it’s possible!)

### ISSUE THREAD

**Issue by cuper6** [nbs-system/naxsi#579]
Please delete the issues https://github.com/nbs-system/naxsi/issues/577 https://github.com/nbs-system/naxsi/issues/578
How to delete an issue at GitHub:
https://docs.github.com/en/issues/tracking-your-work-with-issues/deleting-an-issue

This issue should also be deleted.
Thank you!

**Comment by vncloudsco** [comment]
i think it should not be deleted! You should leave it for later people to refer to

**Comment by cuper6** [comment]
Those issues are not related to naxsi.

**Comment by vncloudsco** [comment]
@cuper6 Unfortunately github does not allow such permission, you can close it but not delete it
