### ISSUE TITLE
"invalid hex encoding, null bytes" false positive when GET request contains a %23

### ISSUE THREAD

**Issue by st3rk** [nbs-system/naxsi#583]
Hello,

It seems a GET request containing a percent-encoded hash character triggers the intenal rule 10 : 

`curl 'https://XXXXXX/recherche?text=%23'`

`2022/02/02 11:38:53 [error] 86824#100306: *112264519 NAXSI_FMT: ip=82.65.XX.XX&server=XXXXXX&uri=/recherche&vers=1.3&total_processed=100814089&total_blocked=4077&config=learning&cscore0=$policy493e02f284124f009ea1acd5a077a378&score0=8&zone0=ARGS&id0=1016&var_name0=text, client: 82.65.170.67, server: XXXXXX, request: "GET /recherche?text=%23 HTTP/1.1", host: "XXXXXX"`

It doesn't happen with any other percent-encoded special character. Is it an expected behaviour? Is there any workaround that doesn't imply to whitelist entirely the rule 10?

**Comment by wargio** [comment]
ehm, no, it does not trigger rule `10` but rule `1016` (https://github.com/nbs-system/naxsi/blob/master/naxsi_config/naxsi_core.rules#L39)

```
ip=82.65.XX.XX
server=XXXXXX
uri=/recherche
vers=1.3
total_processed=100814089
total_blocked=4077
config=learning
cscore0=$policy493e02f284124f009ea1acd5a077a378
score0=8
zone0=ARGS
id0=1016
var_name0=text, client: 82.65.170.67, server: XXXXXX, request: "GET /recherche?text=%23 HTTP/1.1", host: "XXXXXX"
```

**Comment by st3rk** [comment]
My bad, wrong grep pattern, I'm closing the issue.
