### ISSUE TITLE
Redirect URL based on certain checkrule

### ISSUE THREAD

**Issue by Taymindis** [nbs-system/naxsi#591]
Hi, 

I am just wondering any other way to `redirect URL OR multiple Denied URL` based on certain rule? Instead of one deniedURL for all

**Comment by wargio** [comment]
why would you need such feature? can you explain your scenario where this could be useful?

**Comment by Taymindis** [comment]
We have a scenario which handle some special case of security and proxy to another data analysis service. I wish naxsi can have a feature to handle individual deniedUrl

**Comment by wargio** [comment]
Hmm sounds like a good feature. i'm adding this to the list of TODOs.

**Comment by wargio** [comment]
This could be implemented using some tags:
```
DeniedURL "/path/to/403.html";
DeniedURL "/different/path" MYTAG1;

CheckRule "$FOO > 8" DROP; # redirects using default route;
CheckRule "$MALICIOUS > 8" DROP MYTAG1; # redirects using MYTAG1 route;
```

**Comment by Taymindis** [comment]
You actually can just return status, we will handle error by ourself

**Comment by wargio** [comment]
i see, but that is not how it works internally.

**Comment by Taymindis** [comment]
> i see, but that is not how it works internally.

Ya I can see that, it’s quite different with modsecurity.
