### ISSUE TITLE
libinjection issue

### ISSUE THREAD

**Issue by eilandert** [nbs-system/naxsi#602]
Hi @wargio 

Thanks for creating the new repo.

I was not able to make debian packages, the build fails on libinjection. I removed libinjection from the tree and copied the last git version from https://github.com/libinjection/libinjection, after that it went smoothly.

Hopefully my build will be tested soon, if there are any issues, we will let you know.

note: the issues on the new repo are turned off so I noted it here.

**Comment by wargio** [comment]
nice to know, did you git submodule init ?

**Comment by eilandert** [comment]
Oh didn't think of that duh, I've a buildsystem which should take care of that. Haven't had a problem with the originally naxsi so it slipped my mind. Will try it soon.

I'm very happy that we can compile NGINX with pcre2 now.

By the way, our packages are on https://deb.myguard.nl/nginx-modules/ (and https://launchpad.net/~eilander/+archive/ubuntu/nginx), if the tests are ok I'll build a new release with the new naxsi included.

test-packages are being built and uploaded as we speak on http://edge.deb.myguard.nl:8888/pool/main/n/nginx/

**Comment by wargio** [comment]
Nice, if you want you can submit a PR with the missing files to build a deb file within naxsi

**Comment by wargio** [comment]
also the origina naxsi had embedded the libinjection files as copies, since we are in 2022 i thought to just use git features which allows to fix any possible vulnerability by just updating commits of the libinjection repository
