### ISSUE TITLE
Integrate into AbuseIPDB.com?

### ISSUE THREAD

**Issue by JSuenram** [nbs-system/naxsi#608]
Maybe a feature request.
You can integrate Fail2Ban with AbuseIPDB.

Would it be possible to also integrate NAXSI with AbuseIPDB? So you can report IPs which misbehave instead of additional to local ban them?

**Comment by wargio** [comment]
i guess is possible but you need a connector to parse naxsi logs to send them to AbuseIPDB

**Comment by JSuenram** [comment]
> i guess is possible but you need a connector to parse naxsi logs to send them to AbuseIPDB

yes, sounds like. how can this be done? parse the logs and simply run a script when keywords are found?
Using nginx with naxsi on opnSense, not sure what can be done there without breaking thinks...
