### ISSUE TITLE
Need help with understanding and installation of nxapi and nxtool

### ISSUE THREAD

**Issue by tejasvaidya01** [nbs-system/naxsi#610]
I have been trying to install nxtool and I found two different versions. Which one is latest/up-to-date and what is the difference between the two. As far I understand both of them can only support ES 5.x server and client. I am using Ubuntu 20.
   1. sudo apt-get install elasticsearch=5.6.16

**naxsi/nxapi** (https://github.com/nbs-system/naxsi/tree/master/nxapi)
    1. I was able to install it with python 2.7 and get it to work but python 3.8 gives error(Not supported yet?). Following are the steps I followed.
    2. sudo add-apt-repository universe
    3. curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
    4. sudo python2.7 get-pip.py
    5. pip2 install elasticsearch==5.5.3
    6. pip2 install geoip
    7. sudo python ./setup.py install
    8. ./nxtool.py -c nxapi.json --files=/var/log/nginx/error.log
    9. ./nxtool.py -c nxapi.json -x
    10. Works fine.

**nxtool-ng and nxapi-ng** (https://github.com/nbs-system/nxtool-ng which also installs https://github.com/nbs-system/nxapi-ng/)
    1. I have have tried installing it with python 2.7 and python 3.8
    2. pip2 install -r ./requirements-v5.txt
    3. pip2 install geoip
    4. pip2 install maxminddb-geolite2==2018.703
    5. Fails to install due to GeoIPCity.dat not available. Which probably requires some code modification as given here [#455](https://github.com/nbs-system/naxsi/issues/455)
    6. python nxtool.py --elastic-dest --flat-file /var/log/nginx/error.log
    `Invalid database type GeoIP City Edition V6, Rev 1, expected GeoIP City Edition, Rev 1
Traceback (most recent call last):
  File "/home/test/nxtool-ng/nxtool/log_providers/flat_file.py", line 28, in __init__
    ftype = mimetypes.guess_all_extensions(self.fname)[0]
IndexError: list index out of range
`
   8. python nxtool.py --elastic-source --stats [This throws more errors]
   
Any help is appreciated. Thanks in advance.

**Comment by wargio** [comment]
nxapi is very broken. do not use it, create rules by hand.

**Comment by tejasvaidya01** [comment]
Thanks for a quick reply. 

1. Maybe the documentation should be updated saying that nbs-system/naxsi is no longer up to date, it's really difficult for new users to understand what's going on here.
2. I'll try out wargio/naxsi.
    1. Is it safe to use and are you planning to keep it up to date in future?
    2. Any specific timeline for bringing back nxapi with python3.8 and will it support latest version of ES and GeoIP? I am not an expert in python but I could help testing it.
3. Could you suggest any open source alternatives for naxsi which are up to date?
