### ISSUE TITLE
[emerg] unknown directive "MainRule"

### ISSUE THREAD

**Issue by rickygm** [nbs-system/naxsi#612]
Hi , I am testing with your wargio/naxsi fork  and I get an error when I test nginx 

The first one: when I compile with nginx/1.22.0 version and do a test I get a message:

`nginx: [emerg] unknown directive "MainRule" in /etc/nginx/naxsi_core.rules:21`

any ideas?

**Comment by wargio** [comment]
are you sure that you have loaded naxsi?

**Comment by rickygm** [comment]
yes , its loaded 

`nginx -V 2>&1 | tr ' '  '\n' | grep naxsi
--add-dynamic-module=/rpm/naxsi/naxsi_src`

**Comment by wargio** [comment]
where do you load it?

**Comment by rickygm** [comment]
sorry , I didn't put part of the nginx.conf config

`user              nginx;
worker_processes  auto; # uso un core de 2 que tengo en esta vm
worker_cpu_affinity auto;

error_log  /var/log/nginx/error.log;

pid        /var/run/nginx.pid;
load_module "modules/ngx_http_headers_more_filter_module.so";
load_module "modules/ngx_http_naxsi_module.so";
events {
    use epoll;
    worker_connections  2048;
    multi_accept on;
}
`

**Comment by wargio** [comment]
`include /etc/nginx/naxsi_core.rules;` must be in the `http` context.

**Comment by rickygm** [comment]
Hi wargio, there it is, if you look at the http { block, I just close geo $naxsi_witl {}

**Comment by wargio** [comment]
to me kinda looks like the module did not load

**Comment by rickygm** [comment]
I did a couple of successful tests using nginx version 1.20.2 

1- compile the nbs-system/naxsi version and no problem.

2- compile your fork and no problem.

`nginx version: nginx/1.20.2
built by gcc 8.5.0 20210514 (Red Hat 8.5.0-10) (GCC) 
built with OpenSSL 1.1.1q  5 Jul 2022
TLS SNI support enabled
configure arguments: --user=nginx --group=nginx --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --with-http_addition_module --with-http_flv_module --with-http_gzip_static_module --with-http_gunzip_module --with-http_stub_status_module --with-pcre --with-file-aio --with-threads --with-http_realip_module --add-dynamic-module=/rpm/naxsi/naxsi_src --add-module=/rpm/incubator-pagespeed-ngx-1.13.35.2-stable --with-http_slice_module --with-http_v2_module --without-mail_pop3_module --without-mail_smtp_module --with-debug --with-http_geoip_module --add-module=/rpm/ngx_brotli --with-compat --with-http_auth_request_module --with-http_mp4_module --with-openssl=/rpm/openssl-1.1.1q --with-http_stub_status_module --with-http_ssl_module --add-module=/rpm/ngx_cache_purge --with-http_xslt_module --add-module=/rpm/nginx_cookie_flag_module --add-dynamic-module=/rpm/headers-more-nginx-module --add-dynamic-module=/rpm/ngx_http_substitutions_filter_module --add-dynamic-module=/rpm/ModSecurity-nginx --add-module=/rpm/nginx-rtmp-module --add-dynamic-module=/rpm/ngx_devel_kit-0.3.1 --add-dynamic-module=/rpm/lua-nginx-module-0.10.20`


`nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
`

**Comment by wargio** [comment]
on my server i'm using `nginx/1.22.0` and everything works. so you must be doing something wrong.

**Comment by rickygm** [comment]
it is strange , in these last versions of nginx 1.22 and 1.23.1 , I have the same message with naxsi , I am using almalinux 8.x

**Comment by wargio** [comment]
i guess the package format is RPM ?

**Comment by rickygm** [comment]
no , I'm compiling nginx from source

**Comment by rickygm** [comment]
thank Margo for you support , I did the test again with version 1.22.0, compiled from the source and did not present the previous errors, I do not know what could be happening, I did what you have in the readme Build naxsi

`nginx version: nginx/1.22.0
built by gcc 8.5.0 20210514 (Red Hat 8.5.0-10) (GCC) 
built with OpenSSL 1.1.1q  5 Jul 2022
TLS SNI support enabled
`
`nginx -t`
`nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful`

**Comment by wargio** [comment]
maybe you had a module version mismatch

**Comment by rickygm** [comment]
fixed your  name :) , I forgot to mention that I only added these modules to the compilation, previously I did not do it. `--with-pcre --with-pcre-jit`
