### ISSUE TITLE
Feature request: Expose Prometheus metrics for naxsi

### ISSUE THREAD

**Issue by phucnv282** [nbs-system/naxsi#617]

**Comment by wargio** [comment]
not sure to follow this request: do you want to have the metrics from naxsi and import them to Prometheus or you want some whitelist rules to expose Prometheus from a deployed nginx+naxsi ?

**Comment by phucnv282** [comment]
I mean that we have the metrics from Naxsi and import them to Prometheus, then I can show them on Grafana as your previous
