### ISSUE TITLE
Configuration File nginx.conf test failed

### ISSUE THREAD

**Issue by CSmithy123** [nbs-system/naxsi#619]
Hello, 

Im getting an error previously seen under: https://github.com/nbs-system/naxsi/issues/593

I managed to get naxsi running on nginx 1.21.4 fine (pre pcre2) as i couldn't get it to work on any newer version of nginx. I noticed under https://github.com/nbs-system/naxsi/issues/618 that some merges have been reuploaded however i can't get this to work on nginx 1.23.1. Just to confirm naxsi_core.rules is included within the http context, and naxsi_rules is under location in nginx.conf.

Compiled Nginx from source with Naxsi bundled in (error message occurs when starting nginx) and log logs are providing any more detail.

**Comment by wargio** [comment]
please do not use this repo and use this: https://github.com/wargio/naxsi

**Comment by nausixkiz** [comment]
> please do not use this repo and use this: https://github.com/wargio/naxsi
Hi @wargio ,
Can we still can use new repos to build naxsi as a dynamic extension??

**Comment by wargio** [comment]
yes ofc.
