### ISSUE TITLE
How to whitelist the internal rule 20

### ISSUE THREAD

**Issue by choufenging** [nbs-system/naxsi#623]
for some reason, I add naxsi module in nginx，the config just like this：
```
#naxsi_waf
      SecRulesEnabled; 
      LearningMode; 
      LibInjectionSql; 
      LibInjectionXss; 
      DeniedUrl "/RequestDenied"; 
      CheckRule "$SQL >= 8" BLOCK; #the action to take when the $SQL score is superior or equal to 8
      CheckRule "$RFI >= 8" BLOCK;
      CheckRule "$TRAVERSAL >= 5" BLOCK;
      CheckRule "$UPLOAD >= 5" BLOCK;
      CheckRule "$XSS >= 8" BLOCK;
```
As you can see, I enable learning mode, but when I access to some url, naxi still intercept it. The error just like this:
```
2022/10/14 11:32:43 [error] 23418#0: *1222796 NAXSI_FMT: ip=116.24.65.9&server=15700.sit-cnstarr.51zxtx.com&uri=/admincp/cargo/insured_confirm_handler&vers=1.3&total_processed=1&total_blocked=1&config=learning-drop&cscore0=$SQL&score0=4&zone0=HEADERS&id0=1000&var_name0=cookie&zone1=BODY&id1=20&var_name1=&zone2=BODY&id2=20&var_name2=&zone3=BODY&id3=20&var_name3=, client: 116.24.65.9, server: *.sit-cnstarr.51zxtx.com, request: "POST /admincp/cargo/insured_confirm_handler?SerialNo=zxtx6348d3e183c68253141978&_curcid=15700 HTTP/1.1", host: "15700.sit-cnstarr.51zxtx.com", referrer: "http://15700.sit-cnstarr.51zxtx.com/admincp/cargo/insured_confirm?_curcid=15700"
```

I try to delete the rule of 20th (`#@MainRule "msg:bad utf8" id:20;`) in `naxsi_core.rules` ,then I restart nginx.
But I still can see the same error of naxi

**Comment by wargio** [comment]
eheh, rule 20 is hardcoded (like any internal rule) and is not parsed from the `naxsi_core.rules`.
**Be sure to use my repository** https://github.com/wargio/naxsi because there was a bug in the code checking for bad utf-8 which got fixed recently.

If the issue persist then you can use a whitelist rule to bypass this `BasicRule wl:20 "mz:$BODY|$URL:/admincp/cargo/insured_confirm_handler";`

**Comment by wargio** [comment]
regexes, for example, are totally broken in this repo due changes in nginx. use my repository.

**Comment by Napsty** [comment]
> regexes, for example, are totally broken in this repo due changes in nginx. use my repository.

Thank you, appreciate it very much.

**Comment by choufenging** [comment]
thanks
