### ISSUE TITLE
Move to new repository

### ISSUE THREAD

**Issue by ze42** [nbs-system/naxsi#630]
@wargio

As NBS-System does not seem to have any interest in continuing development on naxsi, I suggest making a PR:
* moving current readme as old
* making a new readme clearly stating explicitly to check your repository https://github.com/wargio/naxsi

If you create the PR, I'll try to confirm with the team that they clearly don't plan on investing any on that project, and agree to merge it. That should probably help... that is if you want to continue working on the project (which seems to be the case, as your repo is still getting some commit, and I have not seen anyone else do anything in years here)

**Comment by wargio** [comment]
hey Ze! let me open a PR and see. We could merge my PR (once confirmed on your side) and then archive the repo. I will add some big badge with the NBS logo on my repo if needed.
