### ISSUE TITLE
how can i do test using naxsi

### ISSUE THREAD

**Issue by R4Y-R4Y** [nbs-system/naxsi#632]
i want to do a simulation that demonstrates the capability of naxsi nginx web app firewall on some attacks
how can i do that?

**Comment by wargio** [comment]
First, do not use this repo and instead use mine: https://github.com/wargio/naxsi
Second, [compile naxsi](https://github.com/wargio/naxsi#build-naxsi) and deploy it in a vm then run some tools like sqlmap etc...
Remember that the key is to configure the WAF according to your needs (i.e. avoid deploying rules that are useful for wordpress if you do not run wordpress, for example) and always ensure to enable the waf in the needed locations (i.e. avoid setting it for example in admin paths etc.. which cannot be accessed by any normal traffic, and instead use ip filtering for those)

**Comment by R4Y-R4Y** [comment]
what tools would be the best to test naxsi?

**Comment by wargio** [comment]
any pentest tool for webapps. there isn't 'a tool' with which you test naxsi.
Naxsi is supposed to help you to block obvious threats, like automated scans, etc..

**Comment by R4Y-R4Y** [comment]
Could you recommend examples of popular pentest open source tools?

**Comment by wargio** [comment]
[Just google it](https://letmegooglethat.com/?q=pentest+open+source+tools) there are plenty

**Comment by wargio** [comment]
[There are plenty which you could use](https://www.google.com/search?q=pentest+open+source+tools)
