### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by jirutka** [nbs-system/naxsi#633]
The last release is three years old and there are important bug fixes in master.

**Comment by wargio** [comment]
You can find the latest version here: https://github.com/wargio/naxsi
There are more bug fixes.

For your info, i'm the only developer left on this project.
https://github.com/nbs-system/naxsi/issues/630

**Comment by jirutka** [comment]
Thanks! I’ll update nginx-mod-http-naxsi in Alpine Linux.
