### ISSUE TITLE
Error binary compatible nginx

### ISSUE THREAD

**Issue by Rafli277** [nbs-system/naxsi#634]
nginx: [emerg] module "/usr/local/src/nginx-1.18.0/objs/ngx_http_naxsi_module.so" is not binary compatible in /etc/nginx/nginx.conf:5
nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by wargio** [comment]
Please use the latest version from this repo: https://github.com/wargio/naxsi

**Comment by wargio** [comment]
use my latest release. this repo is abandoned (https://github.com/nbs-system/naxsi/issues/630)

**Comment by ze42** [comment]
Please, use the already mentioned repository.

If you have an issue with it, open an issue there, and specify which commit you use.

Do not post any reply here, or open any other issue on this repository.
