### ISSUE TITLE
Building Naxsi on Kali Purple

### ISSUE THREAD

**Issue by linked-kiwi** [nbs-system/naxsi#639]
I would like to demonstrate the use of a WAF-capable proxy on Kali Purple.  I firstly tried loading the deb package (1.3) for Debian Bullseye but on install nginx reported [emerg] 5996:5996 dlopen() :/usr/share/nginx/modules/ngx_http_naxsi_module.so failed.  Debian Buster also failed with the same error. Is it possible to get a Naxsi build that would work with Kali/Kali Purple?

Although I'd prefer to use the prebuilt package, I did try to build it. In attempting to build Naxsi (1.3) with Nginx (1.24.0) on the Kali Purple platform I get the error message: src/event/ngx_event_udp.h:38:27: error: field pkt6 has incomplete type.  This is followed by the error ../naxsi-1.3/naxsi_src//naxsi_runtime.c:2856:36: error 'r->headers_in.x_forwarded_for' is a pointer, did you mean to use '->'?  There are then follow on errors in using r->.

**Comment by wargio** [comment]
don't use this repository since has been deprecated.
Use mine instead: https://github.com/wargio/naxsi
For more info: https://github.com/nbs-system/naxsi/issues/630

**Comment by linked-kiwi** [comment]
Giovanni - thank you!
